### ISSUE TITLE
Improve ground objects

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#1000]
Improve ground objects

1) the hose is not properly connected to the aircraft
2) the textures of the cones and the fuel tank are quite bad, the latter being particularly low res
3) the ladder could also use some texturing
4) we could attempt to add the reflection effect to them, as to match the look of the aircraft

![fg-1](https://user-images.githubusercontent.com/5700795/37165663-183c2b6a-22f5-11e8-9f26-d24953b4e25e.jpg)
![fg-2](https://user-images.githubusercontent.com/5700795/37165664-18705a3e-22f5-11e8-8e09-5f89a6a203f0.jpg)
![fg-3](https://user-images.githubusercontent.com/5700795/37165665-189584e4-22f5-11e8-8423-8abdd6406f1c.jpg)

**Comment by gilbertohasnofb** [comment]
@wlbragg we could consider working on this in the future, but there is absolutely no rush in tackling this.

**Comment by gilbertohasnofb** [comment]
Ok, I started working on this and here is what I did so far:

* new textures for everything but the power unit
* fixed the power unit cable not properly touching the aircraft fuselage

![fg-0](https://user-images.githubusercontent.com/5700795/37242835-ad443aea-2467-11e8-94e7-5e81063347ca.jpg)
![fg-1](https://user-images.githubusercontent.com/5700795/37242836-ad6401ae-2467-11e8-8435-b2291c47b4c2.jpg)
![fg-2](https://user-images.githubusercontent.com/5700795/37242837-ad878d40-2467-11e8-9b0f-4892c9d45a8c.jpg)
![fg-3](https://user-images.githubusercontent.com/5700795/37242838-ada2ded8-2467-11e8-9612-63d3de2e0b7c.jpg)


missing:
* better UV-map of the fuel tank
* can ground equipment objects be saved between sessions?

@wlbragg about the UV-map, could you give me a hand? I needed a new texture for those ugly black boxes which are above the wheel, so I had to steal a bit of the metallic texture (it used to be double the current side). So this is the new texture:

![ref](https://user-images.githubusercontent.com/5700795/37242830-9f3834ba-2467-11e8-8758-a1c8377824e7.jpg)

And here are the problematic areas that need to be re-UV-mapped:

![fg-4](https://user-images.githubusercontent.com/5700795/37242831-a2f58e0e-2467-11e8-8c9f-c53dfcb06d6e.jpg)

**Comment by gilbertohasnofb** [comment]
the branch is called `issue-1000`

**Comment by wlbragg** [comment]
I pushed the new mapping.
