### ISSUE TITLE
Missing tooltips / hovered information

### ISSUE THREAD

**Issue by mathieugouin** [c172p-team/c172p-detailed#1001]
The following Equipments / Items are missing tooltips information.  (not sure the right term: the text that is displayed when mouse hover).

I find it really helps to understand the aircraft.  Also, it helps when in low light condition (ex: evening, night flying).

# KMA-20 (Audio panel)
* Marker selection

# KX-165 (NAV/COM)
* Swap button
* Frequency knob
* NAV: Pull/Ident: display both volume (already done) and Ident status (missing).

# KR-87 (ADF)
* All buttons & knob

# KI-266 (DME)
* All buttons & knob

# KAP-140 (Autopilot)
* Edit knob

For reference:

![image](https://user-images.githubusercontent.com/11562302/37248663-08f46110-24a6-11e8-903c-8c7256e75100.png)

**Comment by mathieugouin** [comment]
I plan on working on this issue and propose a pull request when ready.

**Comment by gilbertohasnofb** [comment]
@mathieugouin That's great, Mathieu. Looking forward to your PR!

**Comment by mathieugouin** [comment]
Note to myself: DME done.

**Comment by mathieugouin** [comment]
Note to myself: NAV/COM1 done.

**Comment by mathieugouin** [comment]
Note to myself: NAV/COM2 done.

**Comment by onox** [comment]
@mathieugouin You can create a checklist in comments on Github:

- [ ] Not done yet
- [x] Done

**Comment by mathieugouin** [comment]
Thanks! sorry about the spam...

**Comment by mathieugouin** [comment]
- [ ] KMA-20 (Audio panel)
- [x] KX-165 (NAV/COM 1)
- [x] KX-165 (NAV/COM 2)
- [ ] KR-87 (ADF)
- [x] KI-266 (DME)
- [ ] KAP-140 (Autopilot)

**Comment by onox** [comment]
Hey @mathieugouin, are you able to add the last remaining bits so we can close this issue? :smiley:

**Comment by mathieugouin** [comment]
Hello @onox sorry, it takes me more time than expected.

I'm struggling with combining 2 information into a single tooltip for the NAV volume knob.  It relates to https://github.com/c172p-team/c172p-detailed/pull/990.

I was hoping to combine the volume & the pull/push state into one tooltip to help see if the knob is pulled or not.

It works partially, but it is not updated live.  When I adjust the volume while the tooltip is displayed, the tooltip is refreshed for the volume portion, but if I push/pull the knob, this portion is not refreshed.  I need to move the mouse away from the tooltip and back over it for the updated string to be displayed.

Do you have any idea?

Ex:

```
        <hovered>
            <binding>
                <command>set-tooltip</command>
                <tooltip-id>nav-volume</tooltip-id>
                <label>%s</label>
                <measure-text>NAV1 Volume: 100%, Ident disabled (Shift + click to pull)</measure-text>
                <property alias="../../../../params/nav-volume"/>
                <mapping>nasal</mapping>
                <script>
                  var v = arg[0];
                  # TBD MGouin: this property does not seem to be refreshed "live"
                  var a = getprop("/instrumentation/nav[0]/ident-audible");

                  var s = "NAV1 Volume: ";
                  s = s ~ sprintf("%d", v * 100);
                  s = s ~ "%, Ident ";
                  if (a)
                    s = s ~ "enabled (Shift + click to push)";
                  else
                    s = s ~ "disabled (Shift + click to pull)";

                  return s;
                </script>
            </binding>
        </hovered>
```

**Comment by wlbragg** [comment]
Guessing here...
The property that automatically will be refreshed is
~~~
<property alias="../../../../params/nav-volume"/>
~~~
What if you do a second
~~~
<binding>
</binding>
below the fist to do the other property (the one that isn't updating.

Both bindings then need to do the entire concatenation logic however.

So no mater which button is pushed it will run through the entire concatenation logic sequence?

**Comment by mathieugouin** [comment]
Thanks for the tip, I will try that!  Very good idea.  I will let you know.

**Comment by mathieugouin** [comment]
I tried and it's not working... 

I don't know if this can be an issue, but I'm using a knob with a custom shift-action.

**Comment by wlbragg** [comment]
@mathieugouin is it one animation then or are there two separate animations?
Can you post the entire bit of code here?

**Comment by mathieugouin** [comment]
Yes, It is done in a single animation.

Refer to my work in progress branch:
https://github.com/mathieugouin/c172p-detailed/blob/issue-1001/Models/Interior/Panel/Instruments/kx165/kx165-1.xml

**Comment by mathieugouin** [comment]
Here is the hovered portion that is not working (commented out).  I tried to implement 

```
    <animation>
        <type>translate</type>
        <object-name>NavVolume</object-name>
        <property alias="../../params/nav-audio"/>
        <factor>0.002</factor>
        <axis>
            <x>1</x>
            <y>0</y>
            <z>0</z>
        </axis>
        <!--
        <hovered>
            <binding>
                <command>set-tooltip</command>
                <tooltip-id>nav1-volume</tooltip-id>
                <label>%s</label>
                <measure-text>NAV1 Volume: 100%, Ident disabled (Shift + click to pull)</measure-text>
                <property alias="../../../../params/nav-audio"/>
                <mapping>nasal</mapping>
                <script>
                  var v = getprop("/instrumentation/nav[0]/volume");
                  var a = arg[0];

                  var s = "NAV1 Volume: ";
                  s = s ~ sprintf("%d", v * 100);
                  s = s ~ "%, Ident ";
                  if (a)
                    s = s ~ "enabled (Shift + click to push)";
                  else
                    s = s ~ "disabled (Shift + click to pull)";

                  return s;
                </script>
            </binding>
        </hovered>
        -->
    </animation>

```

**Comment by mathieugouin** [comment]
Would it be easier if I push to my branch for you to test?  Let me know.  Thanks.

**Comment by wlbragg** [comment]
No this will work. I'm just really overloaded at the moment. Hopefully I can take a few minutes here in the next day or two to see if I can help you figure it out.

In the meantime...

Is this shift-action binding something new that was added by the devs?

If so I wonder if they need to add or activate a firing for it to the tool-tip code, if that makes sense? Because there are two separate actions but only the first one appears to be firing  to the tool-tip code.

Didn't you originally try to do it all in the first tool tip binding?
You made the second one, kind of on my suggestion, right?
I was more referring to using two separate animations, I didn't realize the "shift-action" was a secondary action.

This is a real hack but what about a "script" binding in the "shift action" that resets the property alias="../../../../params/nav-volume" to its current value and see if it triggers the tooltip to change with the new shift-action data. You would need to go back to using only one tooltip (hovered binding).
I'm not sure this is even possible.

You may want to ask the devs on the mailing list about the shift-action and if it can be made to fire the hovered binding like the main "action" does?

**Comment by wkitty42** [comment]
On 04/06/2018 01:05 AM, wlbragg wrote:
> In the meantime...
> 
> Is this shift-action binding something new that was added by the devs?
> 
> If so I wonder if they need to add or activate a firing for it to the tool-tip 
> code, if that makes sense? Because there are two separate actions but only the 
> first one appears to be firing to the tool-tip code.


has anyone looked at how the airbus does it? i know that josh's craft have knobs 
that rotate, push in and pull out... rotating sets a numerical interface... 
pushing the knob in switches to something else and rotating then sets that 
something else's numerical interface... pulling the button out sets to a third 
item and spinning the knob sets the 3rd item's numerical interface...

then there is also existing library code for buttons, knobs and switches... 
surely pushing or pulling a knob is already covered in those options??? rather 
than reinventing the wheel and all that stuff... i know that some folks have 
used that code to figure out something for sliding switches...

**Comment by mathieugouin** [comment]
Ok, some history here :)

The shift action was added by me through another issue (https://github.com/c172p-team/c172p-detailed/issues/949).  See also discussion in the pull request (https://github.com/c172p-team/c172p-detailed/pull/990)

I will try your idea about "faking" the volume update.

**Comment by wlbragg** [comment]
@wkitty42 
While you may be right and they may have an example of what it is that @mathieugouin is trying to do, it is specific to the help context only and not really about the action or implementation of the animation. He's literally trying to have a single help context binding take update data from two separate actions in the same animation code block.

I would ask on the dev list about this. It may be very simple or not possible without c++ source changes.

>The shift action was added by me through another issue
@mathieugouin what I was referring to is the c++ implementation of that action, if that was new or existing. I was under the impression that there had to be some recent source code changes to implement that "shift action" action behavior.

**Comment by mathieugouin** [comment]
I looked a bit in the nasal for the tooltip and there is only one possible input.  I thought we could have more because of the arg[0]...  This led me to think that we could have arg[1], [2]... etc.  This does not seem to be possible.

We do you recommend for the way forward of this issue?  I can leave my "dual-input" tooltip idea on the side for now and the rest of the issue could be done.  Or you want to check additional stuff?

**Comment by mathieugouin** [comment]
@wlbragg Out of curiosity, do you have any updates on the issue? Thanks!

**Comment by wlbragg** [comment]
@mathieugouin No, I didn't get any response from the forum or the dev mail list.

**Comment by onox** [comment]
> When I adjust the volume while the tooltip is displayed, the tooltip is refreshed for the volume portion, but if I push/pull the knob, this portion is not refreshed. I need to move the mouse away from the tooltip and back over it for the updated string to be displayed.

@mathieugouin Can you remove/clean any testing code you still have and just accept that pushing/pulling the knob doesn't refresh the tooltip? Then you can create a PR and we create a new issue for dealing with the pushing/pulling in the future.

**Comment by mathieugouin** [comment]
Sure.  PR open.  Let me know...
