### ISSUE TITLE
Fatal exception: /position/altitude-agl-m dose not exist.

### ISSUE THREAD

**Issue by tonghuix** [c172p-team/c172p-detailed#1012]
Tested using flightgear 2018.2 and 2018.1. Then I try to checkout release/2018.1, release/2017.1, same result. 

Note that I just delete c172p in FGDATA, if not it will always load default c172 from FGDATA. So I try to replace FGDATA's c172p with this repo. It works fine!.

So I believe it should be some hard-coded path point to FGDATA.

![](https://img.vim-cn.com/b2/3c4af80e3ac6c9a410d1b08ccee0310e6e774b.png)

**Comment by wlbragg** [comment]
>Note that I just delete c172p in FGDATA, if not it will always load default c172 from FGDATA. So I try to replace FGDATA's c172p with this repo. It works fine!.
So I believe it should be some hard-coded path point to FGDATA.

I'm not totally following this.

That property is created by a filter in the system file located at c172p/Systems/ground-effects.xml and your implying that when trying to load the repo version at a path other than fgdata it looks for the missing fgdata file that you've deleted. 

First, I use both the fgdata version and the repo with an Addons/Additional aircraft location path and don't have any problem.

I just tried to duplicate your condition and I can't. I tried removing the ground-effects.xml file from fgdata and then starting my remote repo through the qtlauncher with no issue.
Then I tried removing the entire fgdata/Aircraft/c172p folder and still no issue.

So I think you have something else going on with your system. FYI, I am using 2017.3

**Comment by tonghuix** [comment]
May be the path name? My cloned repo is under c172p-detailed directory.

**Comment by wlbragg** [comment]
Maybe, I am using simply "c172p" no -directory.

**Comment by wkitty42** [comment]
On 03/16/2018 10:32 AM, Tong Hui wrote:
> Tested using flightgear 2018.2 and 2018.1. Then I try to checkout 
> release/2018.1, release/2017.1, same result.
> 
> Note that I just delete c172p in FGDATA, if not it will always load default c172 
> from FGDATA. So I try to replace FGDATA's c172p with this repo. It works fine!.


it should not if you have your paths listed in fg-aircraft properly... maybe try 
reversing their order? i have both here and can easily choose between them... if 
i can do it, other folks can, too...


-- 
  NOTE: No off-list assistance is given without prior approval.
        *Please keep mailing list traffic on the list unless*
        *a signed and pre-paid contract is in effect with us.*

**Comment by wkitty42** [comment]
On 03/16/2018 12:04 PM, Tong Hui wrote:
> May be the path name? My cloned repo is under c172p-detailed directory.


that is definitely wrong... it must be c172p which is why it must also reside in 
a different directory than FGData/Aircraft...


-- 
  NOTE: No off-list assistance is given without prior approval.
        *Please keep mailing list traffic on the list unless*
        *a signed and pre-paid contract is in effect with us.*

**Comment by tonghuix** [comment]
Thank you all above! 

It seems my fault that I should change the directory name to *c172p* to avoid the path problem.

**Comment by dany93** [comment]
For the _aircraft folder_ itself, its name _must_ be _c172p_.
This issue is common, it comes from github which sends it with the 'repository-name' at 'Download'.

Independently, you can put it in a folder for which you can freely choose the name ('My-aircraft' , 'C172P-detailed',...). After that, you have to set this folder name and path in the launcher or in the command line (`--fg-aircraft=....`). Then, the aircraft is selected by its -set name (c172p.set.xml == > 
`--aircraft=c172p`).
Of course, you can have several such folders declared in Qt (you will possibly see your c172p or else several times in the list).
You do not need to declare the FG pack folder.
