### ISSUE TITLE
Wing shading should match cockpit at their intersection

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#1013]
The part of the wings which is 'inside' the cockpit should match the colour of the rest of the cockpit walls, but at the moment they are lighter. In the image below, the red and green areas should all have the same shading:

![fg-0](https://user-images.githubusercontent.com/5700795/37555548-bd3d8cc0-29e0-11e8-8486-3564d0e521ba.jpg)

Possibly related to https://github.com/c172p-team/c172p-detailed/issues/6 since the thickness of the interior walls is addressed there.

**Comment by wlbragg** [comment]
Actually all the effects and everything are identical, the only difference is the texture the mesh is mapped to.
I can try mapping the these objects to the interior texture instead of the wing texture. They are a special case as they are wing parts with interior effects.

**Comment by gilbertohasnofb** [comment]
> I can try mapping the these objects to the interior texture instead of the wing texture. They are a special case as they are wing parts with interior effects.

We could try that. Try mapping them to the same texture as those green side walls, this way they should match (at least more or less) for every single livery

**Comment by wlbragg** [comment]
I think this is going to help.
![temp](https://user-images.githubusercontent.com/11069680/37558931-11bbf724-29ea-11e8-99aa-4338ac04e4d9.jpg)

**Comment by gilbertohasnofb** [comment]
Yes, this looks really good!
