### ISSUE TITLE
Implement fuselage imperfections

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#1014]
Implement fuselage imperfections. My first attempt using the normal maps did not work as they were affecting both the specular light channel (low angle reflections which is what we want) as well as the diffuse light channel (which is what we _don't_ want to be affected). I spoke to Thorsten about how to tackle this and he gave me some ideas which we could try to implement, I will write more on this shortly.

Images and discussion of my naive attempt using normal maps can be found here: https://github.com/c172p-team/c172p-detailed/pull/1004#issuecomment-373536844

**Comment by gilbertohasnofb** [comment]
@wlbragg do you think you might be able to give me a hand with this after we finish working with the external 3D model? I can gladly create the maps necessary for the fuselage bumps but the implementation part might be a little bit too much for me. I am just waiting for a follow up from Thorsten and then I will post here his instructions on how we could attempt to tackle this using a reflection map.

**Comment by gilbertohasnofb** [comment]
Here is what Thorsten wrote me:

> You're after shallow-angle reflections, which is what is technically known as the Fresnel term - in ALS you have the reflection-fresnel-factor parameter for that - if you set the base reflectivity fairly low and this factor high, it *should* give you only shallow angle reflection of the environment cube map.
> 
> Now, if you play with the normal map, it's going to affect every lighting channel - the specular you want, the diffuse (which is why you can see it from vertical view angles as well) and even the ambient (because ALS has an irradiance map and sky light, so ambient light is not homogeneous).
> 
> If you want only the environment reflection to be affected and only see this modulation at shallow angles, my guess is that you could get what you want by using a reflection map which contains these imperfections and then modulate the reflection map with the fresnel term. This may require some fiddling with the precise balance... but conceptually it should be what you're looking for.

So once the gigantic mesh PR is over we could consider playing with this before moving to the cockpit improvements, since those will certainly take a long time. What do you think @wlbragg ?

**Comment by gilbertohasnofb** [comment]
@wlbragg so what do you think, does this make sense to you? I can create the map that can be used for the effect (I have one created with Perlin noise which is what I was using with the normal map and it was looking very decent). The only question is what type of map do you need: just a greyscale map or does it need to be anything special?

**Comment by wlbragg** [comment]
>what type of map do you need: just a greyscale map or does it need to be anything special?

I don't know...
How did you apply the previous attempt? 
What did that map look like?

**Comment by gilbertohasnofb** [comment]
Previously I used a normal map, which is RGB. But as Thorsten correctly pointed out, a normal map will affect both types of reflection and we want only specular reflections (shallow angle reflections). 

> If you want only the environment reflection to be affected and only see this modulation at shallow angles, my guess is that you could get what you want by using a reflection map which contains these imperfections and then modulate the reflection map with the fresnel term. 

Do you understand how exactly to implement this or do you know any other aircraft with similar implementation? In theory, I think we could just use a greyscale texture for the map since we just need one channel (intensity of effect).

**Comment by gilbertohasnofb** [comment]
I was hoping something like this would suffice:

![fuselage_imperfections_map](https://user-images.githubusercontent.com/5700795/37630145-bb82b468-2bda-11e8-89ea-e7c0bbd0bfda.png)

But the question is then how to implement this.

**Comment by wlbragg** [comment]
OK, after re-reading this, then I think we should replace the current reflection map with this and adjust. That would be in bumpspec.eff the current cube is 
Aircraft/Generic/Effects/CubeMaps/buildings/N.png, etc...

**Comment by wlbragg** [comment]
Now we have a couple choices I think, use just this map?. Or add this noise to a copy of the current map?

**Comment by gilbertohasnofb** [comment]
I don't think we want to replace that cube map as this map I created above is not 'what' will be reflect but rather the amount of reflection at shallow angles. We want to keep both effects if that makes sense.

**Comment by gilbertohasnofb** [comment]
Look in particular the two shots of the wing on the before/after section of this comment here: https://github.com/c172p-team/c172p-detailed/pull/1004#issuecomment-373548406

The bumpiness only affects how each part of the wing will reflect, but the content of the reflection is still `fgdata/Aircraft/Generic/Effects/CubeMaps/buildings/U.png`, which is the sky texture

**Comment by gilbertohasnofb** [comment]
What if we define a new effect `spec.eff` based on `bumpspec.eff` but without the normal stuff? Could both effects then be applied to the fuselage, wings and tail?

**Comment by wlbragg** [comment]
Yeah but there is a  mechanism for each effect, I don't know that you have an option for a third map on top of it all?

>Could both effects then be applied to the fuselage, wings and tail?

I'm not sure I follow you, You can't apply two separate effects to one object.

Or are you saying we lose the normals map?

**Comment by wlbragg** [comment]
Oops, got carried away with the mouse click.

**Comment by wlbragg** [comment]
You have this
~~~
<texture n= "5" >
        <type>cubemap</type>
        <images>
            <positive-x>Aircraft/Generic/Effects/CubeMaps/buildings/N.png</positive-x>
            <negative-x>Aircraft/Generic/Effects/CubeMaps/buildings/S.png</negative-x>
            <positive-y>Aircraft/Generic/Effects/CubeMaps/buildings/W.png</positive-y>
            <negative-y>Aircraft/Generic/Effects/CubeMaps/buildings/E.png</negative-y>
            <positive-z>Aircraft/Generic/Effects/CubeMaps/buildings/U.png</positive-z>
            <negative-z>Aircraft/Generic/Effects/CubeMaps/buildings/D.png</negative-z>
        </images>
    </texture>
~~~
and this
~~~
<texture n="2">
      <image>Aircraft/c172p/Models/fuselage-normal.png</image>
      <filter>linear-mipmap-linear</filter>
      <wrap-s>repeat</wrap-s>
      <wrap-t>repeat</wrap-t>
      <internal-format>normalized</internal-format>
    </texture>
~~~
It sounds like he is talking about doing this with the reflection cube. The only way I envision this is by modifying that cube.

**Comment by wlbragg** [comment]
And the adjustment to the reflection cube that he is referring to is this...
~~~
    <reflection-fresnel-factor type="float">0.6</reflection-fresnel-factor>
~~~

**Comment by wlbragg** [comment]
I don't don't know enough about it, you may have to ask for specifics of exactly how to implement this.

**Comment by gilbertohasnofb** [comment]
> Or are you saying we lose the normals map?

No, I wasn't sure if more than one effect could be applied. 

> Yeah but there is a mechanism for each effect, I don't know that you have an option for a third map on top of it all?

I see. I am really ignorant on how effects work in FG so this is a tough one. 

> It sounds like he is talking about doing this with the reflection cube. The only way I envision this is by modifying that cube.

But I am not sure how that would achieve similar results as in those images I previously posted. I will make some experiments with these effects and report my results here.

**Comment by wlbragg** [comment]
I may be totally off base here but can you overlay this on top of the reflection map we currently use with is 6 of these types of images.
![d](https://user-images.githubusercontent.com/11069680/37630674-e5c00d9c-2bb3-11e8-8d2f-b86a790884ee.png)

**Comment by gilbertohasnofb** [comment]
That would not work either, as the bumps should have fixed coordinates in relation to the fuselage, while the world cubemap rotates as the aircraft changes its position.

**Comment by wlbragg** [comment]
OK, yeah this is beyond my knowledge base.

**Comment by gilbertohasnofb** [comment]
@wlbragg Just found in http://wiki.flightgear.org/Howto:Use_the_normal_map_effect_in_aircraft that the alpha channel in a normal map controls the specular reflections. I will experiment with that.

**Comment by wlbragg** [comment]
Ah, OK then, so you do technically combine your noise image with the normals map but in the alpha channel.
I did the four channel lightmap for the shuttle so I do have limited experience manipulating the channels. I remember it wasn't the most intuitive thing I have ever done though, especially the alpha channel as your results (final image) ends up with a degree of transparency (alpha).
Let me know if you need something.

**Comment by gilbertohasnofb** [comment]
I am used to working with alpha channels as a separate map as I did a couple of textures like this for Oolite (an amazing open source version of Elite). Anyway, I did a preliminary test but things didn't go too well: the alpha channel simply dictates how reflective a surface is, and that's not what we want. Bumps are not less reflective, they just reflect light from a different angle. So basically I am starting to think I want something that doesn't exist (yet) in FG:

* I don't want a reflection map, as that changes the point it is map into in the aircraft surface as the viewing angle changes.
* I don't want a specular mask map, as I don't want to make the fuselage less reflective in certain areas.
* I don't want a regular normal map as that affects both diffuse and specular light, not only the latter.

The closest good result so far was with the normal map, but it looks like rubbish from acute angles when the diffuse light takes over. I will make some further experiments then write Thorsten again.

**Comment by wlbragg** [comment]
>as that changes the point it is map into in the aircraft surface as the viewing angle changes.

That does sound like what you want to get your distortion?

**Comment by gilbertohasnofb** [comment]
Yes, I want to simulate the distortions of the fuselage. Our aircraft looks like a perfectly flat board when reflecting light at a low angle, but in reality GA aircraft are full of imperfections. This is what X-Plane 11 simulates and that's what I am trying to achieve. Look at the reflections below, see how they are all irregular, a bit like reflections on water. That's because the fuselage is all bumpy:

![](https://user-images.githubusercontent.com/5700795/37492950-3384be22-289b-11e8-88a0-d887bde19d06.png)

Here is a RL photo showing it:

![image](https://user-images.githubusercontent.com/5700795/37676400-c08fb2d6-2c6f-11e8-97e8-be6e184409b8.png)

And this is quite evident in a metallic GA plane such as an old Cessna 170:

![](https://www.ataviation.uk/wp-content/uploads/2017/09/IMG_9710-1024x682.jpg)
