### ISSUE TITLE
Gyroscope sound can be heard outside the aircraft

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p-detailed#1015]
Playing the sound only while inside (or perhaps, near the aircraft?) would help?

Can still here the gyro from over here:
![image](https://user-images.githubusercontent.com/10434911/37557912-8858f88c-2a03-11e8-8b88-3a02e5f81d4b.png)

**Comment by gilbertohasnofb** [comment]
@onox I can reproduce it, but I don't understand why is this the case since the gyro sound has these lines:

```
            <reference-dist>0.2</reference-dist>
            <max-dist>5.0</max-dist>
```

Do you have some advice?

**Comment by legoboyvdlp** [comment]
Perhaps it is because I zoomed out, not adjusting the max distance.

**Comment by gilbertohasnofb** [comment]
I tried adjusting the distance and I didn't hear any difference

**Comment by legoboyvdlp** [comment]
the sound can be heard up to 100m away, (adjusting it in view > view position)

**Comment by wkitty42** [comment]
On 03/17/2018 01:02 PM, Gilberto Agostinho wrote:
> @onox <https://github.com/onox> I can reproduce it, but I don't understand why 
> is this the case since the gyro sound has these lines:
> 
> |<reference-dist>0.2</reference-dist> <max-dist>5.0</max-dist> |


what is that 5.0? meters?? that's 15 feet and much too far away ;)

**Comment by onox** [comment]
@legoboyvdlp Did you zoom out with Shift + x? Or with the mouse scroll wheel (in the Helicopter View)

**Comment by onox** [comment]
Can it be reproduced by not messing with the view position, but only with the distance using mouse scroll wheel?

**Comment by onox** [comment]
IIRC `<max-dist>5.0</max-dist>` should be the distance where volume is 0, but I'm not 100 % sure about that.

**Comment by legoboyvdlp** [comment]
I zoomed with shift x, then adjusted view position manually woth the dialog on my second test.

**Comment by gilbertohasnofb** [comment]
@onox in Helicopter View, using the mouse scroll wheel, I got as far as 150m from the aircraft and I still listen to the sound

@wkitty42 I agree that those values might need some tweaking, but first it is needed to figure out why the max distance is broken. Once that is fixed then I will gladly tweak things around.

**Comment by gilbertohasnofb** [comment]
According to the wiki:

>  <reference-dist>
>     Set a reference distance of sound in meters. This is the distance where the volume is at its maximum.
> 
>     Volume is clamped to this maximum for any distance below.
> 
>     Volume is attenuated for any distance above.
> 
>     Attenuation depends on reference and maximum distance. See OpenAL specification on "AL_INVERSE_DISTANCE_CLAMPED" mode for details on exact computation.
> 
> <max-dist>
>     Set the maximum audible distance for the sound in meters.
> 
>     Sound is cut-off above this distance.

So I am quite puzzled why this isn't working for the gyro sound.

**Comment by gilbertohasnofb** [comment]
Ok, I somehow figured it out, but the sound implementation in FG does look buggy:

* if a sound is of type `<type>avionics</type>` then it is not affected by the max-distance
* when the `<max-dist>` was set to `5.0` it would simply cut off at that point. When setting it to `50.0` it smoothly lowers its volume and it's barely audible from the outside view. I will use this value as the result is quite convincing.

**Comment by wkitty42** [comment]
On 03/18/2018 09:00 AM, Gilberto Agostinho wrote:
> @onox <https://github.com/onox> in Helicopter View, using the mouse scroll 
> wheel, I got as far as 150m from the aircraft and I still listen to the sound
> 
> @wkitty42 <https://github.com/wkitty42> I agree that those values might need 
> some tweaking, but first it is needed to figure out why the max distance is 
> broken. Once that is fixed then I will gladly tweak things around.


i'm starting to wonder if the zoom stuff is just visual only and not actually 
positioning your body... what happens if you use the walker and walk around... 
that would probably be the better test... especially is the zoom is only a 
visual thing like using binoculars...

**Comment by gilbertohasnofb** [comment]
I don't think the zoom is the problem but rather how sounds are implemented. I get the same results whether I change the distance to a sound source with an internal camera, walker or external camera

**Comment by wkitty42** [comment]
On 03/18/2018 10:31 AM, Gilberto Agostinho wrote:
> I don't think the zoom is the problem but rather how sounds are implemented. I 
> get the same results whether I change the distance to a sound source with an 
> internal camera, walker or external camera


ok... my thinking was that zooming was keeping the body in one place and using a 
set of binoculars to zoom in or out of the view... with the body still in place, 
the distance doesn't change... that's why i suggested using the walker... i 
don't understand the camera stuff other than it being a body's position and then 
binocing the view to make it larger (looks closer) or smaller (looks further 
away)...

**Comment by gilbertohasnofb** [comment]
@wkitty42 in the helicopter camera and with the mouse in the standard mode (i.e. clicks toggle hotspots) then the mouse wheel becomes distance. If you change the mouse mode to the viewing mode (in which moving the mouse causes the camera to move around) then the mouse wheel is zoom. In any other view the mouse wheel is set to zoom, not distance.
