### ISSUE TITLE
ALT output jumps between 11% and 13% throttle.

### ISSUE THREAD

**Issue by wkitty42** [c172p-team/c172p-detailed#1017]
I'm testing the `bug-1015` branch but I don't think it matters for this. Anyway, while playing around running the engine up and down listening for the gyro whine, I realized that with the throttle at 13% I have ""good"" AMP output on the gauge. If I drop the throttle one level (PgDn) it drops to 11% and the AMP reading drops below 0 (zero) on the left half of the gauge. This is with the battery switch ON. Turn the battery switch OFF and the AMP needle stays above zero even with the throttle down to 0%. Surprisingly enough, the engine stays running with the throttle at zero no matter the battery switch position.

**Comment by gilbertohasnofb** [comment]
Good catch, I really don't know why this is happening. @dany93 @onox ?

Just two comments on what you wrote:

> i'm testing the bug-1015 branch but i don't think it matters for this... 

Certainly it is not related, that branch only touches the sound xml file.

> turn the battery switch OFF and the AMP needle stays above zero even with the throttle down to 0%... surprisingly enough, the engine stays running with the throttle at zero no matter the battery switch position...

In relation to the engine, I believe the battery is only used by the starter when starting the engine. Once it is running, turning off your battery won't do anything to the engine even if that is at idle. But someone please correct me if I am wrong on this.

**Comment by wkitty42** [comment]
yeah, even in a car, you can disconnect the battery IF the alternator is good and outputting the proper voltage... that's actually how we (TINW) test that our alternator is working when we're having electrical problems :laughing:  if the alternator isn't putting out enough power, the engine will die... if it is working properly, you won't even notice a change when the battery is disconnected...

**Comment by dany93** [comment]
It is somewhat different from a car.
In a car, the spark transient high voltage is given, anciently by  a DC voltage breaker and a coil, currently by an electronic circuit. The DC voltage (12 V) can be due to the battery or the alternator with rectifying diodes.

At my knowledge:
In an aircraft engine, the plug spark is triggered by a magneto (two magnetos per sparking plug for security). You do not need any DC power supply. The alternator is just to recharge the battery.

**Comment by legoboyvdlp** [comment]
I believe there was an issue about the ammeter and how the gauge needs to be proeprly simulated at some previous point?

**Comment by onox** [comment]
Yes, #37 and #38

**Comment by gilbertohasnofb** [comment]
@onox So should this be closed as a duplicate and we add the information to those other issues?

**Comment by algefaen** [comment]
@dany93 is correct, when the engine is running you don't need battery or alternator at all, since the spark plugs get their power from the magnetos. I've had a total electrical failure when my alternator died and battery drained in-flight, so I'm very happy that this is the case. (=

I'm not 100% sure what would happen if you have low alternator output and turn the battery switch off, sounds like something you should not be doing if the avionics are on...

**Comment by wkitty42** [comment]
On 03/19/2018 04:56 AM, algefaen wrote:
> @dany93 <https://github.com/dany93> is correct, when the engine is running you 
> don't need battery or alternator at all, since the spark plugs get their power 
> from the magnetos. I've had a total electrical failure when my alternator died 
> and battery drained in-flight, so I'm very happy that this is the case. (=


yes, i kinda did forget about this aspect with my comments about the engine 
still running with the throttle at zero... later i realized that's like a car so 
it should have been at it lowest idle which it was so that part is good... what 
i was really looking at was with the engine throttled up, the ALT output 
remained the same a tick over the zero line... it never rose up to a higher 
output indication... there is a clamp, yes, but it isn't that low... generally 
speaking, of course...

plus i saw this weird jump when throttling down and it attracted my attention... 
so i created this issue... if you (the team) want to link it to the others, 
that's fine... it is just something else to fix :)


> I'm not 100% sure what would happen if you have low alternator output and turn 
> the battery switch off, sounds like something you should not be doing if the 
> avionics are on...


this is true... low voltage will result in higher current which can lead to 
damage and the release of the majik smoke in the chips :smile:

**Comment by onox** [comment]
@gilbertohasnofb Yes
