### ISSUE TITLE
Engine Oil Capacity

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p-detailed#1020]
![image](https://user-images.githubusercontent.com/10434911/37612099-21b3dba2-2b9c-11e8-878c-f99786a5cde2.png)

According to this, should I leave the oil capacity as it is, or add another quart?

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp what you measure is the oil in the sump. The extra 1 quart is inside the engine at all times. So I would say that we have it correct already. If you agree I will close this as invalid.
