### ISSUE TITLE
Add movement and sound for Primer

### ISSUE THREAD

**Issue by tonghuix** [c172p-team/c172p-detailed#1021]
First, I consider it as a *low-priority* enhancement.

 Please see the video from 1:36 about priming the engine, in real world primer not just 'In' and 'Out' two state, it also has a process from out to in, and also a 'lock' progress. 

https://www.youtube.com/watch?v=HcomtC_DSlc

To enhance the reality, I suggest add a movement for primer and sound as well.

**Comment by wkitty42** [comment]
On 03/20/2018 10:02 AM, Tong Hui wrote:
> First, I consider it as a /low-priority/ enhancement.


it is the little ones that make the big differences ;)


> Please see the video from 1:36 about priming the engine, in real world primer 
> not just 'In' and 'Out' two state, it also has a process from out to in, and 
> also a 'lock' progress.
> 
> https://www.youtube.com/watch?v=HcomtC_DSlc
> 
> To enhance the reality, I suggest add a movement for primer and sound as well.


ummm... your primer in the c172p doesn't move in and out when you click on it? 
mine does... i don't know if there's any sound associated with it, though... i 
haven't looked either... just surprised that your primer apparently doesn't move...

**Comment by gilbertohasnofb** [comment]
@ tonghuix c

I like this, thanks for the idea.

> your primer in the c172p doesn't move in and out when you click on it?

I think he meant a smooth animation between its range. At the moment, clicking on the primer just toggles it in/out.

@wlbragg @onox what do you guys think about the following change to our primer:

* the primer becomes a true lever that can be clicked and dragged, not only toggled
* the user must click and drag it in and out to fill the fuel chamber
* if the user drags the primer 1/x of the way, only 1/x of the fuel of a current one stroke is filled. 
* we could even attempt to implement the lock as follows: clicking on the primer would unlock it (showing a small rotation), then while holding it and draging in out it stays unlock. If the user then returns the primer to the full in position (as they should) then when they release the mouse button the primer would automatically 'lock' and spins counterclockwise. The lock I describe is only an animation, as clicking and dragging would immediately 'unlock' it.

**Comment by gilbertohasnofb** [comment]
Tiny bit related to https://github.com/c172p-team/c172p-detailed/issues/81 but not a duplicate: this issue here deals with animation and user interaction, that other deals with the primer implementation itself and how it affects the engine.

**Comment by wkitty42** [comment]
On 03/20/2018 11:12 AM, Gilberto Agostinho wrote:
> @ tonghuix c
> 
> I like this, thanks for the idea.
> 
>     your primer in the c172p doesn't move in and out when you click on it?
> 
> I think he meant a smooth animation between its range. At the moment, clicking 
> on the primer just toggles it in/out.


ahhh... my bad... i've never really paid any attention other than having to 
click it six times or so... that's always been painful... have thought it would 
be nicer to click once, see it slide out and slide back in with a full stroke... 
click it again and watch it go...


> @wlbragg <https://github.com/wlbragg> @onox <https://github.com/onox> what do 
> you guys think about the following change to our primer:


i thin it sounds ok but think about needing space to drag the thing out and then 
push it back... sure, it may be more realistic but it is easier with your hand 
holding it than hoping your mouse isn't going to run off the table or into the 
scanner because you weren't positioned on the table properly before grabbing the 
primer with the mouse...

what happens if you let it go mid pump? does it just stay there?

**Comment by legoboyvdlp** [comment]
It would seem by the video it is just a lever like the throttle: it should probably just stay there?

**Comment by gilbertohasnofb** [comment]
> sure, it may be more realistic but it is easier with your hand holding it than hoping your mouse isn't going to run off the table or into the scanner because you weren't positioned on the table properly before grabbing the primer with the mouse...

I don't ever drop my mouse going from idle to full throttle, perhaps you need a larger mousepad :wink: In any case, people can always use autostart.

> what happens if you let it go mid pump? does it just stay there?

Yes, just like in the real aircraft.

**Comment by tonghuix** [comment]
And...the texture of primer also need updated. 

![111](https://user-images.githubusercontent.com/423703/37675452-3db04c04-2cb0-11e8-8836-b2ee6e94988f.png)

A picture from Jeppsen Private Pilot Manual.

**Comment by gilbertohasnofb** [comment]
@tonghuix I will open a new issue for that, as that's a 3D model + texture thing. All our levers could do with some improvements.

**Comment by gilbertohasnofb** [comment]
See https://github.com/c172p-team/c172p-detailed/issues/1023
