### ISSUE TITLE
wing mapping on CAP livery is broken 

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#1029]
The UV-mapping  of the top side of the wings of the CAP livery is utterly broken since we added the wing edge object and remapped the wing. There are two possible solutions to this, both with negative sides:

* attempt to re-UV-map the top of the wings, risking to affect the other liveries, all of which look fine
* remove the CAP livery and leave things as they are. This also means that anyone attempting to create a new livery in the future with a fancy top wing design will be very frustrated. That said, we have some solid HD liveries at the moment.

I am fine leaving things as they are, since I suspect the pain/gain ratio is really high on this one. @wlbragg any thoughts?

**Comment by wlbragg** [comment]
I'm looking now.

**Comment by wlbragg** [comment]
I think it is fixable without major stress. I'm attempting it now.

**Comment by wlbragg** [comment]
As I start to work on this I see I can get it really close but maybe not perfect at a couple spots without messing up either another livery or maybe the normals map again. I'll make the adjustments I know I can make without affecting either and see where it takes us.
I have a feeling to make it perfect might require small adjustments that would require major mapping adjustments.
If I had seen this one first, it might not have been all that difficult. I had no idea that we had this many variations in liveries (technical variations that is).

Bare in mind, when I started any of this livery work my mapping skills were less than amateur. I have to admit, I think I have graduated to somewhere above amateur but still well below experienced.

**Comment by wlbragg** [comment]
Done as much as I dare. It has only one issues that I know of. Because the style of the flaps changed, the livery is no longer valid. I think that would be and accurate description of what happened. So the underside of the flaps where they extend into the wing farther than originally is not mapped properly. @gilbertohasnofb maybe you can do something with the livery to fix this last issue?

**Comment by wlbragg** [comment]
Cap livery...
![cap1](https://user-images.githubusercontent.com/11069680/37992693-0ddc08f2-31d2-11e8-8d66-2a16e8c9809b.jpg)
![cap2](https://user-images.githubusercontent.com/11069680/37992695-0efd7270-31d2-11e8-86aa-8eff261fba4b.jpg)
![cap3](https://user-images.githubusercontent.com/11069680/37992696-1011ea10-31d2-11e8-81d3-15fdd30e99e7.jpg)

**Comment by gilbertohasnofb** [comment]
Looks really good, going to test it now.

**Comment by wlbragg** [comment]
This shows why the flaps mapping doesn't work anymore. I think if you edited the flaps outside corners in only the CAPS livery you might be able to fix it, but it certainly will be more of a hack than fixing the problem.
![cap4](https://user-images.githubusercontent.com/11069680/38001484-a8424936-31f2-11e8-8b5a-2bdfc8433b0d.jpg)

**Comment by gilbertohasnofb** [comment]
I don't think that is worth the pain nor the hack. This is just a legacy livery anyway and it's a miracle any of these still work after all our modifications. All others look fine, so I personally consider this problem solved.
