### ISSUE TITLE
Model the strobe light

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p-detailed#1031]
I noticed that we have a navigation light in the 3D model, but no strobe light model:
![image](https://user-images.githubusercontent.com/10434911/38040491-8a5651aa-32a7-11e8-9aa8-d76301fbf7c8.png)

as compared to 

![image](https://user-images.githubusercontent.com/10434911/38040483-83dc6058-32a7-11e8-9686-bb68dfd84ba3.png)

The procedural light should also be moved to match the model's new position. I'd also appreciate some reference images ;)

Of course, you could always model these:
![image](https://user-images.githubusercontent.com/10434911/38040426-677dc7e4-32a7-11e8-83ee-efc048d069b4.png)

😁

**Comment by gilbertohasnofb** [comment]
@wlbragg Lego is right, the strobe should also be there, all 172P photos I find show it

![](http://imgproc.airliners.net/photos/airliners/5/2/9/4763925.jpg?v=v4c6c51cca0a)

**Comment by gilbertohasnofb** [comment]
> Of course, you could always model these:

@legoboyvdlp :rofl:

**Comment by wlbragg** [comment]
You guys are killing me! OK, I agree, I realized that awhile back as I was repositioning the nav light that there was no strobe on it.
Can we live with something like this?
![strobe](https://user-images.githubusercontent.com/11069680/38054354-58414ebe-329c-11e8-93ae-1ad7f012249b.jpg)
If so we could use a better texture for the strobe part.
This is all I did to map this
![strobe1](https://user-images.githubusercontent.com/11069680/38054822-a46a3dae-329d-11e8-9e29-6854c8235b93.jpg)
However this should probably be the mapping
![strobe2](https://user-images.githubusercontent.com/11069680/38054818-a3158d64-329d-11e8-8dbc-455f2f0e3e00.jpg)

**Comment by wlbragg** [comment]
The bulb would be something like the purple area.
![strobe3](https://user-images.githubusercontent.com/11069680/38054963-08ed912c-329e-11e8-9381-0771ecfa0adf.jpg)

**Comment by gilbertohasnofb** [comment]
> You guys are killing me! OK, I agree, I realized that awhile back as I was repositioning the nav light that there was no strobe on it.

Apologies for being pushy!

> Can we live with something like this?

Absolutely, that looks good. I will make the texture now and merge that PR!

**Comment by gilbertohasnofb** [comment]
The second option for the light texture looks fine with me. Just push the model and I will work on it straight away.

**Comment by wlbragg** [comment]
I have to step out for about 30 minutes. I pushed the models but didn't have time to inspect. Also I noticed the starboard side looks like some normals (bump mapping) is in the way? The mapping is where it should be so you can at least work on that if you want. I'll investigate the bump mapping effect when I return.
