### ISSUE TITLE
Aircraft doesn't slow down fast enough on the water

### ISSUE THREAD

**Issue by onox** [c172p-team/c172p-detailed#1037]
The aircraft would unrealistically continue to glide on the water past the point where it should really start to slow down.

**Comment by dany93** [comment]
In https://github.com/c172p-team/c172p-detailed/pull/1034#issuecomment-377450086 @wlbragg wrote:
> It's somewhat of a cheat because it uses the engine rpm to decide when to apply drag VS any kind of speed measurement. The reason using speed wouldn't work......

Are you sure?

Couldn't it work by applying a non-linear drag coefficient vs speed? A non-linear drag can be realistic because the floats have two regimes: low speed, high drag, when they are plunged, partly sunk in the water, and then, above a speed value, they begin to lift and glide, giving low drag. If the regime change is not too high, the engine might be able to give enough speed to reach it. Above the regime change, that's low drag like previously.
Of course, the regime change can be progressive.

**Comment by wlbragg** [comment]
If I understand your question correctly, no I am not sure.

I thought it should, but this is something I did for the Cub a while back and I struggled getting the correct numbers to make it work.

The problem I remember encountering was you can only use this non-linear drag coefficient vs speed on landing, not on take off as it would be reversed. The property implementing the drag-tweak-force applies to both.

At point X in, lets use groundspeed-kt, the drag needed to slow the aircraft down sufficiently on landing would crush the thrust needed to take off. So the drag at that same groundspeed-kt on the takeoff end keeps you from going any faster making takeoff impossible.

I had to use a different measurement and rpm fit the bill actually pretty good.

Now that is not to say you can't tune this into the hydro-fdm that already exists. I mean that is kind of it's function to start with. But I don't have the knowledge required to figure out where in the existing code to do this. At the time, I was posting about it to the author and never remember getting an answer for this, at least not one I understood.

I stumbled on to the drag-tweak-force property, it wasn't being used, so I took advantage of it and the final results, for the J3Cub at least, is IMHO the best modeled hydro system we currently have in FG. (and believe me, right or wrong, I nudge and tweaked values on it that were not totally clear in my head exactly what they were).

I simply want to bring the c182p up to par with the J3Cub in that area, as it its after all the flagship. This property, adjusted this way, achieves the desired results.

If you can identify the "appropriate" spot in the hydro fdm code to do this, I'd be the first to adopt it in the Cub as well.

**Comment by gilbertohasnofb** [comment]
>  simply want to bring the c182p up to par with the J3Cub in that area

Being super petty, but juts pointing it out: you are referring to the c172p as c182p a couple of times. Including in the title and description of your last youtube video testing the water landing :wink: `</petty-annoying-comment>`

**Comment by wlbragg** [comment]
@gilbertohasnofb 
Thank you, I guess it was getting late here. :face_with_head_bandage:
