### ISSUE TITLE
Water rudders do not have enough influence on turning behavior

### ISSUE THREAD

**Issue by wlbragg** [c172p-team/c172p-detailed#1038]
This issue deals with the turning force and radius of the aircraft when on water with and without the rudders down.

With the rudders down we should effectively be able to turn sharply in the water at lower speeds, we can't do that now. 
We should also be able to easily control the direction of the aircraft, really at any end of the speed scale other than the most extreme, especially with rudders down,  which we cannot do now.

**Comment by wlbragg** [comment]
@dany93 How to we achieve this?

**Comment by dany93** [comment]
I would look at c172p-hydrodynamics.xml, lines 676 - 690,
and change the `<value>-0.025`
```
        <fcs_function name="hydro/rudder-yaw-moment-lbsft">
            <documentation>
                Guessestimated yaw moment due to water rudder.
            </documentation>
            <function>
                <description>Hydrodynamic yaw moment due to rudder</description>
                <product>
                    <property>/controls/gear/water-rudder-down</property>
                    <property>hydro/qbar-u-psf</property>
                    <property>hydro/float-beam-ft3</property>
                    <property>fcs/rudder-pos-norm</property>
                    <value>-0.025</value>
                </product>
            </function>
        </fcs_function>
```
