### ISSUE TITLE
Seaplane should have an anchor

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p-detailed#1040]
I feel the seaplane should have a way to stop the aircraft fully. Perhaps on water, the parking brake could toggle an anchor? I believe one of Dave Culp's aircaft, perhaps the Clipper? has this simulated.

**Comment by wlbragg** [comment]
Somewhat related is the mooring option for seaplanes. I added that system just now and next I will add a mooring line and/or anchor.

**Comment by legoboyvdlp** [comment]
Thank you ;)
