### ISSUE TITLE
Continuous error messages in multiplayer mode

### ISSUE THREAD

**Issue by mathieugouin** [c172p-team/c172p-detailed#1041]
# Steps:
* Enable multiplayer
```
--callsign=Whatever
--multiplay=out,1,mpserver02.flightgear.org,5000
```

* Start FG from the command:
`fgfs`

# Issue
The following message is repeatedly output in the console (at the same multiplayer rate, 1Hz in my example)

```
Multiplayer packet truncated prop id: 10314: sim/multiplay/generic/int[14]
```

However, the multiplayer mode seems to work: I was able to see other a/c.

**Comment by legoboyvdlp** [comment]
I was wondering if you are trying to use the old FlightGear MP Protocol introduced in 2017.2? Without it enabled in the multiplayer menu, you may get this type of error.

**Comment by onox** [comment]
Yeah, this is most likely caused by using the old MP protocol. Set the compatibility to 2017+ in the Multiplayer Settings window and the messages should disappear.

**Comment by mathieugouin** [comment]
Thank you very much!  That was the issue.
