### ISSUE TITLE
Texture of digital in AP is not clear

### ISSUE THREAD

**Issue by tonghuix** [c172p-team/c172p-detailed#1043]
See picture below.

![fgfs-screen-417](https://user-images.githubusercontent.com/423703/38227515-284ed61a-3731-11e8-8501-0c9bdf35fa0e.png)

**Comment by legoboyvdlp** [comment]
Appears to be a possible lack of  transparency in the image?

**Comment by tonghuix** [comment]
I tested c182s, the AP's texture is perfect, so maybe we could 'steal' texture file from c182s?
