### ISSUE TITLE
Repair option is available even with damage turned off

### ISSUE THREAD

**Issue by wkitty42** [c172p-team/c172p-detailed#1050]
in the aircraft options, the repair button is still available and working even when damage is turned off...

![20180406-c172p-repair-available-without-damage-option-01](https://user-images.githubusercontent.com/4641713/38440885-d4cb575c-39b0-11e8-8f91-1135f6ec935b.jpg)

**Comment by gilbertohasnofb** [comment]
If anyone implements this, please make sure that disabling damage will also fix the aircraft, else disabling damage with a broken aircraft will result in an unfixable airplane.

**Comment by wkitty42** [comment]
yes, yes, yes! this! i forgot to mention it :)
