### ISSUE TITLE
Oil instruments not indicating

### ISSUE THREAD

**Issue by okroth** [c172p-team/c172p-detailed#1056]
While doing the run-up I got shocked when I looked onto the oil pressure and temperature indicators:
![grafik](https://user-images.githubusercontent.com/10168496/38675031-cbffd134-3e56-11e8-87b7-90687e5f6654.png)
Temperature should have raised in the minutes the engine was running, and pressure must have raised within seconds.
Luckily, the engine is fine, as the property tree viewer shows.
Looks as if the oil instruments look onto the wrong property : active-engine, instead engine.
Or did someone forget to copy the values over to active-engine?

**Comment by wlbragg** [comment]
There is a filter for oil pressure and oil temp
~~~
<filter>
        <name>Engine Oil Temperature</name>
        <type>gain</type>
        <gain>
            <property>/engines/active-engine/low-oil-temperature-factor</property>
        </gain>
        <input>
            <condition>
                <equals>
                    <property>/controls/engines/active-engine</property>
                    <value>1</value>
                </equals>
            </condition>
            <property>/engines/engine[1]/oil-temperature-degf</property>
        </input>
        <input>
            <property>/engines/engine[0]/oil-temperature-degf</property>
        </input>
        <output>
            <property>/engines/active-engine/oil-temperature-degf</property>
        </output>
    </filter>
~~~
~~~
<filter>
        <name>Engine Oil Pressure</name>
        <type>gain</type>
        <gain>
            <property>/engines/active-engine/low-oil-pressure-factor</property>
        </gain>
        <input>
            <condition>
                <equals>
                    <property>/controls/engines/active-engine</property>
                    <value>1</value>
                </equals>
            </condition>
            <property>/engines/engine[1]/oil-pressure-psi</property>
        </input>
        <input>
            <property>/engines/engine[0]/oil-pressure-psi</property>
        </input>
        <output>
            <property>/engines/active-engine/oil-pressure-psi</property>
        </output>
    </filter>
~~~

**Comment by wlbragg** [comment]
I don't even know what those are, @onox?

**Comment by onox** [comment]
What are the values of the `/engines/active-engine/indicated-*` properties? You're using the 160 HP engine?

**Comment by okroth** [comment]
I am using the 160hp engine
the values say '' or none

**Comment by legoboyvdlp** [comment]
Let me test if this bug is fixed on my branch.. if so no need to fix.

**Comment by onox** [comment]
@okroth Can you repeatedly reproduce the problem?

**Comment by okroth** [comment]
It happens each time.

**Comment by legoboyvdlp** [comment]
@okroth would you by any chance be using my branch, issue-124? Probably not, but just to confirm

**Comment by okroth** [comment]
Could not find that branch, but the reeason for my trouble.
The 2017.1 release did not initialise /engines/active-engine/low-oil-temperature-factor in engine.nas, the release 2018.1 does.
So, it's a glitch.
