### ISSUE TITLE
Request: adjust the sound as you rotate around the aircraft

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p-detailed#1061]
Hi there,
I noticed that the F-15 and F-14 by Richard simulate this. 
He adds orientation tags to the sound file:

![image](https://user-images.githubusercontent.com/10434911/38824958-e1396d18-41a2-11e8-81b2-c6946f912a5f.png)

In light of the sound improvements recently, I think this could be used to further improve the sound.

**Comment by legoboyvdlp** [comment]
Good reference:
https://www.youtube.com/watch?v=3py-LRzVuXA

And potentially a source if you contact the author.

**Comment by onox** [comment]
I'm not sure about this, the F-14/F-15 have jet engines whose sound is very directional. @gilbertohasnofb what do you think?

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp I agree with @onox, I don't think directional sound make sense for our plane. The sound of the engine always comes from a fixed point (the engine itself), and we do have directionality in relation to the viewpoint (e.g. if you look right, you will hear the engine much louder from your right speaker than from your left one). 

About that reference, I think our sounds are better than those, as I used that amazing source you found which was recorded from inside the cockpit. These outside sounds are not really useful. Finally, working with sounds is a bit more complicated than it might first look like, as we have to change its pitch and volume dynamically, as well as fade in and out unwanted sounds. It's not like we can just put a new sound in the sim and it will be great. I am quite happy with my last improvements and at the moment I am not really into re-working anything to do with sounds unless it's a bug fix or a complete new sound that might be missing from some knob/lever/etc.

So for me this issue could be closed.

**Comment by legoboyvdlp** [comment]
Understood. No problem :wink:
