### ISSUE TITLE
Trim wheel rolling too slow

### ISSUE THREAD

**Issue by tonghuix** [c172p-team/c172p-detailed#1072]
The trim wheel rolling is too slow to trim manually. 

I have to take a lot of time to trim the plane. could someone make it faster?

**Comment by tonghuix** [comment]
@dany93 yep very accurate, but I use trim by typing NUM 7 and NUM 1. not using mouse clicking any more. The two keys just like a 'modern' electric trim. 

In another word, the trim control key is slow...

So why you use AP a trim, not manual trim?

**Comment by dany93** [comment]
I understood that you meant with the scroll wheel in the cockpit (I don't use it, not easy to reach).
I use manual trim(s). On my joystick hat.
I think that 1 and 7 on the keyboard are FlightGear coded.

**Comment by tonghuix** [comment]
Yep, you are right, I tested c182s, the trim wheel also rolling very slow. 

I think the slow rolling trim wheel is suit for 737 / A3XX, but not good for c172 / 182, it cost more time to trim the plane.

**Comment by dany93** [comment]
The trim set code by the keyboard is in FlightGear/Data/**keyboard.xml**.
Of course, It is applied for all aircraft.

Search for the expression "elevator-trim".
- keys 49 (NUM 1) and 55 (NUM 7). The step is + / - 0.001.
I just discovered that Ctrl-1 or Ctrl-7 should give a faster change (step + / - 0.05) but for some reason they do not work (for me). 
- Also, keys 362 (Home) and 363 (End) give the same effect (step + / - 0.001).

You can change this values (make a backup copy) but be careful prior to uninstalling FG.

What you can try (not tested):
- use NUM 1 and NUM 7 as usual,
- change Home and End for step +/ - 0.05.

**Comment by gilbertohasnofb** [comment]
@dany93 if you decide this will be a `won't fix` then please add the `won't fix` label and close it. Else add the appropriate labels that you think fit here, perhaps `animation (xml)`
