### ISSUE TITLE
Control lock floating when yoke is hidden

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#1075]
Clicking on the control lock from the pocket on the left side of the pilot's seat when the yoke is hidden causes the lock to be floating in the air. The control lock should be hidden from the pocket when the yoke is hidden and vice-versa.

**Comment by wlbragg** [comment]
@gilbertohasnofb that would be part of the repositioning and something I overlooked. In the future you may want to just drop a note in the "panel to low" thread about any repositioning issues.You can do it this way (as a new issue) as well, but it does fit with the repositioning stuff. Don't fell like you have to create a new issue if it is connected.

**Comment by gilbertohasnofb** [comment]
> In the future you may want to just drop a note in the "panel to low" thread about any repositioning issues.

I normally do that, I just opened a new issue because I thought this was a bug present prior to that work. This is not about the position, this is about the control lock floating though. So unless there were modifications to the control lock logic then this bug was present before.

**Comment by wlbragg** [comment]
Fixed in PR #1066
