### ISSUE TITLE
autopilot buttons are not animated when you click on them

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#1079]
The autopilot buttons are not animated when you click on them. They should quickly be toggled, just like the rest of the radio stack buttons.

**Comment by onox** [comment]
@gilbertohasnofb I've changed the milestone, if it gets closed in time, then the milestone will be changed back.

**Comment by gilbertohasnofb** [comment]
@onox yes, that was my mistake. Thanks for spotting it.

**Comment by wlbragg** [comment]
I went ahead and took care of this. The simplest way to deal with this because of the complexity of the switches was to make each switch a simple two way toggle switch. So every press does exactly what it did before code wise and the animation simply shows the switch click in and click out.
