### ISSUE TITLE
Trim indicator is incorrect

### ISSUE THREAD

**Issue by tonghuix** [c172p-team/c172p-detailed#1087]
When the trim at 0.0 the point to the bottom, and when trim to 1.0, it now point to "take off " position.

Before 0.0 is point at "take off" position. 

![fgfs-screen-524](https://user-images.githubusercontent.com/423703/39736222-a54b1e26-52b1-11e8-914e-24c54df64be0.png)
![fgfs-screen-523](https://user-images.githubusercontent.com/423703/39736223-a580cc38-52b1-11e8-8d6b-a539bee07f51.png)

**Comment by gilbertohasnofb** [comment]
@wlbragg I think we possibly forgot to lift this piece together with the rest of the panel, right?

**Comment by tonghuix** [comment]
I just fix it~

**Comment by wlbragg** [comment]
>we possibly forgot to lift this piece together with the rest of the panel, right?

I saw that when working on it and I wasn't sure that it wasn't correct as is.
I didn't assume that 0.0 was supposed to be point at "take off" position as I didn't do the trim code in the first place. I should have checked that against master to verify. After looking at the setting in fgdata it was 0.0  = point at "take off" so it was wrong. The question is why. I need to verify the movement @tonghuix made and verify the rotation center is correct.
With all the instruments, I moved everything together so this should have moved as well. @tonghuix normally you can't just move the object mesh without also changing the center point in the xml, so I can't see how this is correct even if it looks that way.

**Comment by tonghuix** [comment]
Nope, I checked the commit before 3D model update, the 0.0 always point to "take off". 

After moving the trim indicator up, I noticed all function works very well. If you don't move this up, when trim indicator down (trim tab up, nose up), the indicator will hide very low into the panel.

**Comment by wlbragg** [comment]
I understand, but what you aren't understanding is there is some nuance your missing.
See below, I think that explains it.
![trim](https://user-images.githubusercontent.com/11069680/39772698-87dbd4f2-52bb-11e8-9971-5916f1ee9f49.jpg)

**Comment by wlbragg** [comment]
I am not sure what I did wrong with this, It may have been that I didn't get the ElevatorTrimPosition moved. Even my center point was incorrect. The illustrations above shows the correct process to do this right.

**Comment by wlbragg** [comment]
I made all the adjustment and verified this in the sim. It is now spot on. @tonghuix if you are going to do this work it is important that you understand some of the complexities of working on the mesh. I am willing to point things out as I see them and help you learn and grow in your abilities. One of the fast rules we have for the mesh work is only one PR open at any time for mesh work. It is imperative that we follow this or the blend will quickly get corrupted.
So Please let me open a single PR for multiple mesh issues and I'll do the work.
