### ISSUE TITLE
main wheels struts should be moved downwards

### ISSUE THREAD

**Issue by tonghuix** [c172p-team/c172p-detailed#1089]
I try to lower them, but it cause the wheel sink into earth and wheels rolling axis not changed.

So I think it should be more work to do to fix this major issue.

Ref picture:

![4681705](https://user-images.githubusercontent.com/423703/39759339-063ff848-5305-11e8-9b1e-1d78e5acae61.jpg)

![4763925](https://user-images.githubusercontent.com/423703/39759340-064232e8-5305-11e8-940a-e0b4c997e848.jpg)

**Comment by wlbragg** [comment]
@tonghuix what do you mean by two high? Are the wheels themselves to tall? Is the airframe to far off the ground? You need to be more specific as to what you mean. The two images are not enough data to illustrate the issue.
Moving gear touches many areas of code and in no easy task, It requires a though understanding of the systems it involves and how it is all tied together.

**Comment by tonghuix** [comment]
When I trying remodeling the connection between wheels struts and fuselage, I found these connection located too high. It should down at the corner of fuselage, due to this also cause the whole wheel too high.

I tried, so I do understand it relates many code, and needs much more work to do, so I mark this issue is Major problem...

**Comment by wlbragg** [comment]
@tonghuixa a comparison picture is worth a thousand words. I understand now.
![gear](https://user-images.githubusercontent.com/11069680/39770396-87506770-52b4-11e8-9149-53f086254293.jpg)

We need to discuss this.
What happens to the struts if I simply reattach the top of the struts to the correct location, That is a trick that would require now wheel adjustments whatsoever, only a mesh change. But then do they become to short? Does the fuselage actually need to be raised?

**Comment by wlbragg** [comment]
Comparing the photo with our aircraft it looks like our fuselage needs to be raised. I also noticed the tail is to tall as in thick.

**Comment by gilbertohasnofb** [comment]
Ok, so since we are busy with the interior model at the moment let's leave this opened for the time being, ok? This one will need a lot of testing as it will affect a lot of things.

@tonghuix please do not report things as 'major issues', a neutral report with a picture is a thousand times more useful to us. Thanks!

**Comment by wlbragg** [comment]
I wanted to show you a quick test. this compares the struts as they are now compared to a slight adjustment that really only required some rotation of the top of the gear stuts. What do you all think?
![fgfs-screen-001](https://user-images.githubusercontent.com/11069680/39784013-99e737e2-52dc-11e8-8cb6-6fb894e6835e.png)
![fgfs-screen-002](https://user-images.githubusercontent.com/11069680/39784014-99fe54d6-52dc-11e8-8b87-612e41126c08.png)

**Comment by wlbragg** [comment]
They have actually been moved substantially when looking from this perspective.
![fgfs-screen-003](https://user-images.githubusercontent.com/11069680/39784156-0f410ce8-52dd-11e8-9be0-69ffe4da8310.png)

**Comment by gilbertohasnofb** [comment]
@wlbragg I like how the wheels are looking after the PR #1091 so can we close this issue?

**Comment by wlbragg** [comment]
Close this issue?
I have a finished product with this change should we want to go with it.
![strutmove](https://user-images.githubusercontent.com/11069680/39785098-6d841220-52e0-11e8-8389-edff021ec8a5.jpg)
It would require you moving the texture for the gear strut connection lower to match the new location. You and @tonghuix can decide if you want me to push this last change or not.

**Comment by gilbertohasnofb** [comment]
Sorry I got confused and thought this was also included in the last PR! Yes, I think we should go with it, I can fix all textures. Open a PR and I will push a commit with the fixed fuselage textures for _all_ liveries :crying_cat_face:

**Comment by gilbertohasnofb** [comment]
Closed via https://github.com/c172p-team/c172p-detailed/pull/1092
