### ISSUE TITLE
Organize the blender file

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#16]
3D14 - Organize the blender file. It was ok, in the first time I imported. Until I realize the livery problem pointed by ludomotico. Then I just reimported the original model and was muuuuuch more lazy than the first time.

**Comment by gilbertohasnofb** [comment]
Has this been done?

**Comment by onox** [comment]
If the number of objects in the .blend file corresponds with the number of drawables, then perhaps we should organize all the objects into two groups:

1. `animation`

2. `static`

Objects under `animation` are used in animations (in `Models/c172p.xml`). All the objects under `static` are not used in animations. These objects can then be joined to become 1 object and then exported to the .ac file. (Don't save the .blend file after joining). The .ac file will then have 1 static objects + *n* animation objects.

See http://forum.flightgear.org/viewtopic.php?f=5&t=28476

**Comment by oMarcosLucas** [comment]
Almost everything in the model either moves or changes texture.

**Comment by wlbragg** [comment]
>(Don't save the .blend file after joining).

BUMP

**Comment by wlbragg** [comment]
Are we really going to gain anything by attempting to do this? If there is a way to measure the performance difference then I would consider going through it and trying to reduce the object count, but without seeing some kind of measurement or proof of gain, I'm not sure it's worth it.

**Comment by onox** [comment]
I think it depends on how OSG renders all the objects. If it uses OpenGL multi draw to reduce the number of draw calls and draw objects in the order of texture usage to avoid unnecessary texture binding, then you won't see reduced CPU usage. But I'm not sure OSG is smart enough to do that.

If we clearly know which objects are dynamic (require animations) and which objects don't, then I don't think there is any harm in grouping them under `animation` and `static` (or make multiple static groups, one for each texture). In that case if you decide not to join objects, they just sit in a group. Then we have just reorganized the objects. Nothing more, nothing less.

If you click on Debug > Cycle On-Screen Statistics you should be able to see the number of draw calls and triangles it draws.

**Comment by wlbragg** [comment]
Another potential issue, when moving things around in the blend (putting objects in and out of groups) Bender can decide to flat out "bug out" and loose UV texture path info. Also, there is coordinate space relations that can be screwed up when doing the same, if not careful. So this needs to be done by someone that knows what they are doing, I'm not sure that is me. But I'm willing to take a closer look.

**Comment by onox** [comment]
> But I'm willing to take a closer look.

You could try to join all the static objects (that share the same texture) together and just test whether you get better performance, even if the UV mapping becomes bad. It would be interesting to see if joining all these static objects gives a lower CPU usage and/or higher fps. I suspect just lower CPU usage.

Don't spend too much time on this though.

**Comment by onox** [comment]
Just don't commit anything if the UV becomes bad :stuck_out_tongue_winking_eye:

**Comment by wlbragg** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
@wlbragg can we close this or is this still relevant?

**Comment by wlbragg** [comment]
@gilbertohasnofb 
I think we can close this.

**Comment by onox** [comment]
This is a "won't fix"?
