### ISSUE TITLE
Clicking "Repair" button doesn't set craft to upright position

### ISSUE THREAD

**Issue by wkitty42** [c172p-team/c172p-detailed#308]
Now that we have the "Repair" button in the "Aircraft Options" window, I find myself using it more and more to try to correct things from accidents but some things it just doesn't do and that means that one has to exit or reset the sim.
1. Craft is upside down
2. Fix all instruments that may be broken (had the horizon get broken the other day after a nasty)

Those two are all I can think of at the moment... I'm sure there may be others, too.

**Comment by wlbragg** [comment]
Yes, that one bugs me to. I'll see if there is a way to do that.

**Comment by wkitty42** [comment]
ahhh... i hadn't forgotten about this one but did think it was already closed... plus i wasn't able to find it, either... i hope that others can still get and use the flight tape i linked to in #497  :wink:

**Comment by wkitty42** [comment]
geez, i reported this one, too :smiley_cat: 
hard to believe that we've had this bug for almost 3 years :crying_cat_face:

**Comment by wkitty42** [comment]
i thought CTRL-U just flung you up higher than you currently are by 1000 feet each time you hit it... i would expect that an upside down crashed craft would remain upside down and that you might possibly be able to flip it back over by maybe diving and recovering that way... that's not something that many new users can do... i keep trying to just let go of everything and hope the craft will right itself like some easy flying ones are known to do but this craft doesn't do that AFAIK...

**Comment by wkitty42** [comment]
i've asked on the dev list about this... the first response, from jsb, suggests to set roll and pitch to zero... do you think that will do it? i've still more messages to read over there so there may be more answers... if so, i'll comment them here...

**Comment by wlbragg** [comment]
@wkitty42 

FYI, it appears to be as easy as roll and pitch to 0. I tested it and I think that is pretty much all it will take. Although we are going to have to have a check to not do this if it's not needed.

**Comment by tonghuix** [comment]
Have you try MIG-15, it has a Full Reset button at the menu, and set everything back in 1 second!

**Comment by gilbertohasnofb** [comment]
> FYI, it appears to be as easy as roll and pitch to 0. I tested it and I think that is pretty much all it will take. Although we are going to have to have a check to not do this if it's not needed.

Possibly just check if the either the roll or pitch is above 90 degrees. If so, then the aircraft is certainly flipped. Anything less than that and it should be a slope.

**Comment by wkitty42** [comment]
i understand what you're saying about being on a slope, @gilbertohasnofb ... the problem is when you're flipped over but leaning against crates or a tree or another craft... i haven't looked at the numbers to see what they are when one ends up in this condition, though... i guess i/we need to find them and run some tests... there's so many properties in the sim, i'm not sure even where to start looking for these particular ones for the craft...

**Comment by gilbertohasnofb** [comment]
@wkitty42 I haven't tested in the sim either, but I assume that roll go from -180 degrees to 180 degrees and the same for pitch, in which case it should be trivial to detect if the plane is upside down.

**Comment by wkitty42** [comment]
ok... i'm concerned that we may be canted at an angle and not completely upside down... possibly we flipped and flopped and bounced around (you know how crazy the sim can get with bounces) and we may end up against another object upright but with the wing or nose or tail on the object and the other end on the ground... mostly i find myself upside down but those static crates at that one airport have had me looking at the sky with the tail on the ground and on of the wings on the ground while the nose and other wing were propped up on the crates...

speaking of these crackups, i'm glad we don't have to clean up a bunch of glass from the windows breaking :laughing:

**Comment by dany93** [comment]
> it should be trivial to detect if the plane is upside down

Anyway, if an angle is not inside about +/- 45 deg after "Repair", we can assume that the aircraft is not in a comfortable situation.  :grimacing:

**Comment by wkitty42** [comment]
that's an idea, @dany93 ... check the angle after the repair and then flip if needed... i thikn i'd go for something a bit less than 45 degrees, though... it isn't very often that you'll find your craft on a slope that's larger than maybe 15 degrees... possibly 20 but that's going to be a sticky airport anyway :)
