### ISSUE TITLE
Improve the broken wing model

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#319]
@wlbragg what do you think if we improve the broken wing model by showing the wing structure through the broken point? I am talking about these green metal structures: http://www.mikejamesmedia.com/modo_media/modo_wip/cessna_310k/cessna_310k_138_ribs.jpg

Here you can see how they look in the 172: http://4.bp.blogspot.com/-FbGczdVEcts/UQaMdCgj4cI/AAAAAAAAAAs/IquO8W5p6xc/s1600/Cessna+172++glass+cockpit+%287%29.jpg

If you like the idea, I can create a texture for that. If not, feel free to close this issue.

**Comment by wlbragg** [comment]
Yes, you want to just add the texture to part of the end of the wing?
Great idea, I don't like the symmetry of the existing damage.
I pinched the ends of the broke off wing, do they need to be opened back up?

**Comment by gilbertohasnofb** [comment]
> Yes, you want to just add the texture to part of the end of the wing?

Yep, we can create a simple 2D object where the wing is broken (similar to the seat mounts for instance).

> I pinched the ends of the broke off wing, do they need to be opened back up?

Aren't the wings losing their tips completely when they break? Because if they do, we should be able to see something like that: https://c1.staticflickr.com/5/4068/4431293697_5d2de5f2ce_b.jpg

Tell me what you think so I can work on it.

**Comment by wlbragg** [comment]
>we should be able to see something like

Right, but I pinched that broken gap off, so you probably want the space back?

**Comment by gilbertohasnofb** [comment]
> so you probably want the space back?

Well, I don't particularly want anything unless you agree with me that this would be an improvement to your damaged model :smile: My proposal comes from the idea that when a wing breaks, it would normally break in between those structural points and that normally we would be able to see these structures, but I guess it's also possible to brake a wing in a way they don't show. So in the end it's just a decision of how we want it to look, if we keep it as it is or try to show a bit those green metallic structures like this: http://www.rafmuseum.org.uk/images/blog/Cosford/rootendwingkynnspitfire.jpg

**Comment by wlbragg** [comment]
>I don't particularly want anything unless you agree with me

gilbertohasnofb, when I say "you want", especially in this context, it is just a figure of speech meaning I am looking for your definition of what it is your suggesting and how you might anticipate it will look.
I absolutely agree with where your going with this idea, I just need to know if you think we should open that space back up, for technical reasons? Is it easier to texture the end it it is a bigger flat surface or does it even matter, technically speaking?
I think it would look better if you could see some kind of ribbing.
If you agree then I will open the ends up a little bit and then you can do the texture, agreed?

**Comment by wlbragg** [comment]
Here is an example of what I am talking about with the wing. If you have blender and can get around in it, look at the ends of wing_1BB, compare the two ends and you will see one is pinched together (left), the other is opened up about the same normal width of the wing (right).
https://copy.com/sYJeLFJBzmkJgqBC
Does this need to be one way or the other? If you want to use this Blend file for a test, go ahead and then we can do a final on the original damage.blend file after we decide if the original damage file needs the ends opened up.

**Comment by thevirtualfer** [comment]
Hi guys.

Unfortunately, my ISP told me that the problem with my connection will be
solved only on August/12


cheers.

2015-06-21 1:28 GMT-03:00 wlbragg <notifications@github.com>:

**Comment by onox** [comment]
@thevirtualfer Do you happen to live in the US where you can choose from as many ISP's as long as it's the only ISP you can choose from? :open_mouth: I would switch ISP if they can't fix your connection within 1 or 2 weeks.

**Comment by gilbertohasnofb** [comment]
@onox I believe thevirtualfer lives in Brazil, and depending on where you live these problems can be quite annoying.

@wlbragg in order to show that structure, the wings would need to be opened indeed. I have seen pictures of planes with broken wings which are pinched but also which are opened (and thus the internal structures can be seen), so that's why I said that either way is fine with me. Personally the first option (open hole showing the inner structure) sounds better looking to me, but now we are discussing aesthetics of a broken wing :wink: So what do you think, which option would you prefer?

**Comment by tigert** [comment]
often the wing just crumbles too. I guess if it is overstress in the air it likely gets torn off, but on crashed aircraft often the skin stays on and just crumbles at the impact point, much like the bending damage we have (had before?)

Doing custom damage model for each kind of overstress and impact might be a bit overkill though. :)

**Comment by gilbertohasnofb** [comment]
> Doing custom damage model for each kind of overstress and impact might be a bit overkill though. :)

Oh sure, I never meant that! I just meant that we should choose a single damaged model, and I proposed to _maybe_ change ours as to show the inner structure. But I am also fine leaving it as it is since our damaged model is quite good :)

**Comment by dany93** [comment]
I'm afraid you are making this aircraft heavy (in Mo) for secondary features. In the end, bad for the fps... And impossible for those who do not have a very recent computer.

**Comment by gilbertohasnofb** [comment]
@dany93 Well Dany, I was thinking about adding a single 2D object of the wing structure, and the texture could well be inside one of the already existent png files, so I hardly think this would make the aircraft any heavier on the CPU. But I kind of see your point, although we surely have different views on this. As much as I agree that the model shouldn't be an overkill of thousands of unnecessary polygons or overly detailed minor parts (door handles, seats, etc.), I also care for the aesthetics of the model very much (after well, my main work here is to deal with textures). If we would only think about fps on low end computers, we probably would have only improved systems and FDM while the whole model would have stayed as the previous default plane, which looked horrible in my opinion (but gave great fps even in old humble machines).

**Comment by wlbragg** [comment]
@dany93, thank you for keeping us grounded.
As gilbertohasnofb said, we are only talking about a single 2D object of the wing structure, and the texture could well be inside one of the already existent png files.
I think gilbertohasnofb was correct in suggesting we look at the possibility of doing this minor texture upgrade to the existing damage model. I was never happy with my final version being so symmetrical looking and clean at the breaks and bends in the wings. I always had in the back of my mind the thought of coming back to this at some point in time and making it look a little more "realistic". I didn't know how I was going to go about that and all along thought I would have to redo the models. But gilbertohasnofb suggestion of just modifying a simple texture would make all the difference in the world as to the look of the damage at little or no cost in performance. His idea answered my original concerns without him even knowing I had them.
So I am all for a little texture work on the damage.
All the talk of opening the wings up was just my ignorance of not knowing what he needs technically to place a texture at the end of the broken wing. I don't think we are talking about adding any new model parts at all, just potentially closing the ends of the broken wing tips where I pinched it together when I broke it and the reason I did that back then was not for any other reason than i didn't know what to do at the end so i just pinched them almost closed.

**Comment by gilbertohasnofb** [comment]
Cool @wlbragg, I am already working on this. And by the way, is this a "new feature" or a "bug fix"? We are basically improving a feature we already have, so I guess it could be fine to have a 3.6 release milestone. What do you think? Any ideas, @onox ?

**Comment by gilbertohasnofb** [comment]
@wlbragg Done, see the file Models/wing.png on master. I didn't add these structures to every livery's wing.png as we don't need to make it livery-dependent. Let me know what you think.

**Comment by onox** [comment]
> We are basically improving a feature we already have, so I guess it could be fine to have a 3.6 release milestone.

If you look at that way you can consider the 3.6 release milestone :smile:

**Comment by gilbertohasnofb** [comment]
@onox thanks :smile:

**Comment by onox** [comment]
Is that commit you added to master the only thing we can expect or does this issue need more commits?

**Comment by gilbertohasnofb** [comment]
From my part that was the only commit (unless wlbragg wants me to improve something on that texture). But now wlbragg will have to create the 2D object and apply the texture in his damaged model, so I guess we should wait for that before closing this.

**Comment by onox** [comment]
Feature branches :sob: :sob: :sob:

**Comment by gilbertohasnofb** [comment]
I don't understand, sorry...

**Comment by onox** [comment]
Never mind @gilbertohasnofb :stuck_out_tongue_winking_eye:

**Comment by gilbertohasnofb** [comment]
No, please tell me so I don't do the same thing next time. You mean that since this is not only a texture fix but also will include some other modifications I should have created a branch for it?

**Comment by onox** [comment]
That would have been nicer, yes.

**Comment by onox** [comment]
Shall I force push again to pretend it didn't happen? :stuck_out_tongue_closed_eyes:

**Comment by gilbertohasnofb** [comment]
> Shall I force push again to pretend it didn't happen? :stuck_out_tongue_closed_eyes:

Is that really necessary? These force pushes have been breaking my repository all the time, and this is just a texture modification. What about this: I will create a new branch now in which wlbragg will do his work. If any modifications to this texture is needed, I will also do it in that branch. Then we merge back with the master once the work is done.

Also, next time I am adding something (texture, sound) which is not a simple substitution but needs some more work (some programming, adjusting model, etc.) I will **always** create a new branch. Is that all right?

Sorry for making a mess :cry:

**Comment by onox** [comment]
I think we can better do it now. I'm here for assistance anyway.

Can you backup that texture file you added?

**Comment by onox** [comment]
> I will always create a new branch. Is that all right?

Yes! :smile:

**Comment by gilbertohasnofb** [comment]
Ok, then go for it! And yep, I always do my work on a different folder so I always have a copy of it. Just reset the master and I will create a new branch!

**Comment by onox** [comment]
Okay. Do this:

1. `git reset --hard 636767ac4dd90e5d173846c60b7dfcb31f86ebd1`

2. `git pull`

**Comment by gilbertohasnofb** [comment]
Done. So just to confirm, now I do a `git checkout -b bug-319`, then add my stuff and commit it, then I do a `git push -u` right?

**Comment by onox** [comment]
Yes.

**Comment by gilbertohasnofb** [comment]
Sorry onox but it didn't work. After I did `git push -u`, I got:

    Branch master set up to track remote branch master from origin.
    Everything up-to-date

And I can't see the new branch nor the modifications here on GitHub...

**Comment by onox** [comment]
Btw, sorry that I'm so persistent on it, but if you always do your stuff in a feature/topic branch, then your work can be reviewed and tested, and when it's ready it can be merged to master. If instead you just simply commit directly to master, then no one can review and test your changes. If you accidentally break something, you break it for everyone.

If you're the only person working on a repository, then committing directly to master is OK, but if you're working in a team (as we are), you should really try to use these feature/topic branches. So I hope you understand it a bit :smiley:

**Comment by onox** [comment]
What does `git branch` say?

**Comment by gilbertohasnofb** [comment]
That I am at `bug-319` branch. Locally everything is fine, the problem was with the push I believe.

**Comment by onox** [comment]
`git push -u origin bug-319`

**Comment by onox** [comment]
Did you add a commit to bug-319 branch?

**Comment by gilbertohasnofb** [comment]
`git push -u origin bug-319` did the trick, thanks! So I guess the problem was that I was using only `git push -u`. Thanks again, onox...

**Comment by onox** [comment]
I got it:

```
From https://github.com/Juanvvc/c172p-detailed
 * [new branch]      bug-319    -> origin/bug-319
Already up-to-date.
```

**Comment by gilbertohasnofb** [comment]
Okay, so let me repeat this so it doesn't get lost:

@wlbragg Done, see the file Models/wing.png on the branch `bug-319`. I didn't add these structures to every livery's wing.png as we don't need to make it livery-dependent. Let me know what you think.

**Comment by wlbragg** [comment]
OK, I'm a little behind, give me a bit (later today) and I'll take a look, thanks!

**Comment by gilbertohasnofb** [comment]
No rush at all, take your time and let me know if you need anything to make it work. Thanks!

**Comment by gilbertohasnofb** [comment]
@wlbragg related in a certain way: https://github.com/Juanvvc/c172p-detailed/issues/329

**Comment by wlbragg** [comment]
gilbertohasnofb, I have both ends of the "both wings broken" model closed off and uv mapped with your new texture. For some currently unknown reason, it is not carrying over to the model in FG (I am completely new to mapping textures to models in Blender). So I preparing to post a forum request for help here shortly. I can't wait to see it in the sim.
I was under the impression that we were going to add some "damage" texture to the top and bottom of the damaged wings also, like ripped away skin maybe. Do you think this is feasible or reasonable. Are there costs to using a different texture on the damaged model than the one used on the undamaged model?

**Comment by gilbertohasnofb** [comment]
Oh, that is really not my area of expertise either! I have so far only created textures, and then either @Juanvvc, @thevirtualfer or @dg-505 would apply them in the model. So it's better to ask them what's the best route to take.

**Comment by wlbragg** [comment]
>So it's better to ask them what's the best route to take.

OK, the question still stands for @Juanvvc, @thevirtualfer or @dg-505.

What cost are associated to having a totally different texture set for damaged models?

**Comment by wlbragg** [comment]
As much as I want to do this it is a little over my head. Texturing in Blender is an art and requires great skill and stamina for anything detailed. I just don't have the experience (or stamina) to do this.
I spent some more time on this using a different approach and realized I don't know enough to pull this off. As a matter of fact, along with this issue we really need a modeling expert to come in an repair some of the existing UV maps in the various blends.

**Comment by gilbertohasnofb** [comment]
@wlbragg there is no problem, this would be implemented only for FG 3.8 so we have plenty of time. Let's focus now in solving the issues for the 3.6 release and then we tackle this once again, and maybe some of the 3D modellers would help us as well.

**Comment by thevirtualfer** [comment]
Let me understand. I have not yet downloaded the flightgear, nor the repo content.

There is a blend file to the damaged plane ?

**Comment by onox** [comment]
If you haven't downloaded the repository yet, then which file were you using to show those pictures in the forums? :open_mouth: 

The repository contains the following `.blend` files:

```
./dev/fdm/gerris/floats.blend
./Models/c172p-shadowpontoon.blend
./Models/c172p-shadowbushdef.blend
./Models/c172p-shadowbush26.blend
./Models/c172p-pontoon-damage.blend
./Models/c172p-bushkit.blend
./Models/Interior/Panel/Buttons/breakers/breakers.blend
./Models/Interior/Panel/Instruments/hi/hi.blend
./Models/Interior/Panel/Instruments/oat/oat.blend
./Models/Interior/Panel/Instruments/hobbs/hobbs.blend
./Models/Interior/Panel/Instruments/light/light.blend
./Models/Interior/Panel/Instruments/AI/AI.blend
./Models/Interior/Panel/Instruments/tc/tc.blend
./Models/Interior/Yoke/yoke.blend
./Models/c172p.blend
./Models/c172p-damage.blend
./Models/c172p-shadow.blend
./Models/c172p-pontoon.blend
./Models/c172p-shadowbush36.blend
```

**Comment by thevirtualfer** [comment]
Wow !

I got the repo address you give me, and dowloaded only the c172p.blend.

And don't noted these other files.

I downloaded the repo today. And the fgdata + flighgear + simgear

Compiled ok. But only UFO is working.

It hangs with : 

FATAL:'-' found in propertyname after ''
name must begin with alpha or '_'

Will see it later. But my default pessimism is tilting.

**Comment by onox** [comment]
> And don't noted these other files.

What do you mean? Are you saying that the other `.blend` files (that I mentioned) do not exist? They [do](https://github.com/Juanvvc/c172p-detailed/tree/master/Models).

**Comment by thevirtualfer** [comment]
HAHAHAHHA !

Of course they do !

But i didn't see then, when i downloaded the c172p.blend

Like when we will see a girl, and don't see the others person in the same place.

But i cloned the repo today. A lot of fun to me.

Hey @onox !

What version are you running ?

I just can't understand that error about propertyname. I downloaded the 3.7.

**Comment by onox** [comment]
I'm using flightgear/simgear/fgdata git (that's 3.7 currently). Also be aware that fgdata git contains a snapshot of our c172p in its `Aircraft/` folder. (Because it's the default aircraft) So you have to use --fg-aircraft to point to your Juanvvc/c172p-detailed folder. If you want to be absolutely sure that FG is reading the git version of c172p (Juanvvc/c172p-detailed) and not the snapshot from fgdata, you should nuke/rename/delete that snapshot.

**Comment by thevirtualfer** [comment]
Thanks, @onox.

Didn't work here. Will investigate later.

2015-08-28 13:04 GMT-03:00 onox <notifications@github.com>:

**Comment by onox** [comment]
Or try to rename your `.fgfs` to `.fgfs-backup` and see if that works.

**Comment by gilbertohasnofb** [comment]
As of 19 February 2018, we have a new and considerably different wing 3D model, so the broken wing model should be updated to match it.

**Comment by wlbragg** [comment]
Duplicate wing objects #592 is a part of this.

**Comment by gilbertohasnofb** [comment]
Small note for when this gets tackled: the new fuel sumps are not touching the bottom part of the broken wing model. They need to be translated upwards by a small amount.

**Comment by wlbragg** [comment]
@gilbertohasnofb 
I seem to have misplaced your texture for the wing ribbing for the end of the broken wing model. Any chance I can get you to add it to the wing.png "default" texture? Somewhere over on the right I suppose would be the best location. I also vaguely remember it having a green color I didn't think looked right, but I don't completely remember. Maybe it was supposed to be that color and I was expecting something more like aluminum color.

**Comment by wlbragg** [comment]
Please make it as close to this outline as possible, obviously only on the default texture.

![tex](https://user-images.githubusercontent.com/11069680/37841630-23785db0-2e8e-11e8-804d-ddd9afd501b1.jpg)

**Comment by gilbertohasnofb** [comment]
@wlbragg Ok! But would you be able to send me a 1024 x 1024 or 2048 x 2048 image with the UV-mapping position such as above? Because if the resolution matches what we use for the textures, I can superimpose it while creating a new texture and then the placement will already be perfect.

**Comment by wlbragg** [comment]
@gilbertohasnofb can you just scale that, crop the black border and it should scale to either.That is what I would have do and will if you still need me to.

**Comment by wlbragg** [comment]
If you try that and it doesn't work then I can try something else.

**Comment by gilbertohasnofb** [comment]
Sure, I can do that, it's just that if you send me in native resolution then it's easier to be precise very precise. I think Blender exports that automatically, since that's how paintkits are created. But no problems, I can just scale it myself.

**Comment by wlbragg** [comment]
I can try that I just don't know if it will export the mapping!. I was going to try that anyway, let me see if it does.

**Comment by gilbertohasnofb** [comment]
When I did the textures for the c182s, Heiko gave me a bunch of png files looking like this:

![](https://raw.githubusercontent.com/HHS81/c182s/40b92cdcf2b5749614913e5119b2e4f2e7537722/Models/PanelTexturing-MainPanel.png)

**Comment by gilbertohasnofb** [comment]
or ![](https://raw.githubusercontent.com/HHS81/c182s/40b92cdcf2b5749614913e5119b2e4f2e7537722/Models/PanelTexturing-Controls.png)

**Comment by wlbragg** [comment]
I could be wrong but that looks like Sketchup.

It's not saving the uv-mapping and I don't know how. I can't even get it to show both mappings at the same time and I used to know how to do that. What I gave you was a Gimp with two layers super imposed. It doesn't have to be perfect I can easily resize, we just need the proportions to be consistent so the round holes remain round.

**Comment by gilbertohasnofb** [comment]
Yeah, no worries then, I just thought it was something Blender did automatically. Let's now waste time with this, I can easily scale and match the image you posted above.

**Comment by wlbragg** [comment]
@gilbertohasnofb the easiest thing to do was to use the fast prop object from the c182s and map it to the new texture you provided using our material settings. I was worried that using the texture from the c182s would darken up our prop too much. By using our material settings I think it worked out really well. I like it.
One thing I didn't test for was the red or yellow coloring as I don't think I am seeing the same thing as you are. So please test and let me know where were at with this.

**Comment by gilbertohasnofb** [comment]
@wlbragg First, sorry for my super slow replies, I have been ultra busy these last days.

As for the prop disk, it looks really good. Did you make them livery dependant? This way I can tweak them for each different front prop. 

> One thing I didn't test for was the red or yellow coloring as I don't think I am seeing the same thing as you are. So please test and let me know where were at with this.

I removed the white and red part of the disk in the texture I pushed to this branch since our default 4X-CHV has a fully black propeller. For other liveries, I will create a different disk for each one.

**Comment by gilbertohasnofb** [comment]
@wlbragg Take a look at this picture, it's the only good one I found of a 172 with a broken wing. The interior of the wing is simply some grey metal, so the textures I will push will be super simple metallic ones.

![](https://media2.fdncms.com/boiseweekly/imager/cessna-172-crashed-approximately-one-mile-southeast-of-silver-city/u/original/2658552/1338214655-cessna.jpg)

**Comment by gilbertohasnofb** [comment]
done and pushed

**Comment by wlbragg** [comment]
@gilbertohasnofb 

As far as livery dependent is concerned for the Propeller.Fast object. We have to set up a new livery logic for that texture. I have no problem doing that but it would be helpful to have at least one of the alternate livery prop textures for testing purposes.

**Comment by wlbragg** [comment]
Also the rib texture is on a livery dependent texture so it unfortunately needs to run through the liveries. In order to remove it from the liveries I would have to make it a different object than the damaged (broken saw edged) object and that would require having another object to manipulate in the damage code and also require you to move the texture to a different texture sheet that is not livery dependent.

**Comment by wlbragg** [comment]
>it would be helpful to have at least one of the alternate livery prop textures for testing purposes.

Not true, it's now set up and shouldn't be a problem to add a livery dependent fastprop when needed.

**Comment by gilbertohasnofb** [comment]
> Also the rib texture is on a livery dependent texture so it unfortunately needs to run through the liveries. 

no problems, I will do that. Give me a sec.

> Not true, it's now set up and shouldn't be a problem to add a livery dependent fastprop when needed.

I am already pushing a testing one for you!

**Comment by wlbragg** [comment]
I'm ready to push all my corrections, let me know when your done so I can pull your final stuff. I think I am all done except the new OH-CTL prop livery which I am adding now and will be included when I push.

**Comment by wlbragg** [comment]
Nice, OH-CTL works fine, looks good.

**Comment by gilbertohasnofb** [comment]
Done. I pushed the broken wing texture to all wing textures, see my comments in the PR. Also, please take a look at my comment https://github.com/c172p-team/c172p-detailed/pull/1019#issuecomment-375905883

**Comment by wlbragg** [comment]
>Also, please take a look at my comment #1019 (comment)

That's included in the last push.

**Comment by wlbragg** [comment]
OK, I decided to get fancy and add the holes to the ribbing itself. This is really cool. I hope we don't cause people to want to crackup just to see the model! :smile: 
![rib1](https://user-images.githubusercontent.com/11069680/37868638-f45942a2-2f77-11e8-8791-0eef58732d87.jpg)
![rib2](https://user-images.githubusercontent.com/11069680/37868639-f6537f14-2f77-11e8-882a-de1bc7e97b6c.jpg)
![rib3](https://user-images.githubusercontent.com/11069680/37868641-f7d21f44-2f77-11e8-94e8-400ef106ffc6.jpg)

**Comment by onox** [comment]
Looks better! :smile:

**Comment by gilbertohasnofb** [comment]
Looks amazing!!

**Comment by wkitty42** [comment]
i don't remember but do we also damage the wing if we have, say, a wing strike on take off? like i've done many many times before i figured out my fast method of getting the AP turned on to go wings level and maintain my climb against the p-factor and side winds :smile_cat: 

it'd probably be too complicated to have another set of wing halves or to have another part of the wings for, say, the outer foot of the wing with the lights on it...

i've also wondered about damage to the tail if we land too hard and break the landing gear... i do like what we've done to the craft since the beginning of the project and these additions are also adding a lot more to the craft and its realism factor :+1:

**Comment by wlbragg** [comment]
>do we also damage the wing if we have, say, a wing strike on take off? 

Yes, same damage can occur if you strike the wing on the ground as the force damage.

I thought about possibly adding some tail damage. I have not seen any images though of tail strike damage. I also don't know how common of an event that might be, not that any of this is.

**Comment by tigert** [comment]
On tail strike there is the tiedown hook that gets scraped, and on a harder strike it might break off, causing scraping to the underside of the fuselage under the tail and maybe rudder. If the hook is there it protects the fuselage from scrape marks.

**Comment by tigert** [comment]
well, it's a metal loop, nit exactly a "hook" but you know what I mean :)

**Comment by wlbragg** [comment]
OK, yeah we actually have the loop and we also simulate the tail scrap. Although we need to make a better particle effect for it.

**Comment by gilbertohasnofb** [comment]
I noticed we have a branch called `bug-319`. Does anyone know what that's about? This issue has been solved. Can we delete that branch or does it contain any important work?
