### ISSUE TITLE
Better UV mapping

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#430]
The fuselage could have some improved UV mapping in several places:

* * *

1) Tail needs better UV mapping, particularly between the rudder and the tail itself. This is very evident with the OH-CTL livery:

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/8765870/cf57bf6e-2e22-11e5-9e1d-0d605932d76b.png)

![fgfs-screen-002](https://cloud.githubusercontent.com/assets/5700795/8765871/d187fd1c-2e22-11e5-9828-dc3da50087aa.png)

In the first picture above, note how the yellow stripe does not match between the rudder and the tail. In the second pitcure, note how there is a number missing in the yellow stripe (it was supposed to be written 15000 instead of 1500) and how the blue airplane logo has a mismatching left wing tip (the blue bit)

* * *

2) The back of the fuselage doesn't look good on the right side of the plane. This is quite evident with the livery N35799. See:

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/8766023/02eeacb0-2e29-11e5-8896-b021f3558e63.png)

The other side isn't perfect but is much more acceptable:

![fgfs-screen-002](https://cloud.githubusercontent.com/assets/5700795/8766025/0dd30d4c-2e29-11e5-93da-f63fbf7564e5.png)

* * *

3) The nose is also quite problematic, see:

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/20443278/844aabb4-adcc-11e6-81d7-e881208ea085.png)

**Comment by gilbertohasnofb** [comment]
The post above has been edited, as there are 3 problematic areas all of which involve the UV mapping of the fuselage. 

For whomever plans to fix this: please be careful not to think that the issue is fixed by testing a single livery. The tail and nose issues are more evident with the OH-CTL while the bottom back is more clearly seen with the N35799, but after a fix please do take a quick look on the other liveries to confirm nothing went too much out of place.

**Comment by wlbragg** [comment]
These issues are being taken care of in PR #964 
![fgfs-screen-015](https://user-images.githubusercontent.com/11069680/36211600-4f671dec-1167-11e8-93d2-9c7740093d17.png)
![fgfs-screen-016](https://user-images.githubusercontent.com/11069680/36211604-505a0c96-1167-11e8-8016-c89d70c4f237.png)

**Comment by wlbragg** [comment]
That is about as good as I can get it. Please check other liveries to make sure it didn't effect them.
![fgfs-screen-017](https://user-images.githubusercontent.com/11069680/36213474-72177292-116c-11e8-9061-2606377a9fbd.png)
![fgfs-screen-018](https://user-images.githubusercontent.com/11069680/36213477-733a2714-116c-11e8-80ed-6867ce05a3ec.png)

**Comment by legoboyvdlp** [comment]
:)
As always, great job.

(by the way, on another note is that volumetric grass, the sort you enable by uncommenting something?)

**Comment by wlbragg** [comment]
Thanks!
One is volumetric grass and the other is the fur shader. There is two separate effects.
The volumetric grass, yes there is some code in the materials I think you uncomment.
https://forum.flightgear.org/viewtopic.php?f=6&t=23666
https://forum.flightgear.org/viewtopic.php?f=47&t=32183
