### ISSUE TITLE
Texture or normal issue with the pontoons

### ISSUE THREAD

**Issue by wlbragg** [c172p-team/c172p-detailed#507]
I noticed this issue with the pontoons while flying in Alaska.
![texture1](https://cloud.githubusercontent.com/assets/11069680/10950481/7b8abed8-82fd-11e5-8c6e-9f80bb7e3fbc.jpg)

**Comment by gilbertohasnofb** [comment]
Does this appear all the time for you or was it just in that particular flight (under specific light conditions)? The textures are symmetrical, so unless they were wrongly applied they should be identical (and I thought they were). Also, I don't even know where is the normal map for the floats. I will make a test and see how they show on my computer, ok?

**Comment by wlbragg** [comment]
I think it is only on the floats and not on the amphibious.

**Comment by wlbragg** [comment]
I found the problem, it's because of the bumbspec effect being applied to the pontoons, I'm not sure it should be.

**Comment by gilbertohasnofb** [comment]
Can't you just copy the effect from the amphibious to the pontoons to solve this?

**Comment by wlbragg** [comment]
I was just looking at that and they are both using the same thing I think? All there is is pontoon.xml
I am looking at the blend.

**Comment by wlbragg** [comment]
I know I should know this seems how I did it, but where did we get the texture for the pontoons?

**Comment by wlbragg** [comment]
It's a problem in the blend, I'll fix it.

**Comment by gilbertohasnofb** [comment]
`/Models/floats.png`, and they are livery dependent.

**Comment by wlbragg** [comment]
I mean originally, where did they come from, who made them, what aircraft?

**Comment by gilbertohasnofb** [comment]
Hmm, I don't know, maybe from the beaver? The default one is almost untouched except for some additional textures I added in blank spaces, but the ones for the HD liveries are heavily modified by me.

**Comment by gilbertohasnofb** [comment]
@wlbragg Has this issue been fixed in one of those PRs mentioned above?

**Comment by wlbragg** [comment]
No this has not been fixed.
Now that I have a little more experience with Blender, I'll take another look at it and see if I can figure out what is wrong with it.

**Comment by gilbertohasnofb** [comment]
Thanks!
