### ISSUE TITLE
Problems in the pre-flight tutorial

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#587]
I tested the pre-flight tutorial and found the following problems:
- ~~the tutorial starts with instrument lightning at 100% during day!~~
- ~~close door pink circle in the wrong place (immediately after leaving the cockpit after checking the fuel level)~~
- ~~funny cameras, sometimes they rotate in an anti-intuitive manner (like rotating 300 degrees instead of 60, thus looking away from the plane for some moments)~~
- We now have static objects, including ladders, which can be activated in the Ground Equipment dialog. This ladder can be climber by the walker, making it easier to click on the fuel tank caps to add/remove fuel. This could be added to the pre-flight check tutorial.
- add control surface checks to the tutorial

@dg-505 do you think you can have a look at them?

**Comment by gilbertohasnofb** [comment]
Otherwise, great job! It is really immersive :smile:

**Comment by dg-505** [comment]
> funny cameras, sometimes they rotate in an anti-intuitive manner (like rotating 300 degrees instead of 60, thus looking away from the plane for some moments)

In the definition of the cockpit view, there are limits present. Because of this the view can't move more than +-140 degree. If the tutorial changes the view heading from, let's say 140 deg to 220 deg, the view cannot turn the direct way, but it turns the other way round. Until now I fund no way to obviate this problem, even if I comment out all limit definitions...



>close door pink circle in the wrong place (immediately after leaving the cockpit after checking the fuel level)

![door](https://cloud.githubusercontent.com/assets/12293276/11459670/2dd8f40a-96dc-11e5-98ce-cca415955a29.JPG)
You mean this? I had no better idea where to put the marker for "Close the door". Any better idea? Feel free to make suggestions!


>the tutorial starts with instrument lightning at 100% during day!

Ooups, somehow I didn't notice that... I'll correct it.

**Comment by gilbertohasnofb** [comment]
> In the definition of the cockpit view, there are limits present. Because of this the view can't move more than +-140 degree. If the tutorial changes the view heading from, let's say 140 deg to 220 deg, the view cannot turn the direct way, but it turns the other way round.

Hmm, I see. But let's say that between point A and point B, the camera will spin to the wrong side. Couldn't we define a point C in between those two so that the camera goes from A to C and immediately from C to B, and the angle of rotation in those smaller segments will never exceed 140 degrees?

> I had no better idea where to put the marker for "Close the door". Any better idea? Feel free to make suggestions!

Yeah, pointing finger is easy but coming up with ideas is hard: I reported it but never occurred to me what would be a better solution, and I can't think of any... :wink:

**Comment by dg-505** [comment]
I don't think it's possible to define two camera "waypoints" in one tutorial step.Otherwise that would be a solution.
For a test, change the line 558 in the  tutorial **preflight.xml** to ```<heading-offset-deg>160.0</heading-offset-deg>``` I'm almost sure this will lead to a funny result when this step comes up.

**Comment by gilbertohasnofb** [comment]
In that case, we could ask in the devel list for this to be fixed. Maybe the rotation direction could clockwise if the angle is positive and counter-clockwise if negative, for instance. Or it could be set in a different parameter as well. Would you be interested in asking them for this? I know next to nothing about how the camera works in the Tutorials...

**Comment by gilbertohasnofb** [comment]
@dg-505 I have update the description of this issue, so there are now three things concerning the tutorial, all of which we can work under a single issue and then create a single PR, is that fine with you?

About the control surfaces conditions, what about listening to these conditions on the moment the tutorial moves to those specific checks:

left aileron condition: `/controls/flight/aileron` equal to `-1.0`
right aileron condition: `/controls/flight/aileron` equal to `1.0`
elevator condition: `/controls/flight/elevator` equal to `-1.0`
rudder condition: `/controls/flight/rudder` equal to `1.0`

The signs are correct because of the way I did the interpolation: those values are achieved in the end of the animation for each of the 4 surface checks, so that the condition will be true only at the very end of the animation. Does that make sense?

**Comment by dg-505** [comment]
@gilbertohasnofb about your points in the description:

* Unfortunately I still didn't find a way how to solve this problem... I also experience this with the tutorials of the DHC-6 Twin Otter

* The tutorial doesn't make use of the walker but maybe I find a way to incorporate these in the tutorials though it might be just  eye-candy

* While the idea of your last post is good, the implementation won't be that easy. Let me try to explain this: The tutorial waits a short time (don't know the exact time) until it checks if the condition is complied. If that's not the case it waits another few seconds until it checks again. This means that the property has to be at a consistent value at least for a few seconds. In your suggestion the property has this value only for a very short time and it would be a big coincidence if that works.
Because of this I believe the most reliable way is to use a separate property as I suggested...

**Comment by gilbertohasnofb** [comment]
> Unfortunately I still didn't find a way how to solve this problem...

No problems, if we ever think of something we can then improve it.

> The tutorial doesn't make use of the walker but maybe I find a way to incorporate these in the tutorials though it might be just eye-candy

I see. I believe that the fuel level is normally checked visually during the preflight inspection and not only via the gauge in the cockpit (correct me if I am wrong), so the ladder would be a cool addition. We could then "fake" the walker climbing the stairs: the camera in the tutorial would stop in front of the wing, a ladder would be added, and the camera would go a bit up and forward as if going up the ladder, and then the user can click on the cap. Camera goes down, ladder removed, tutorial moves on. What about that?

> The tutorial waits a short time (don't know the exact time) until it checks if the condition is complied. [...] In your suggestion the property has this value only for a very short time and it would be a big coincidence if that works.

Oh, I didn't know that! I see, I see... So probably we need to do it the way you suggested, though the tutorial must also force that property to `false` at the beginning just in case someone wants to go through the tutorial twice, and then the property would already be `true` from the first time, correct? We actually don't need to touch those Nasal functions, we can simply assign a value of `true` to these new properties via XML in the `Models/c172p.xml` when one clicks on the surfaces. What do you think?

**Comment by gilbertohasnofb** [comment]
@dg-505 I am also thinking about implementing a control lock for the yoke, so this would also be part of the tutorial (it need to be removed when in the cabin)

**Comment by dg-505** [comment]
> camera in the tutorial would stop in front of the wing, a ladder would be added, and the camera would go a bit up and forward as if going up the ladder, and then the user can click on the cap. Camera goes down, ladder removed

I was thinking about exactly something like this +1

> the tutorial must also force that property to `false` at the beginning

Correct, thanks for the reminder

> assign a value of `true` to these new properties via XML in the `Models/c172p.xml`

That's a good idea, imo more elegant than the nasal stuff I suggested

**Comment by dg-505** [comment]
> implementing a control lock for the yoke

I already had that idea, too, as this item is available in the checklist, though it's not activated.
That would be a really nice feature

**Comment by gilbertohasnofb** [comment]
@dg-505 great, so:

>> assign a value of `true` to these new properties via XML in the `Models/c172p.xml`
> That's a good idea, imo more elegant than the nasal stuff I suggested

Would you do this in the same PR that will tackle these tutorials so we don't need to open a new issue and another PR for that? Remember to also initialize the property as `false` in the `-set.xml` file.

>> implementing a control lock for the yoke
> I already had that idea, too, as this item is available in the checklist, though it's not activated.
> That would be a really nice feature

How familiar are you with 3D modelling? Would you be able to (and of course would you be interested in) give me a hand with this? I am rubbish at 3D modelling, but I would be glad to make a texture for it and do the coding. But if not, no worries, I can then try to convince someone else :smiling_imp:

**Comment by dg-505** [comment]
Well, with all the points together, I guess that the next tutorial PR will be a bit bigger..... ;)

> How familiar are you with 3D modelling?

Actually I consider myself to be quite capable. At least I have been with AC3D but this is only for windows and currently I'm trying

**Comment by gilbertohasnofb** [comment]
> Well, with all the points together, I guess that the next tutorial PR will be a bit bigger..... ;)

Not a problem I suppose, as they are all related!

> OTOH this control lock isn't a big deal so I think I can give it a try.

Great, so in that case we could create a new branch `bug-865` and work together there before making a PR. I will create a texture for the lock right away.

**Comment by gilbertohasnofb** [comment]
@dg-505 when you would have a chance, would you like to update the checklist as well as the pre-flight tutorial as to include the yoke control lock? Right now, the checklist has the item for the control lock, but it is not clickeable:

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/22909058/20070cf4-f252-11e6-8e8b-d9b527a98589.png)

The tutorial also skips over it. If you take a look at this, remember to add a conditional to check if the option "allow securing aircraft" is toggled before activating the lock.

We are now working on the 2017.1 release and tomorrow evening (Wednesday the 14th) we will ask for a merge into FGDATA. So if you have the time and interest in having a look at this before that, it can still make it to the new release, else we can work on it on a later date.

**Comment by dg-505** [comment]
Yes, I will do that today evening. And if there's still time left after that I will work on the other tutorial steps that we've talked about.

**Comment by gilbertohasnofb** [comment]
@dg-505 Great, thanks a lot! I should be online during most of the day, so just let me know if you need some help (with testing, for instance)

**Comment by dg-505** [comment]
I'm home, so let's go!
Here's what I have to do:
1. Control lock (checklist and tutorial) --> high priority!
2. Flight surface checks (checklist and tutorial)
3. Fuel capacity and contamination checks (tutorial), like you suggested:
> We could then "fake" the walker climbing the stairs: the camera in the tutorial would stop in front of the wing, a ladder would be added, and the camera would go a bit up and forward as if going up the ladder, and then the user can click on the cap. Camera goes down, ladder removed, tutorial moves on.

Was that all or did I forget something? :wink:

**Comment by gilbertohasnofb** [comment]
@dg-505 I think that's basically it, in particular the numbers 1 to 3. The "faking" of the walker climbing would be neat but if you find some difficulties implementing it then I would suggest not worrying about it at this time and having a look at it at some other time after the release.

I should be around the whole day so just let me know if I can help with anything.

**Comment by dg-505** [comment]
[New branch](https://github.com/c172p-team/c172p-detailed/tree/bug-587-preflight-tutorial) and [pull request](https://github.com/c172p-team/c172p-detailed/pull/905) created! :grin:

**Comment by gilbertohasnofb** [comment]
Great! I will take a look at it now :smile:

**Comment by onox** [comment]
@gilbertohasnofb @dg-505 Can this issue be closed? The corresponding PR has been merged.

@dg-505 If you add "Fixes #<number>" in the description of a PR then Github will link the PR to that issue, closing it automatically when the PR gets merged.

**Comment by gilbertohasnofb** [comment]
@onox there are still some stuff left to be done with the tutorials and checklists, but I created a new https://github.com/c172p-team/c172p-detailed/issues/906 for those specific issues, so this here can be closed

**Comment by gilbertohasnofb** [comment]
Closed via https://github.com/c172p-team/c172p-detailed/pull/905
