### ISSUE TITLE
Duplicate wing objects

### ISSUE THREAD

**Issue by onox** [c172p-team/c172p-detailed#592]
With the current Blender files we have 10 objects for 10 states.
A lot of objects are partly duplicated because of this (the vertices).

Example 1: the middle section of `wing_1BB` and `wing_1BD` are (basically) the same.
Example 2: right outer wing part of `wing_1RGLB` and `wing_1LD` are the same.

| Left | Right | Blender |
| --- | --- | --- |
| ok | ok | (in default Blender file) |
| dmg | ok | wing_1LD |
| brk | ok | wing_1RGLB |
|  |  |  |
| ok | dmg | wing_1RD |
| dmg | dmg | wing_1BD |
| brk | dmg | wing_1RDLB |
|  |  |  |
| ok | brk | wing_1GRB |
| dmg | brk | wing_1LDRB |
| brk | brk | wing_1BB |
|  |  |  |
| col | col | wing1Collapse |

If we split the wings in two halves (left and right) we can reduce it to
6 or 7 objects for 10 states. If you want to make a change to one of the parts,
for example the left outer damaged wing, you only have to modify 1
object (`left_dmg`) instead of 3 (`wing_1LD`, `wing_1BD`, and `wing_1LDRB`).
It will make the model XML file easier and smaller.

These are the objects you get:
- `left_ok`
- `left_dmg`
- `right_ok`
- `right_dmg`
- `col_and_col` (or you can choose `left_col` + `right_col`)
- `inner_wing`

So now we only need about 5 select animations (`inner_wing` object is always
displayed) instead of 10.

The only thing the 3D modeller has to be aware of is to make sure the vertices
of the outer parts precisely align with the `inner_wing` object so that the user
doesn't see the cutting edge when a wing halve (left and/or right) is ok.

For all the 10 states here's which objects to display:

| Left | Right | Model XML file |
| --- | --- | --- |
| ok | ok | inner_wing + left_ok + right_ok |
| dmg | ok | inner_wing + left_dmg + right_ok |
| brk | ok | inner_wing + right_ok |
|  |  |  |
| ok | dmg | inner_wing + left_ok + right_dmg |
| dmg | dmg | inner_wing + left_dmg + right_dmg |
| brk | dmg | inner_wing + right_dmg |
|  |  |  |
| ok | brk | inner_wing + left_ok + right_brk |
| dmg | brk | inner_wing + left_dmg + right_brk |
| brk | brk | inner_wing |
|  |  |  |
| col | col | col_and_col or inner_wing + left_col + right_col |

**Comment by onox** [comment]
@wlbragg @thevirtualfer See above ^^

**Comment by onox** [comment]
This also might make it easier to do (very subtle) wing flex (for `left_ok` and `right_ok`).

**Comment by onox** [comment]
`Effects/model-wingflex-organic` works great for the Pterosaur, but not for our aircraft :cry::

![fgfs-screen-369](https://cloud.githubusercontent.com/assets/3361585/11540870/6d86034a-992f-11e5-850b-0306c5a5ac11.png)
![fgfs-screen-371](https://cloud.githubusercontent.com/assets/3361585/11540872/6d8b29a6-992f-11e5-97d0-c4b40bd86df3.png)
![fgfs-screen-370](https://cloud.githubusercontent.com/assets/3361585/11540871/6d8a55ee-992f-11e5-82b2-76dbf089d702.png)

![fgfs-screen-373](https://cloud.githubusercontent.com/assets/3361585/11540873/6d8bf1ce-992f-11e5-8329-9509c86a22b9.png)
![fgfs-screen-374](https://cloud.githubusercontent.com/assets/3361585/11540874/6d8c4cbe-992f-11e5-9918-6e00882e745c.png)

**Comment by wlbragg** [comment]
I understand what your referring to as far as splitting the wing part and I agree there is room for improvement. Unfortunately at the time I didn't have the skill set to do that and I'm really not sure I could do it now. So it may require the services of an expert.

**Comment by onox** [comment]
Well it's good you see there's room for improvement :smile: Hopefully @thevirtualfer will notice see this page then.

About the wing flex, those wings seem to be made from [titanium](https://www.youtube.com/watch?v=Kx5YeqTBcDI&t=88) (as I already expected). Although it would be nice if that vertex shader eventually becomes usable for more than just dragons (for other aircraft).

**Comment by wlbragg** [comment]
These are the objects you get:

left_ok
left_dmg
right_ok
right_dmg
col_and_col (or you can choose left_col + right_col)
inner_wing

Are we missing ?
left_broke (gone)
right_broke (gone)

**Comment by wlbragg** [comment]
Speaking of damage, I'll  ask here and we can make an issue should we choose to do this.
While trying to test the pontoon leaking I damages a wing, (broke it actually), I was thinking it might be a nice feature to be able to repair the individual parts as well as the entire craft.

**Comment by onox** [comment]
> Are we missing ?
left_broke (gone)
right_broke (gone)

No, the whole point is to realize that when a wing halve is broken, that you don't see the outer part. (Because that part of the wing has been torn off from the aircraft). So these `left_brk` and `right_brk` parts you're talking about are invisible. The only thing you keep seeing when both sides of the wing are broken, is the `inner_wing` part.

**Comment by onox** [comment]
Although if you want to animate them being torn off from the aircraft (perhaps via a particle system) then you could create these two `left_brk` and `right_brk` objects. But the difference is that in that case they will be displayed via the particle system, not via our regular model XML file.

**Comment by onox** [comment]
> I was thinking it might be a nice feature to be able to repair the individual parts as well as the entire craft.

That's a nice idea :smile:

**Comment by gilbertohasnofb** [comment]
> I was thinking it might be a nice feature to be able to repair the individual parts as well as the entire craft.

Why would anyone fix only the nose gear and leave a broken wing?

**Comment by wlbragg** [comment]
Well, the instant I needed it for was I was having problems damaging the pontoon without damaging or breaking a wing. It would have been nice to fix the wing and leave the pontoon damaged. But that is more debug help. It gave me the idea however that others may like the option to see some things in action or to train. For a while we had it so you could damage any part by clicking on a button. That of course was beneficial for debug but it also would have some benefits for users to be able to test certain effects of incidents of damage to the aircraft and how it affects things. I suppose instead we could make some scenarios  where you have one of these damage events happen during flight or whatever. Something like "Your on approach with a damaged gear, see how close you can come to landing the plain on the center line",. Or "You sustained damage to the wing, fly an emergency course to the nearest airport and land". You get the idea. But it would be nice to provide a mode where the user could choose what they want to train on.

**Comment by wlbragg** [comment]
@onox, I was starting to take a look at this and I realized that by adding a leading edge addition to this that we now have even more models to deal with.
We created the leading edge for the dirt effect so we could customize that edge differently from the rest of the wing, which in theory is a good idea as it should get dirtier quicker. How much customization, I don't really know. Minimum it would allow a different dirt pattern and also be controllable at a different rate than the rest of the wing.
Before I go any farther do you have an opinion on this? Basically I am asking, do we just suck it up and incorporate the extra parts into our damage models?

**Comment by wlbragg** [comment]
If we retain the leading edge as being separate in the damage models can I combine the leading edge together with the rest of it's wing part, or do I leave it distinct as all the effects still apply to the parts and would have to be modified accordingly? I think we have to leave it separate, correct?

**Comment by wlbragg** [comment]
@onox, we are using many "damage" strobe objects and translating them the same as we do the original strobe1 and strobe2 objects. There is no reason to do this as far as I can tell. Can't we simply use a condition on the original two strobes to translate them where we want them for each damage or non-damage condition?
For example...
~~~
<animation>
        <type>translate</type>
        <object-name>strobe1</object-name>
        <offset-m>5.760493</offset-m>
        <axis>
            <x> 0.105</x>
            <y>-5.65777</y>
            <z> 0.53365</z>
        </axis>
    </animation>

    <!-- Damage Mod -->
    <animation>
        <type>translate</type>
        <object-name>strobe1BD</object-name>
        <offset-m>5.760493</offset-m>
        <axis>
            <x>0.293912</x>
            <y>-5.227128</y>
            <z>0.999938</z>
        </axis>
    </animation>
~~~
becomes
~~~
<animation>
        <type>translate</type>
        <object-name>strobe1</object-name>
        <condition>
            <no damage>
        </condition>
        <offset-m>5.760493</offset-m>
        <axis>
            <x> 0.105</x>
            <y>-5.65777</y>
            <z> 0.53365</z>
        </axis>
    </animation>

    <!-- Damage Mod -->
    <animation>
        <type>translate</type>
        <object-name>strobe1</object-name>
        <condition>
            <damage>
        </condition>
        <offset-m>5.760493</offset-m>
        <axis>
            <x>0.293912</x>
            <y>-5.227128</y>
            <z>0.999938</z>
        </axis>
    </animation>
~~~

We lose the following four objects in the damage model that way.
strobe1BD
strobe2BD
strobe1Collapse
strobe2Collapse

To take it a step farther maybe we do it in a fcs_function, although I don't know that the axis positions are exposed that way.

**Comment by wlbragg** [comment]
Thanks!

**Comment by wlbragg** [comment]
Hum, that's actually an interesting concept, your rotating the lights, I'm trying to translate them by selecting a different translate position based on a condition. It doesn't appear to work this way. I think I need to use a property that changes the position through one translate animation VS conditioning to use set translations. That is basically what your doing except using a rotation animation.

**Comment by wlbragg** [comment]
@onox 
I have another issue. I was going to model any wings broken with a jagged edge, both with two jagged edges. That doesn't fit with the above layout as we would technically have to have 3 center models, left jagged, right jagged, both jagged.
Thoughts anyone?
Another option is to break them off cleanly using @gilbertohasnofb rib texture in the ends to help add a higher level of realism.

**Comment by wlbragg** [comment]
I went with the third option, it works fine.

I do have a very difficult problem however, I can't get the landing/taxi light cover to export correctly. By that I mean it crashes the sim when a select animation makes it visible.
Here is what I think I know...

It is a straight copy appended from the main blend which brings over it material and texture mapping settings, I think.

It like all the other glass simulated objects we have in the aircraft is uvmap activated but no mapping has been done and no texture assigned, basically it only has a material.

If I assign it a texture then it doesn't break and crash the sim anymore, but none of the other glass simulating objects have a texture assigned to them, even it's "EXACT" duplicate in another blend.

I'm stuck on this simple piece of ...expletive... glass!

I am very close to being finished with the new damage models but this is hanging me up.

**Comment by wlbragg** [comment]
Wow, I am such a dummy, I figured it out. I accidentally left the glass material joined with a another object using none compatible settings, duuu!

**Comment by wlbragg** [comment]
Spoke too soon, while that could have been the issue, It wasn't. I completely started from scratch and as soon as I try to import or assign an object with the settings we typically use for glass, it crashes the sim. I don't why, but I am done waisting my time on this. If someone else can figure this out I will leave the landinglightcover_D object in the Blend.
The way I look at it, where the wing bends in the damage model it would certainly break the glass at that location anyway. Maybe I can come back to it and even make a jagged broken piece of glass in place of the full cover, but right now it is stopping my production and I am fed up with it.

**Comment by wlbragg** [comment]
Here is the first look at the new damage models. You can see my solution for the landinglightcover object. I am choosing to have it shatter and fly away and while it is at it it brakes the landing and taxi light bulbs.
![dmg1](https://user-images.githubusercontent.com/11069680/37847071-90deed9c-2e9d-11e8-983a-f3283f2b0788.jpg)
![dmg](https://user-images.githubusercontent.com/11069680/37847080-96ab91c6-2e9d-11e8-8c35-cb943a4154c9.jpg)

**Comment by onox** [comment]
> Can't we simply use a condition on the original two strobes to translate them where we want them for each damage or non-damage condition?

Yes, if you can change the animations so that you can reuse objects, then you should do that.

**Comment by onox** [comment]
@wlbragg So I need to enable `landinglightcover_D` in the blend file and then export the ac file and then FG should crash?

**Comment by onox** [comment]
> Another option is to break them off cleanly using @gilbertohasnofb rib texture in the ends to help add a higher level of realism.
A third option is to extend the undamaged center section with two separate rib and jagged edges and call those two pieces when appropriate, left_jag, right_jag or both of them. That way the center section can still be on all the time making things much simpler.

My original idea was the second option (so you cleanly cut the outer parts of the wings), but maybe the third option is okay too (as long as you only duplicate a tiny amount of vertices)

**Comment by wlbragg** [comment]
@onox  

>So I need to enable landinglightcover_D in the blend file and then export the ac file and 
then FG should crash?

Yes, it has been pushed now so you can do that if you want to try to figure out why it is crashing FG. However I am happy with the solution of simply not using the cover as it would probably have broken in any of the damage events where we want to use it. But if you can get it to work I think it would be really cool for me to break the glass and leave part of it where appropriate, like I do now with the taxi and landing light bulbs.

>but maybe the third option is okay too (as long as you only duplicate a tiny amount of vertices)

This is what I did and I think it worked great. It will look even better I think when I get @gilbertohasnofb rib texture mapped.

Anyone that can take the time to test the damage models, please do. It's hard to test them and achieve all possible conditions.

I think the following are what need to be verified to work.
Left damaged right not
Right damaged left not
Left and right both damaged
Left damaged right broken (gone)
Right damaged left broken (gone)
Left and right both broken (gone)
Left and right both collapsed

Of these I have verified
Left and right both damaged
Left and right both broken (gone)
Left and right both collapsed

Sill to do is the strobe lights and any other lights. I don't remember what lights we allow to work after damage, It may be easiest and the least amount of overhead to simple not allow any lights to work if a wing is damaged in any way. What do you all think about that?

Here is the both wings broken condition
![dmg2](https://user-images.githubusercontent.com/11069680/37860917-659e7dcc-2efd-11e8-8c36-472c3331382b.jpg)

**Comment by wlbragg** [comment]
After testing a bit more I see we do allow lights after damaging the wings. If we do away with that concept and consider the electrical system for the lights broken when there is wing damage, then we are pretty much done with this issue once we condition the lights to no longer work.
I think that is the easiest thing to do and I see no reason to go through the effort of having to re-factor the lighting for the damage models.

**Comment by dany93** [comment]
@wlbragg wrote:
> Anyone that can take the time to test the damage models, please do

I've done some tests, got these situations and observations.

**Properties:**
`/fdm/jsbsim/wing-damage/left-wing=.... , right-wing=....` (0, 0.12,  0.3, 1=broken=gone)

Flyable and still controllable with:
- a single wing at 0.12 (not more),
- both wings at 0.3.

**3D model remarks:** as seen from the exterior.

**Results**


Left wing | Right wing | Left 3D | Right 3D | Remark |
------------ | ------------- | -------- | ---------- | ------------|
0.12 | 0 | bent | **broken** | issue |
0 | 0.12| **broken** | bent | issue
0.3 |0.3 | bent | bent |
0.3 | 1 | (?) | (?) |
1 | 0 | broken  |**broken** | issue |
0  |          1   |              **broken** | broken      |     issue
1  |          1   |              broken | broken

Some 3D as seen do not match the Property values. One 3D wing seen as broken instead of not damaged in the case the other one was partially damaged or broken.

Uneasy to test. If you don not confirm, please tell me to check again.

**Comment by wlbragg** [comment]
Thanks @dany93 I think I'll have to override the damage system and set the damage properties by hand to really test these. I can't confirm your findings without getting the condition which as you know is really difficult to achieve.

**Comment by dany93** [comment]
I believed having seen 0.3 and 1, however I'm wondering is it can happen. Based on my spirit when I did it.

**Comment by onox** [comment]
I noticed when both wings are damaged (bended upwards), the green ALS light moves with it (correct), but the red ALS light moves above where it should be (not correct).

**Comment by onox** [comment]
When the wings are broken, the sides of the wings (where they are damaged) is grey/purple and reflective. I don't see the green unpainted interior of the wing. Isn't that what we wanted?

**Comment by onox** [comment]
@wlbragg You can test this by commenting lines 388 to 390 in the -set.xml file (you disable `Systems/damage.xml`). Then you adjust `/sim/models/c172p/damage` by setting the value to 0 (ok), 1 (broken), 2 (damaged).

**Comment by onox** [comment]
I can fix this in an hour and migrate it to 2017.2 protocol as well.

**Comment by onox** [comment]
Gonna do the migration in a different PR.

**Comment by dany93** [comment]
Tests: wing animations vs property values, OK.
(done at rest, by setting manually the prop values)
Independently, every configuration and combinations (each wing at 0, 0.12, 0.3, 1) ==> 3D match the property values.
As the property values matched the flight stresses in my previous tests above, that should be OK.

_Your  ribbings with holes which appear when a wing is broken are amazing!_
