### ISSUE TITLE
Improvement to the rudder pedals

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#600]
Currently our rudder pedals are simply "floating" above the ground. They should have a bar connecting them to the floor, as well as holes on the floor where they are free to run (alternatively, I can "make" the holes in the textures, but this isn't an ideal solution IMO).

![](https://i.ytimg.com/vi/tanXy8rnuy0/maxresdefault.jpg)

![](http://www.trcsimulators.com/wp-content/uploads/2014/02/rudderpedals1a.jpg)

**Comment by wlbragg** [comment]
I can do this also.

**Comment by wlbragg** [comment]
Here are a couple videos showing the finished product.
https://www.dropbox.com/s/xw3tv0z4pdw9slw/2018-03-15%2011-40-35.mkv?dl=1
https://www.dropbox.com/s/wq7sprpz4a60n2q/2018-03-15%2011-44-52.mkv?dl=1

**Comment by gilbertohasnofb** [comment]
That is looking good, but I have the impression the pedals need to be raised a tiny bit in particular when comparing with the photos above. But it's also hard to tell from the videos.

**Comment by wlbragg** [comment]
>need to be raised a tiny bit 

I'll check it out and if I agree I'll move them up.

**Comment by wlbragg** [comment]
I did move these up, are they good now?

**Comment by gilbertohasnofb** [comment]
Yes, they look good now!
