### ISSUE TITLE
Create oil cap and air side door 3D objects

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#621]
Create oil cap and cabin air side door (on the right side of the fuselage) 3D objects. See:

![](http://www.weekendcfii.com/photos/c172preflt/C172_oil_dipstick.jpg)

![](http://www.kentstreetshs.wa.edu.au/Images/General/cessna%20172SP.jpg)

**Comment by gilbertohasnofb** [comment]
Maybe we could also create a dipstick model which becomes visible when the oil cap is opened:

![](https://www.wagaero.com/media/catalog/category/I-944-300.png)

**Comment by gilbertohasnofb** [comment]
@wlbragg this could be an interesting one to tackle in the current or some of the next mesh PRs. How complicated do you reckon this one would be?

**Comment by wlbragg** [comment]
Not too hard I don't think. Could you post a picture backed out aways so I can see where to place the oil access door on the fuselage.

**Comment by gilbertohasnofb** [comment]
You could use the normal map as reference, though it seems to me the oil door is a bit too close to the window in the map:

![fg](https://user-images.githubusercontent.com/5700795/37241340-791bf90a-244f-11e8-892e-f4ba009821a9.jpg)

Here are a couple of reference shots of the OH-CTL: 

![_dsc8029](https://user-images.githubusercontent.com/5700795/37241343-8a2da46e-244f-11e8-905c-453d0d726e07.jpg)
![_dsc8031](https://user-images.githubusercontent.com/5700795/37241344-8a4be366-244f-11e8-9442-fb3ff02f9e2d.jpg)
![_dsc8032](https://user-images.githubusercontent.com/5700795/37241345-8a672e6e-244f-11e8-8280-df1f316fa7a5.jpg)
![_dsc7990](https://user-images.githubusercontent.com/5700795/37241353-9d70c452-244f-11e8-9cdf-f0712f686ec0.jpg)

**Comment by wlbragg** [comment]
Oil door and compartment is created. "OilCap" object is the new "hot-click-spot". Please heck the logic in Models/c172p.xml for the oil management. I removed the select for the hot-spot as it really doesn't apply anymore and used OilCap for the pick. Could use a new "yellow" texture for the OilCap in panel-parts.png.
![oil](https://user-images.githubusercontent.com/11069680/37268652-fcb0db28-2594-11e8-944c-e924c9ab5c9d.jpg)
![fgfs-screen-001](https://user-images.githubusercontent.com/11069680/37268660-009cf7f8-2595-11e8-9691-605f4124d1f8.png)
![fgfs-screen-002](https://user-images.githubusercontent.com/11069680/37268663-01ffcbac-2595-11e8-9ad0-6cda8b12f493.png)

**Comment by wlbragg** [comment]
Did you want the vent?
![vent](https://user-images.githubusercontent.com/11069680/37268679-161b800e-2595-11e8-8cc5-51c08f269107.jpg)

**Comment by legoboyvdlp** [comment]
@gilbertohasnofb would you have any idea incidentally about the cable going into the oil cap? It wouldn't be the external heater by any chance?

If it is, I suppose I have to fix the external heater 3D model 😩

**Comment by legoboyvdlp** [comment]
This shows me I might have to keep working on the engine damage... merging it may become more and more difficult as it goes on :P

**Comment by gilbertohasnofb** [comment]
> would you have any idea incidentally about the cable going into the oil cap? It wouldn't be the external heater by any chance?
>
> If it is, I suppose I have to fix the external heater 3D model weary

I really don't know, but these photos were taken by @tigert so perhaps he would know about it. But please careful on tweaking anything related to the ground equipment at the moment as I am reworking their textures on the branch `issue-1000`. So if you decide to change anything, could you please wait for that branch to be merged? At the moment I am just waiting for @wlbragg to improve the UV-map of the fuel tanker and then I will create a PR.

**Comment by gilbertohasnofb** [comment]
> Did you want the vent?

@wlbragg Yes I do. And I also would add that "handle" that is just above this vent, as I've seen that in most photos of the 172P. You could just UV-map them to the fuselage colour just beneath them. Would that be fine?

**Comment by gilbertohasnofb** [comment]
@wlbragg About the oil cap, that looks truly wonderful! What branch is that, as I don't see it in the new mesh PR? I see you modelled a cap for the oil tank, which is super cool. But then please make a separate object, so that when you click on it after opening the oil tank door the cap will disappear and the dipstick will appear, what do you think? Concerning the textures, please do not map them to bits used for something else, as if one day someone decides to change a toggle texture for instance it will be puzzling why that affects other objects. Since the oil cap is part of the external model, please map it to some of the white areas of `fuselage.png` and then send me the image of where it is mapped (preferably in the same resolution as the original `fuselage.png` so that I can simply superimpose it as reference when creating a new texture). Does that makes sense?

**Comment by gilbertohasnofb** [comment]
I just realized the dipstick is actually part of the cap itself!

![](https://i.pinimg.com/originals/81/1d/da/811dda52a73c1166c574f448c4ea9218.jpg)

So one click to open the oil door, another click to lift the cap showing the dipstick, which would then open the menu. The hotspot for the cap+dipstick needs a condition that the oil door must be opened and the hotspot of the door needs the condition that the cap+dipstick must be closed (screwed in place) since in FG mouse clicks go through solid objects. See:

![image](https://user-images.githubusercontent.com/5700795/37294601-151eb288-260e-11e8-94d0-1a0b87af0a86.png)

**Comment by gilbertohasnofb** [comment]
@wlbragg when I am ready to push, there will be some new textures to map to the oil door and the dipstick. A is the interior of the oil door, B is the top (cap) of the dipstick, C is the sides of the cap and D is the stick itself:

![image](https://user-images.githubusercontent.com/5700795/37296154-fc8c7d64-2611-11e8-9f2a-77fdb93a90e0.png)

I am using this image as reference: https://github.com/c172p-team/c172p-detailed/issues/621#issuecomment-239864629

**Comment by wlbragg** [comment]
>About the oil cap, ....  What branch is that, as I don't see it in the new mesh PR? 

I assume you found the oil cap work in the current PR. I thought maybe I forgot to push it, but I did.

>I see you modeled a cap for the oil tank,

I actually used a copy of the fuel cap. I'll modify it to look more like our examples, especially now that I have a texture for it. The cap already includes the dipstick, I ran out of time last night so I didn't get the animation for the dipstick and cap finished.  Nice job on all the new textures for it, It's going to look really nice. I should be able to finish up this entire issue tonight.

**Comment by wlbragg** [comment]
@gilbertohasnofb when you get a chance could you add a red texture for the "Fuel Caps" like you did for the Oil Cap. Currently the Fuel Caps are mapped to a switch texture on panel-parts.png, I want to map them like the oil cap to fuselage.png. Don't push it until I am finished tonight and give you the OK.

**Comment by wlbragg** [comment]
@gilbertohasnofb 
Logic and mapping of the OilCap is finished. I added some extra logic trying to account for all contingencies. 
The logic is as follows, feel free to change anything as you see fit.

Click to open or close oil door.
Only allow clicking Oil Cap if door is open and same conditions as before apply, only on ground with engine off. 
Clicking the closed Oil Cap opens dialog and shows dipstick.
Closing door or dialog closes Oil Cap.
Clicking open Oil Cap closes Oil cap and dialog, not the door.
Closing the dialog closes the Oil Cap not the door.
Starting the engine in any manner closes the Oil Cap, not the door, not the dialog.

I think that covers all of it. Like I said, if you want to change any of the logic feel free to.

**Comment by wlbragg** [comment]
Well I didn't get completely finished. I still have the vent and the exhaust pipe whole to deal with. I think I found a solution for the exhaust pipe hole but it is going to take a bit of work to make it look good.

This should give you an idea as to what it is I am trying to do.
![fgfs-screen-001](https://user-images.githubusercontent.com/11069680/37327252-819fb79a-2663-11e8-96a6-f7b6436f9bfc.png)

**Comment by onox** [comment]
@wlbragg Maybe you can also model the cold air door on the right side of the aircraft? I think it's the red door in the lower left corner of https://github.com/c172p-team/c172p-detailed/issues/621#issuecomment-372205987

**Comment by gilbertohasnofb** [comment]
@onox I thought the cold air would enter through that little hood I circled in the image on that comment.

**Comment by onox** [comment]
Uhh, I don't know, I just know there should be a little door on the right side of the aircraft.

**Comment by onox** [comment]
But I thought it was actually a little door that could be opened. Don't have the POH here atm.

**Comment by gilbertohasnofb** [comment]
@onox I don't have it with me either, but I am quite sure the hood is where enters for the vents, and this has been modelled by @wlbragg in the newest PR we are working on. See for instance this photo of a Cessna 150:

![](http://www.flyingstart.ca/FlightTraining/preflight/cabinair.jpg)

**Comment by wlbragg** [comment]
I didn't do a "Cabin Air Vent", only the small port above and to the left (see green circle).
![vent](https://user-images.githubusercontent.com/11069680/37377590-d29a27b2-26f8-11e8-9242-c5c1db784244.jpg)

**Comment by gilbertohasnofb** [comment]
My mistake, the photo above is too low-res and I mistook it. Indeed the cabin air vent is that little door that can be opened. Here is a better resolution image of OH-CTL:

![image](https://user-images.githubusercontent.com/5700795/37377921-c579b350-2724-11e8-8e48-d1be3286eeed.png)

**Comment by wlbragg** [comment]
So you think that air vent opens with the cabin air slider knob, that is what adjusts the air volume, depends on how open the vent is?

**Comment by gilbertohasnofb** [comment]
Yes, I think that's how it works. We could ask some of the RL pilots if they can confirm this. @tigert @Juanvvc @algefaen @okroth

**Comment by wlbragg** [comment]
Well, I'm going to do this right. I just noticed the bottom door hinges are up too high, I am going to move them down, Then I will model the "cabin air vent". I'd like to confirm that the vent is opened by the air vent slider in the cabin, that makes sense to me.

**Comment by okroth** [comment]
It's the cabin vent knob, that when pulled out, opens the cabin vent door. The more you pull it, the more the door opens and directs air into the cabin ventilation ducts.
BTW. The cabin heat mixes in air that has been heated by streaming around the exhaust muffler. But you will unlikely see some action outside the plane :-)

**Comment by wlbragg** [comment]
Air vent is finished.

Still left to do,  fuel cap animations.

**Comment by legoboyvdlp** [comment]
Should this air vent add drag, or is the effect too miniscule to notice?

**Comment by gilbertohasnofb** [comment]
> or is the effect too miniscule to notice?

I would guess so. @dany93 ?

**Comment by okroth** [comment]
It may be negligible.

quick estimation: size is 5 by 8 cm, cw=1, speed v=100kt =50m/s:

F = 0.05m * 0.08m * 0.5 * 1.22kg/m3 * v*v * 1 = 6.1N

-- 
Oliver


Am 19.03.2018 um 00:25 schrieb Jonathan Redpath:

**Comment by legoboyvdlp** [comment]
6.1N is the equivilent of 610 grams, if I remember right... not really that much.
