### ISSUE TITLE
Create elevator trim tab

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#622]
Create elevator trim tab in the 3D model.

![](https://upload.wikimedia.org/wikipedia/commons/f/ff/Labeled_Cessna_172_trim_tab.jpg)

**Comment by legoboyvdlp** [comment]
Picture broken

**Comment by gilbertohasnofb** [comment]
Here is another one:

![](http://www.weekendcfii.com/photos/c172preflt/C172_elev_trim_tab.jpg)

**Comment by legoboyvdlp** [comment]
Sure. Looks easy enough. Though maybe @thevirtualfer worked on it?

**Comment by legoboyvdlp** [comment]
No guarantee!

**Comment by gilbertohasnofb** [comment]
>  Though maybe @thevirtualfer worked on it?

We haven't heard from him in months and he hasn't committed anything in the past 9-10 months. Very likely he worked on this on the new model, but we don't know when nor if it will come... the philosophy here is then to simply try to improve the things ourselves and then if he ever commits his new model then we see what to do.

**Comment by legoboyvdlp** [comment]
Right! I'll see what can be done then.

**Comment by Juanvvc** [comment]
In order to model the trim tab, you must open the huge main .blend file, understand it and cut a rectangular box in the horizontal stabilizer.

To model the seat mounts, you just create your own .blend with only the seat mounts. The, you can ask  any of the blender/xml modellers to append your file. I strongly believe the seat mounts are a much easier task to start a modelling career!

**Comment by legoboyvdlp** [comment]
Hah!
As for seat mounts.... well, they look tricky. And they aren't really visible at any time except for those crazy people who fly with their head resting on the rudder pedals and turning the yoke with their toes. But...
:)

**Comment by gilbertohasnofb** [comment]
> And they aren't really visible at any time except for those crazy people who fly with their head resting on the rudder pedals and turning the yoke with their toes. But...

I think they are quite visible from the outside with the doors opened :wink:

> well, they look tricky

**Comment by legoboyvdlp** [comment]
Ah! I see :)
I may go through to Noob2Pro tutorial I found first. It is a wikibook. Very detailed. Just this: ffom noob to pro.

**Comment by Juanvvc** [comment]
Keep in mind you can do both! I'm just suggesting you could begin modelling the seat mounts and after learning the basics with them, model the trim tab or any other "more visible" object.

The trim tab is easy, but you must also modify the horizontal stabilizer. This involves modifying an object in the main .blend file, and I believe touching anything in this file is not a good idea for a newbie in blender :)

Merry Christmas for you all!

**Comment by gilbertohasnofb** [comment]
> Merry Christmas for you all!

:santa: :snowman: :christmas_tree: :gift: Merry Christmas to all the gang!

**Comment by tonghuix** [comment]
Trim not shown on release 2016.1.

**Comment by onox** [comment]
There's indeed no trim tab in the 3D model currently. That's why this bug is still open. Hopefully some of the 3D modelers can add it in time for 2016.2.

**Comment by wlbragg** [comment]
I'll try to do this next, as soon as we get the mesh smoothing sorted out.
