### ISSUE TITLE
Improve and add to normals map (bumpmap)

### ISSUE THREAD

**Issue by wlbragg** [c172p-team/c172p-detailed#736]
I've been playing around with creating normal maps for various items on the c172p. Gimp has a plugin you can install that works as well as anything else I tried. My first experiment was the tires.
The first two images are over exaggerated. The last picture is with no normal map.

![normalmaps](https://cloud.githubusercontent.com/assets/11069680/14053287/21cf4c22-f29e-11e5-86f2-19f9b0d4e94b.jpg)

Some of the things we could do with it that might really enhance the look of the aircraft are
Crinkled metal where damaged.
Paint chips and flaws.
Fuel caps.
Many others, anywhere we want some better definition.

**Comment by onox** [comment]
Nice :+1: Is it possible to make the bottom side of the wing a bit more detailed? We should also clean up the wing (that's another issue) and perhaps use a mirror modifier.

**Comment by gilbertohasnofb** [comment]
@wlbragg Yes, I know that plugin, I used it for the oil cap as well as for some of the scenery textures I worked on. I like the effect very much, but in general creating a normal map out of the same texture you use for the UV map does not create the best results. If you are interested, this is interesting: http://www.katsbits.com/tutorials/textures/how-not-to-make-normal-maps-from-photos-or-images.php

But by all means let's try to apply this to some objects! The wheels can be made to look really nice indeed, would you have some other objects in mind in which the effect could be interesting?

@onox We already have a normal map for the bottom side of the wing but unfortunately it's not very detailed. I can help taking a look at it and trying to improve it.

**Comment by wlbragg** [comment]
>I like the effect very much, but in general creating a normal map out of the same texture you use for the UV map does not create the best results.

Yes, I kind of figured that out while playing around with the tires. It definitely requires a skilled artist or someone experienced in this technique to get the best results. Thanks for the link to that article, I'm sure that will help me considerably.
I figured we all knew about this, I just wanted to get it into an issue so we might all start adding more normal mapping as it is a really cheap way to enhance the look of the model.

**Comment by wlbragg** [comment]
Excellent article, that really helps!

**Comment by wlbragg** [comment]
Here is the tire and now the rim. The rim is only as good as the texture + the normal map. If you look closely you can see the enhancement. I can strengthen the normal also to get more definition.

![norm4](https://cloud.githubusercontent.com/assets/11069680/14058724/f9104746-f2f7-11e5-9861-6daffcd797b0.jpg)
Can you tell which tire and rim has the normal map?

**Comment by wlbragg** [comment]
Here I blurred the height map before I ran it through the normal filter at the strongest settings I could. I think this look much better.
![norm6](https://cloud.githubusercontent.com/assets/11069680/14058809/af9ea672-f2fa-11e5-956b-8c02fa02966a.jpg)

**Comment by wlbragg** [comment]
This is what the rim normal looks like now.
![norm7](https://cloud.githubusercontent.com/assets/11069680/14058834/5197d278-f2fb-11e5-96ea-c5a76d8fa5fe.jpg)

**Comment by wlbragg** [comment]
Here is the height map used to make the normal map. I drew the height map by hand by overlaying a blank layer over the uv texture sheet so I could see where to draw the elements.
![norm8](https://cloud.githubusercontent.com/assets/11069680/14058867/4777a5e2-f2fc-11e5-99ef-1183c9629932.jpg)

**Comment by gilbertohasnofb** [comment]
@wlbragg this is looking good! :smile: 

>  I drew the height map by hand by overlaying a blank layer over the uv texture sheet so I could see where to draw the elements.

That's how I do it as well.

As for the bottom of the wings, would you like to do that yourself or should I take a look at it? Right now I am a bit busy but later today I would have time for that

**Comment by wlbragg** [comment]
I'm not itching to do it so feel free. This stuff is new to me and thus time consuming.

**Comment by wlbragg** [comment]
Whoever pushes the first PR for this, we can just keep pulling and pushing what were working on until we decide there is enough to merge?

**Comment by wlbragg** [comment]
I just remembered you have
https://github.com/gilbertohasnofb/c172p-detailed-liveries/blob/master/Paintkit/fuselage-gimp.xcf
I just brought the normal and uv texture into Gimp and made my own file. Should any height map I make be added to your file? Do we also want to keep the normal layers there? I like having the development folder with the project and keeping it all together too, so I don't know how to handle this.
Maybe I should take the 4 files from the link above, add all the normals and any other appropriate layers and make a master in the dev folder here in this project?

**Comment by gilbertohasnofb** [comment]
> I just brought the normal and uv texture into Gimp and made my own file. Should any height map I make be added to your file? Do we also want to keep the normal layers there? I like having the development folder with the project and keeping it all together too, so I don't know how to handle this.

@wlbragg the idea of that other repository is to keep all xcf there, since they are huge and would make the main repository unnecessarily large. You don't need to keep the height map in the same xcf as the paintkit (actually, it is better to have a separate file for that since the height map .png and the airplane textures .png are different files, so different .xcf are better as well). 

I would say that when you create new height maps, simply keep the png in our repo here and push the xcf to the other liveries repo there (I believe you all have access to the other repo, but if anything goes wrong just let me know).

Makes sense? What do you think?

> I'm not itching to do it so feel free. This stuff is new to me and thus time consuming.

Ok, I will take a look at it now.

> Whoever pushes the first PR for this, we can just keep pulling and pushing what were working on until we decide there is enough to merge?

Sounds like a plan :+1:

**Comment by gilbertohasnofb** [comment]
@wlbragg also, I assume you already have a branch in which you are working on this, right? If so, would you mind pushing this branch so I can work on it as well, and so we can have a single PR later on?

**Comment by gilbertohasnofb** [comment]
@onox as for the bump map for the bottom wing, I had a look at it and I can add more details to it, but I think that it is barely visible anyway since the bottom wing is almost never directly illuminated. On the ground I can barely make up the bump map, just on the air when the plane is a bit tilted. I also tried making the contrast of that bump map more extreme, but even then the bottom wing's effect is really hard to see. What do you think?

**Comment by wlbragg** [comment]
>I assume you already have a branch in which you are working on this, right?

I do but I need to start a cleaner branch (or at least take the time to check this one against master) as I'm not positive what all is in it. So if you beat me to a point where you want to push a branch, it is nothing for me to adapt to it and bring my work over to it. It would be later tonight before I can push a branch is all I am saying.

I'll make a xcf with the height and normal maps and push to your repo (also later tonight)

**Comment by wkitty42** [comment]
On 03/26/2016 04:46 PM, Gilberto Agostinho wrote:
> @onox <https://github.com/onox> as for the bump map for the bottom wing, I had a
> look at it and I can add more details to it, but I think that it is barely
> visible anyway since the bottom wing is almost never directly illuminated. On
> the ground I can barely make up the bump map, just on the air when the plane is
> a bit tilted. I also tried making the contrast of that bump map more extreme,
> but even then the bottom wing's effect is really hard to see. What do you think?

here's something else related to the bottom of the wing... it is possibly a 
different bug/issue, though...

sitting on the apron or runway somewhere, get it raining where there's a lot of 
rain coming down... now look up at the bottom of the wings... even the bottom of 
the craft i think... should we see those raindrop effects like that?

**Comment by gilbertohasnofb** [comment]
@wlbragg Sounds good to me. I have nothing to push since my attempts with the bump map of the bottom wing didn't work well. Also, I checked and we don't have xcf for the bump maps, so just push them to the `Paintkit` folder of the liveries repository. But there is no rush at all.

@wkitty42 that would be a different issue as it's not related to bump maps. I tried reproducing it but for some reason I am not seeing rain in my sim, only in the windshield :cry: But I think this bug you report should have a new issue just for itself

**Comment by wkitty42** [comment]
On 03/26/2016 05:29 PM, Gilberto Agostinho wrote:
> @wkitty42 that would be a different issue as it's not related to bump maps.

right...

> I tried reproducing it but for some reason I am not seeing rain in my sim,
> only in the windshield :cry:

it has been a while but i'll have to try KSFO with a storm again... now that we 
have full tie down capability, my craft should remain tied to the tarmac instead 
of being flung upside down onto the top of the terminal :)

> But I think this bug you report should have a new issue just for itself

i'll try to remember to get one filed... am in a flight right now rebuilding my 
.terrasync_cache files... have stuck a sticky note to my forehead...

**Comment by gilbertohasnofb** [comment]
> it has been a while but i'll have to try KSFO with a storm again... now that we have full tie down capability, my craft should remain tied to the tarmac instead of being flung upside down onto the top of the terminal :)

Nice :smile: So if you do see that, maybe try taking a screenshot or something. I don't know if I am the only one with the rain issue, but under AW I can't see exterior rain and also no exterior rain effect in the fuselage

> i'll try to remember to get one filed... am in a flight right now rebuilding my .terrasync_cache files... have stuck a sticky note to my forehead...

No problems, in that case I open it myself: https://github.com/Juanvvc/c172p-detailed/issues/738

**Comment by wlbragg** [comment]
Pushed bug-736 for this issue.

**Comment by wlbragg** [comment]
@gilbertohasnofb I can't push to c172p-detailed-liveries for some reason. It doesn't appear to be an authorization issue. I have two xcf files I wanted to put in "others". I'll keep trying and again in the morning if it won't go through tonight. But if by tomorrow morning it still isn't working, I can push the two files to this branch and maybe you could take them out of here and try to push them yourself. I first tried to push them to master then thought maybe I should push them as a new branch and let you merge them in a pr. But that isn't working either, I can't push a branch either.

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by onox** [comment]
> Pushed `bug-736` for this issue.

Your commit is on top of commits from `bug-704`. So please do the following once:

1. Make sure you are in branch `bug-736`

2. Do: `git pull --rebase origin master`

3. Verify that the commit is now on top of commits from `master`

3. You have to force push once (branch `bug-736`)

**Comment by wlbragg** [comment]
OK, let me see if I can do this now.

**Comment by wlbragg** [comment]
>You have to force push once (branch bug-736)

How?

**Comment by wlbragg** [comment]
OK, I think I got it.

**Comment by onox** [comment]
What's the status of this bug?

**Comment by wlbragg** [comment]
>OK, I think I got it.

That tells me I did what you asked me to do with the commit order.

As far as the "bug" this is suppose to be an ongoing effort (reminder) to add normal maps where appropriate to improve the look of the aircraft. I don't care if you want to close it or leave it open. Either way is fine with me.

**Comment by onox** [comment]
You did indeed fix the git issue, but I was wondering if there's going to be a PR or whether more work is needed.

**Comment by wlbragg** [comment]
I can do a PR for the rim and tire bumpmap if you want me to? Is there a deadline I need to be aware of?

**Comment by onox** [comment]
Milestones are set to 14th of May. But I do not know when exactly the core devs expect a new branch.

**Comment by wlbragg** [comment]
OK, I'll try to get something pushed in the next day or two.

**Comment by gilbertohasnofb** [comment]
@wlbragg hasn't this been incorporated already or are we still in need of improvements to the normal map?

**Comment by wlbragg** [comment]
Any new work that I know of has been incorporated (rims and tire tread). But as I said earlier in the thread, this issue is supposed to encourage us to identify areas that could use a bumpmap to improve the look of the aircraft. I would like anyone or all of us to take the time to make sure we have done all we could in this area. I doubt we have. We should look for any textures or areas of the aircraft that are not 3dimentional that should be and create a bumpmap for that area.

**Comment by gilbertohasnofb** [comment]
Ok, so I will take a look on this soonish and give my opinion.

**Comment by wlbragg** [comment]
I would like to add a relief (normals map) to the new cabin air vent, like the oil access door has.

**Comment by gilbertohasnofb** [comment]
I will try to do that then.

**Comment by gilbertohasnofb** [comment]
@wlbragg done, please do a git pull on that branch of the PR. This is how it looks:

![fgfs-screen-001](https://user-images.githubusercontent.com/5700795/37430743-fcd88f5a-27ca-11e8-847f-297eb0546181.png)

**Comment by wlbragg** [comment]
Nice, it makes these cuts that normally would blend it really pop!

**Comment by gilbertohasnofb** [comment]
I am about to push some modifications to the normal maps. I have added normal maps to:

* both air intakes on the side of the nose
* engine air intake below the nose
* interior of oil door
* dipstick screws
* fuel sump below the wings
* some more details below the wings

**Comment by legoboyvdlp** [comment]
@wlbragg @gilbertohasnofb 
One last thing, if you soom in on the door handle, it appears to have smoothing issues. I think this is the best place to report this, but if necessary I shall create a new issue.

**Comment by gilbertohasnofb** [comment]
I don't see it and can't reproduce it lego, can you post a screenshot?

**Comment by legoboyvdlp** [comment]
On the last screenshot published by you. 

But actually, it seems to be just the fuselage reflections causing a few strange angles to appear, not a mesh issue.

**Comment by gilbertohasnofb** [comment]
I think that's not the door handle but the mechanism that rotates the door. And if that's what you are talking about then it doesn't have any mesh or smoothing issues, it's just the light in that shot

**Comment by legoboyvdlp** [comment]
Sorry.... my brain doesn't work properly at this late hour :) Yes, it is the hinge, not the handle...
