### ISSUE TITLE
Instrument knobs are too short

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#751]
It seems to me that our instrument knobs (AI, altimeter, HI, etc.) are too short when compared to RL ones. See for instance:

![](http://i.ebayimg.com/images/g/xbsAAOSwSclXLWDO/s-l1600.jpg)

![](http://cdn.c.photoshelter.com/img-get2/I0000W8JoXyhdN9g/fit=1000x750/MG-8468.jpg)

![](http://i.ebayimg.com/images/g/SV0AAOSw9N1VxiWZ/s-l300.jpg)

And compare them to:

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/15138267/fb0311ea-168e-11e6-89e7-770cc2369f81.png)

**Comment by legoboyvdlp** [comment]
This is simple to fix... I was looking for something to do. I wonder if @wlbragg any cockpit mesh changes are on the way, that is, can I safely branch off master or will it conflict with other work? I'll of course, porbably be forking as I for obvious reasons do not have push access...

**Comment by wlbragg** [comment]
>cockpit mesh changes are on the way,

Right now there are two outstanding PR that deal with exterior mesh only (c172p.blend). I think all these modifications would be done in the individual instrument blends. So I think you'd be good to do this now. We are getting really close to attempting a major interior cockpit modification that will touch virtually every object on the panel and the panel itself. But the way it is going to be done shouldn't be a show stopper for you to work on this now.
Worst case scenario, I can cherry pick anything we have issues with.

**Comment by legoboyvdlp** [comment]
Just putting a  couple photographs here for reference.
![image](https://user-images.githubusercontent.com/10434911/36469920-df59dace-16e0-11e8-8dbf-fdd44e5bf292.png)

**Comment by legoboyvdlp** [comment]
It seems a heading bug is not common in Cessna's but I'll make it the same as the DG adjust knob... should work ;)

AI horizon offset and cage knobs extended slightly:
![image](https://user-images.githubusercontent.com/10434911/36470495-e80cbd6a-16e2-11e8-83c0-5598def9043c.png)
![image](https://user-images.githubusercontent.com/10434911/36470498-efcb2384-16e2-11e8-9144-7c13d72eee4f.png)

**Comment by legoboyvdlp** [comment]
@wlbragg I believe I'm finished, having done the AI, DG, VOR 1/2, ADF, ALT, and I think that's all that I noticed. Please check this and make sure there are no issues!
