### ISSUE TITLE
Move tutorials to new airport for 2016.4

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#761]
Once the base airport is decided for the 2017.1 release, we should move our tutorials there

**Comment by onox** [comment]
The core devs want to switch to a new airport every 3 months.

**Comment by gilbertohasnofb** [comment]
I don't understand why you changed this to 2017.1. As far as I know, the airports selected are:

- 2016.1: San Francisco
- 2016.2: Barcelona
- 2016.3: Rio de Janeiro
- 2016.4: undecided
- 2017.1: undecided

**Comment by onox** [comment]
You can set it to `2016.4 release` milestone if you enjoy updating all those tutorials :stuck_out_tongue_winking_eye:

**Comment by gilbertohasnofb** [comment]
Actually who often "enjoys" doing this is @dg-505 </sarcasm> :wink:

**Comment by onox** [comment]
Lets close this issue with a "wontfix" until someone volunteers and creates a PR?

**Comment by gilbertohasnofb** [comment]
Agreed.

**Comment by wlbragg** [comment]
Good luck with that!

**Comment by wkitty42** [comment]
On 11/12/2016 02:39 PM, onox wrote:
> Lets close this issue with a "wontfix" until someone volunteers and creates a PR?

i've thought, several times, to suggest bringing back the old tutorials so they 
are all available... then each one, if it can, would transfer the craft to the 
proper location/airport where they take place... this way the tutorials don't 
need to be updated for every new release and they should function properly... 
the key is if the tutorial code can move the craft to the necessary airport and 
parking position...

the only additional thing would be fixing broken tutorials due to changes in 
flightgear or fixing existing bugs found later...

**Comment by gilbertohasnofb** [comment]
@wkitty42 I don't think  I understand what you mean, but I believe the issue is as follows: people would like to have tutorials in the default tile, which changes with every release. If we don't change the location of the tutorials, the problem is that some users without terrasync will be sent to the ocean (!) but at the same time changing the tutorials every 3 months is _really_ annoying. Also tutorials must be tied to a single airport, since some of them are airport specific (taxing comes to mind).

What exactly are you proposing with the old tutorials that differ from what we have now?

**Comment by wkitty42** [comment]
On 11/14/2016 05:36 AM, Gilberto Agostinho wrote:
> @wkitty42 <https://github.com/wkitty42> I don't think I understand what you
> mean, but I believe the issue is as follows: people would like to have tutorials
> in the default tile, which changes with every release. If we don't change the
> location of the tutorials, the problem is that some users without terrasync will
> be sent to the ocean (!) but at the same time changing the tutorials every 3
> months is /really/ annoying. Also tutorials must be tied to a single airport,
> since some of them are airport specific (taxing comes to mind).
>
> What exactly are you proposing with the old tutorials that differ from what we
> have now?

i fully agree that having to change the tutorials or write new ones for each new 
airport is annoying as hell... my proposal is to stop doing that and provide the 
existing (and possibly older) tutorials but just have them teleport to the 
proper airport they are/were written for...

granted, users without terrasync may end up in the drink but we should be able 
to figure out how to deal with that... maybe listing the tutorials under their 
airport with a notice that they must already have that airport's scenery 
downloaded and installed? i dunno... it was just an idea and i may be confusing 
"tutorials" with "walk throughs" where you start at an airport and perform all 
checks and startups and then fly a specific flight plan by following the 
instructions given...

like i say, it was just an idea to keep our existing tutorials as well as the 
older ones and still have them work properly by placing the user at the proper 
airport the tutorial was written for... i don't see any reason why the tutorial 
must be at the default airport /other than/ not having the tiles already 
downloaded...

**Comment by gilbertohasnofb** [comment]
> my proposal is to stop doing that and provide the existing (and possibly older) tutorials but just have them teleport to the proper airport they are/were written for...

But isn't this exactly what we are currently doing already? Our tutorials are still based in Barcelona, and that's two versions old! But if you mean something else, I am really lost here, sorry...

**Comment by wkitty42** [comment]
no, i guess we're on the same page... i was thinking there were previous tutorials from before Barcelona... ones with flights over other areas...

**Comment by gilbertohasnofb** [comment]
A bit off topic but still about tutorials, please check this bug report out: https://forum.flightgear.org/viewtopic.php?f=25&t=31135

Can anyone reproduce it?

**Comment by gilbertohasnofb** [comment]
@onox wrote:

> Lets close this issue with a "wontfix" until someone volunteers and creates a PR?

I think we forgot to do that, so I am closing this now. Also, there is a conversation going on in the dev-list about these airport changes, it seems a lot of people lost enthusiasm with it.

**Comment by wkitty42** [comment]
On 01/25/2017 08:42 AM, Gilberto Agostinho wrote:
> @onox <https://github.com/onox> wrote:
>
>     Lets close this issue with a "wontfix" until someone volunteers and creates
>     a PR?
>
> I think we forgot to do that, so I am closing this now. Also, there is a
> conversation going on in the dev-list about these airport changes, it seems a
> lot of people lost enthusiasm with it.

the main complaint, such as it is, is mainly like "i'm working on this airport 
over here instead of one of those presented because i want to present this one 
in one of the next polls."

maybe they could do a once a year, airport change in the YYYY.1 release and then 
keep it there until the next YYYY.1 release... i'll suggest this on the list...

**Comment by gilbertohasnofb** [comment]
I honestly don't see the point of changing the default airport, be it every 3 months, be it every 3 years. 

> the main complaint, such as it is, is mainly like "i'm working on this airport over here instead of one of those presented because i want to present this one in one of the next polls."

I know a lot of people think like this but I don't get this argument, who uses the default airport anyway? I personally guess that most people select where they want to fly as oppose to simply letting the sim take them for a single location. Also, developing an airport which is not a default does not mean less people will use it, it simply mean that tile with the airport is not in the default package. Just advertise the work on the forum and people _will_ use it.

On the other hand, the importance of having the tutorial on the default tile is that people without internet connection or with TerraSync disabled will be taken to the ocean instead of the tutorial airport, and that's a much more serious thing.

**Comment by wkitty42** [comment]
On 01/26/2017 04:09 AM, Gilberto Agostinho wrote:
> I honestly don't see the point of changing the default airport, be it every 3
> months, be it every 3 years.
>
>     the main complaint, such as it is, is mainly like "i'm working on this
>     airport over here instead of one of those presented because i want to
>     present this one in one of the next polls."
>
> I know a lot of people think like this but I don't get this argument, who uses
> the default airport anyway?

i do, for one... especially when testing stuff in the sim... i'm always popping 
in at KSFO since it was the default forever... then i check the same stuff again 
by starting in each of the new default airports we've had...

> I personally guess that most people select where they want to fly as oppose
> to simply letting the sim take them for a single location. Also, developing
> an airport which is not a default does not mean less people will use it, it
> simply mean that tile with the airport is not in the default package. Just
> advertise the work on the forum and people /will/ use it.

i can understand that... now, to play devil's advocate and use your argument...

[devil's advocate]
> On the other hand, the importance of having the tutorial on the default tile is
> that people without internet connection or with TerraSync disabled will be taken
> to the ocean instead of the tutorial airport, and that's a much more serious thing.

i don't get this argument, who doesn't have an internet connection or disables 
terrasync anyway? if they didn't have an internet connection, they wouldn't have 
flightgear in the first place ;)
[/devil's advocate]

anyway, it is off topic in here... t'would be better off in the dev list where 
we've kinda carried it to already O:)

**Comment by gilbertohasnofb** [comment]
> i do, for one... especially when testing stuff in the sim... i'm always popping in at KSFO since it was the default forever... 

But if it's for testing then why does it matter if you are in SF or Barcelona or Tokyo?

> if they didn't have an internet connection, they wouldn't have flightgear in the first place ;)

That's not correct. First of all, you can download it from a second computer (e.g. at your work, university, friend's or family houses, in a cyber cafe, etc.). You can also buy FlightGear from the [official store](http://store.flightgear.org/) and have it delivered home, if your internet is too slow to download it but not for shopping.

In my view, changing the default airport causes:
a) lots of work for a lot of people both in the dev team, as well as for us here
b) some users to not have access to the tutorials, as I argued above
c) it also means very little for most people whom select where they are flying from

**Comment by wkitty42** [comment]
On 01/26/2017 07:51 AM, Gilberto Agostinho wrote:
>     i do, for one... especially when testing stuff in the sim... i'm always
>     popping in at KSFO since it was the default forever...
>
> But if it's for testing then why does it matter if you are in SF or Barcelona or
> Tokyo?

because some problems can show in some places and not others... consider flying 
around paris, france, compared to san francisco... or atlanta compared to 
dallas-ft. worth...

>     if they didn't have an internet connection, they wouldn't have flightgear in
>     the first place ;)
>
> That's not correct.

i'm not gonna argue this... this isn't even the proper venue for it ;)

**Comment by gilbertohasnofb** [comment]
> because some problems can show in some places and not others... consider flying around paris, france, compared to san francisco... or atlanta compared to dallas-ft. worth...

But then how rotating a default airport every 3 months would help? To truly troubleshoot something that may be related to location, you must select a different one while testing. If a problem appears in 2016.4 but not in 2016.3, it could be because of the different default airport, but much more likely it will be for one of the many other differences between these versions.

> i'm not gonna argue this... this isn't even the proper venue for it ;)

Fine by me :+1:

**Comment by wlbragg** [comment]
I wish we had someone that would commit to changing the location of the tutorial every cycle. Is it really that hard code wise or is there considerable text that needs to be re-worded? If I knew this "new airport" cycling was going to stay consistent and continue on infinitum, i would consider taking a closer look at the tutorials and figuring out a way to automate as much of the changes as possible. I'm sure it could be done that way.

**Comment by wlbragg** [comment]
Also, as long as we continue to change the default airports, it is important to make the flagship tutorials match that airport.

**Comment by gilbertohasnofb** [comment]
I don't know exactly how much, @dg-505 would you care to give your opinion since you have been handling those?

> I wish we had someone that would commit to changing the location of the tutorial every cycle.

Yeah, that would be a solution, but a) so far no one volunteered to that and b) IMO the project would be better if this person would work on some of the issues or implement new features

By the way, Stuart just wrote in the list:

> We could just ship a 1x1 degree tile for the c172p tutorials, to minimize the impact.

Now that would be an ideal solution in order to keep the default airport changing as much as they want. If Barcelona is not in the border of a tile, then having a 1x1 wouldn't be a problem at all as far as tutorials are concerned. Does anyone know about it?

**Comment by gilbertohasnofb** [comment]
> When we ship the barcelona tile with the aircraft it is just a matter of time until related reports/complaints pop up on the forum.

Maybe I am misunderstanding something, but the tile would _not_ be shipped with the aircraft, it would be included in FGDATA. That is, FG would have two "default" sceneries: a _de facto_ default which rotates every three months and gives the name to the release, and a fixed one (Barcelona looks great!) which can be used for anything that needs a fixed scenery, such as the tutorials.

**Comment by dg-505** [comment]
>  it would be included in FGDATA

Sounds great :+1:

**Comment by gilbertohasnofb** [comment]
@dg-505 do you happen to know what is the size of the Barcelona tile? The discussion seems to have died in the dev-list, so I was thinking that if the tile is not particularly large it could be used as one more argument as to add it in addition to the default airport tile which will keep rotating at each version.
