### ISSUE TITLE
Propeller disk looks red under certain circumstances

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#771]
Propeller disk looks red under certain circumstances: try loading the plane in the weather preset "low pressure system" and advance the time from dusk to evening by holding the key `t`, advance the time towards evening. At a certain point, the back of the propeller disk look red, while the front looks normal. See:

![fgfs-screen-003](https://cloud.githubusercontent.com/assets/5700795/15629502/5cb19800-251a-11e6-8bd1-3a9b708e06c7.png)

![fgfs-screen-005](https://cloud.githubusercontent.com/assets/5700795/15629518/aa5f3cd8-251a-11e6-8949-f04ed4afd93a.png)

**Comment by legoboyvdlp** [comment]
I also noticed this last night, flying in the dark, but I remembered seeing a bug report about it, and thought it had been brought up by wlbragg suring his mesh fixes and might have been fixed already... was a little wrong ;)

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp thanks for the info. Have you observed this with other propeller aircraft? I barely fly anything else these days (heck, I barely fly at all!)

**Comment by legoboyvdlp** [comment]
I know the feeling :grinning: 
I actually haven't, but I haven't been particularly looking out for it.

**Comment by gilbertohasnofb** [comment]
Thanks. I will post a question about this in the forum.

**Comment by gilbertohasnofb** [comment]
Here is a link: https://forum.flightgear.org/viewtopic.php?f=4&t=33962

And I could _not_ reproduce this in a quick test with the c182s

**Comment by legoboyvdlp** [comment]
FWIW, I observed the bug from the cockpit, using real time at about dusk, real weather (quite stormy).

**Comment by gilbertohasnofb** [comment]
@wlbragg I think this has to do with our 3D model, I tried a couple of other propeller aircraft and none had this issue. Could we compare our propeller to the c182s or c152? Those do not get red.

And by the way, our propeller disk could do with some improvement. Would it be possible to have the front of the disk mapped to a different texture than the back? And could the front disk depend on livery? This way I can try to reproduce how the propeller in each livery looks like.

**Comment by wlbragg** [comment]
>I think this has to do with our 3D model, I tried a couple of other propeller aircraft and none had this issue.

I told you when we switch to the c182s material settings and now their propblur model that I thought the issue corrected itself.

You said no. Well I just tried your weather settings and the time of day at the location you suggested and got the same results you did. But guess what, I get the same thing with the c182s!

In my case it corrected it in conditions where it was readily apparent before the changes. But not in all cases as in the settings and location you suggested. But that holds true with other aircraft as well. So I am of the opinion ours "IS" now the same as the others.

Unless you can suggest a different aircraft and scenario I can try to disprove my current hypothesis?
Only then will i have something to compare against.

What I am trying to say is I am now seeing identical lighting results between the c172p and the c182s.

**Comment by wlbragg** [comment]
Now I am not saying that I can't try a few things such as the ambient settings in Blender (I'm experimenting with that now).

**Comment by wlbragg** [comment]
This is the same results with the c182s as I get with the c172p.
![fgfs-screen-005](https://user-images.githubusercontent.com/11069680/37879666-f825ebb8-3041-11e8-81c6-e95297df7fb7.png)

**Comment by wlbragg** [comment]
@gilbertohasnofb 

Please try this .ac and let me know what you think. If you think it works for our issue, make sure it works in all other lighting typical lighting conditions.
https://www.dropbox.com/s/5k1a83btrrc3bls/c172p.ac?dl=1

**Comment by gilbertohasnofb** [comment]
> You said no. Well I just tried your weather settings and the time of day at the location you suggested and got the same results you did. But guess what, I get the same thing with the c182s!

I just did the same test and all aircraft seems to be affected somehow. Apologies for the misinformation, I must have messed up my prior test with the c182s. Both c182s and c150 get the yellow -> red -> black propeller colour transition at sunset time:

![fg-0](https://user-images.githubusercontent.com/5700795/37880019-d9a1e632-3079-11e8-959d-4d7377128948.jpg)
![fg-1](https://user-images.githubusercontent.com/5700795/37880020-d9cf4e4c-3079-11e8-85a4-139521b9d31f.jpg)

I also tested the dc3, and though its propeller does NOT show those hues, the cockpit and cabin windows do! See:

![fg-2](https://user-images.githubusercontent.com/5700795/37880033-f53c247a-3079-11e8-91b3-70bc16a78a55.jpg)
![fg-3](https://user-images.githubusercontent.com/5700795/37880034-f55389ee-3079-11e8-9117-c7dafd09fb97.jpg)
![fg-4](https://user-images.githubusercontent.com/5700795/37880035-f58ddaf4-3079-11e8-891a-c06296961cac.jpg)
![fg-5](https://user-images.githubusercontent.com/5700795/37880036-f5a72838-3079-11e8-905b-267c7a4930b1.jpg)

This is starting to look like some issue with ALS, don't you think?

> Please try this .ac and let me know what you think.

Will do it now.

**Comment by gilbertohasnofb** [comment]
@wlbragg This ac model you sent me seems to solve 99% of the problem (just a hint of red is left, nearly imperceptible). But the wing edge seems to have some issues now:

![fgfs-screen-001](https://user-images.githubusercontent.com/5700795/37880057-75b7062e-307a-11e8-97c6-437db9fec098.png)

**Comment by wlbragg** [comment]
What branch did you stick that .ac into  to test it?

**Comment by gilbertohasnofb** [comment]
Oh, I inserted it in the master, sorry

**Comment by wlbragg** [comment]
Before I forget, something that would be really cool if we can locate it is engine sounds from the 180 hp equipped aircraft. I wonder how different the sound would be?
I am assuming these sounds are from a 160 hp aircraft?

OK, back to the lighting. What I changed is the rgb values in the .ac file, line 19
~~~
MATERIAL "FastProp" rgb 0.0000 0.0000 0.0000  amb 1.0000 1.0000 1.0000  emis 0.0000 0.0000 0.0000  spec 0.5000 0.5000 0.5000  shi 12 trans 0.9250
~~~
I set them to from 1.0000 1.0000 1.0000 to 0.0000 0.0000 0.0000. You can mess with it and see if you like something else better. 
I assume that yes this lighting issue is an ALS "feature". I don't think it would be problematic if it only did it while the sunlight was affecting the environment. It seem like it does this well past when the sunlight would be having any influence, but I don't know that for sure.
I also don't know what exactly the .ac's rgb values are used for but it appears to be how much effect the scene lighting is allowed. I don't think I would want to change this for most objects but just the prop blur, maybe. I simply don't know the ramifications though, if it will cause other lighting issues with the propblur under other lighting conditions?

**Comment by gilbertohasnofb** [comment]
> something that would be really cool if we can locate it is engine sounds from the 180 hp equipped aircraft. I wonder how different the sound would be?
> I am assuming these sounds are from a 160 hp aircraft?

I am also assuming that's a 160hp. If we ever find a source for the 180hp, I would definitely use it. But I suspect that the main difference is the higher rpm at same throttle settings, and that's compensated in volume and pitch of the sounds (engine sound pitch and volume varies with RPM). In the end, the difference would not be too big I think.

> I assume that yes this lighting issue is an ALS "feature". I don't think it would be problematic if it only did it while the sunlight was affecting the environment. It seem like it does this well past when the sunlight would be having any influence, but I don't know that for sure.

Exactly.

> You can mess with it and see if you like something else better.

I think these are working well.

> I simply don't know the ramifications though, if it will cause other lighting issues with the propblur under other lighting conditions?

Let's keep our eyes opened then, in the worst case we can simply revert this commit.

**Comment by wlbragg** [comment]
OK, I'll add it to the open PR and as far as I am concerned that PR is finished. We may want to let @onox review it and merge it.

**Comment by gilbertohasnofb** [comment]
@wlbragg Can you confirm we merged that fix for this issue already and therefore we can close this?

**Comment by wlbragg** [comment]
Yes, this is done. Except, every time we push a modification to the Blend we have to manually change the RGB value of the FastProp material setting to 0's. I of course forgot to do that after my last Blend edit and .ac change. If there is a way to set the RGB value to 0 in the blend itself, this would be much easier. I would imaging there is but I don't know how yet.
I just pushed a new branch to get rid of the color in the propblur. That is the only change. rgb-two-zero

**Comment by wlbragg** [comment]
I figured it out. It will always stay set to 0, 0, 0 now unless someone changes it.
