### ISSUE TITLE
Better propeller sound 

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#779]
Create better propeller sound as the `wasp.wav` isn't really a very good quality sound

**Comment by onox** [comment]
@algefaen Are you able to record the engine of c172p? See the closed PR #780

**Comment by gilbertohasnofb** [comment]
@algefaen That would be great. If you can, please try the following: try to record a long take without talking and minimizing any other noises so that the engine is as pure as possible. Also, one take at idle and one at higher throttle would be great (keep the RPM as constant as possible during a take). The longer the takes the easier it is for me to loop them. Also feel free to record any other sounds that might be useful (door banging, switches, etc.), I can always use them as reference.

**Comment by algefaen** [comment]
I'll try to get some recordings next time! I can try to get a complete set with in-cockpit, outside, starting, low rpm, high rpm, shutting down, etc... Just don't hold your breath, it'll be at least a couple of weeks.

**Comment by gilbertohasnofb** [comment]
@algefaen absolutely no rush at all and many thanks!
