### ISSUE TITLE
Why set parking brake on damaged left/right gear?

### ISSUE THREAD

**Issue by wlbragg** [c172p-team/c172p-detailed#784]
``` xml
 <!-- A broken gear operates as a parking brake -->
 <property>/fdm/jsbsim/gear/unit[1]/broken</property>
 <property>/fdm/jsbsim/gear/unit[2]/broken</property>
```

I ask because we extend contact points 7 and 8 to be the WOW points and they have their own friction factors?

**Comment by onox** [comment]
> because we extend contact points 7 and 8

Extend? Do you mean the z-position? Where is that hapenning?

**Comment by wlbragg** [comment]
Yes, in c172p-ground-effect.xml. I was implementing the j3cub's damage logic and noticed both the brake being set and contact points 7/8 z-pos being moved.

I think the brake is too hard but the contact point may be too soft (ie:too much and too little friction).

I also remember before the FDM refactoring that I used the z-pos of a structure point to cause the extra friction needed.

**Comment by wlbragg** [comment]
@onox, @gilbertohasnofb 
I verified that if you comment out the condition
~~~
 <!-- A broken gear operates as a parking brake -->
  <!-- 
<property>/fdm/jsbsim/gear/unit[1]/broken</property>
 <property>/fdm/jsbsim/gear/unit[2]/broken</property>
 -->
~~~
at line # 458 in ground-effect.xml the aircraft still skids to a stop. it appears to have roughly the same friction either way so I think we could safely remove the condition and allow the contact points to do their job. 
If one of you want to test this and verify your OK with the condition being removed then we can close this and I will add it to the current PR.

**Comment by onox** [comment]
@wlbragg Looks OK to remove the conditions :+1:

**Comment by wlbragg** [comment]
This is finished and pushed to #973 PR
