### ISSUE TITLE
absolute position for instruments in individual .ac files

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#790]
Thorsten wrote:

> That's caused by translating/rotating things into place rather than having them absolutely positioned in the ac file, not by including a separate ac file.

@wlbragg wrote:

> I guess I never really understood that and it is really helpful to know this. So technically in the c172p's case, all the eternal .ac instruments it uses (the ones that are local anyway), could be positioned absolutely in their ac file and then be included in the shadow effect to get a better visual. It would be some work but might be worth it. It for sure would be worth understanding this on any new build and start out using this method so you can include the entire instrument panel in your effects, good to know.

I personally think it would be really worth to do it, so that all instruments can respond properly to the effects. But maybe, if we are still considering fixing https://github.com/Juanvvc/c172p-detailed/issues/6 and https://github.com/Juanvvc/c172p-detailed/issues/216 (which are fundamental to have a properly looking cockpit IMO) then we maybe should wait for those before adjusting all instruments.

**Comment by wlbragg** [comment]
Yes, for sure we would only want to do this once.

**Comment by gilbertohasnofb** [comment]
:+1: So let's put this on hold for a bit

**Comment by dany93** [comment]
_(I don't know if this is the best place...)_
I noticed that the 3D magnetic compass indication is wrong.
About 180° error near 90° and 270° mag heading (map),
Pretty well at 0° and 180° mag heading.

**Comment by gilbertohasnofb** [comment]
@dany93 I don't think this is the place for that, this issue is just about the position of the instrument models in the .ac file. I will open a new one with your report.

**Comment by dany93** [comment]
I had the impression that the code change was in [Move compass to absolute position....](https://github.com/c172p-team/c172p-detailed/commit/20fdd9612decd95e34f4bbe705928e26736035ff).
Hence this place for my message. I don't know if it can help, or if there is no relation (it can be a mistake on my part, then sorry).

**Comment by gilbertohasnofb** [comment]
@dany93 I see. Nevertheless, @wlbragg is already working on a fix so this should be back to normal soon. Thanks!

**Comment by wlbragg** [comment]
@gilbertohasnofb 
Yes
