### ISSUE TITLE
small 3D issues with the external fuselage

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#860]
These are a couple of minor 3D issues that we currently have with our external fuselage:

- While testing the tutorials, the camera angle for removing the tie-down in the tail of the plane on the preflight tutorial shows a possible problem with the 3D model, see:

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/20261406/e8d43086-aa5d-11e6-94ce-d644011e802b.png)

On the left side of the purple circle we can see through the fuselage! (click on the image to open it in higher resolution to see what I am talking about)

- problematic UV mapping near the aircraft nose in the left side, colors look really strange on all liveries:

![fg-0](https://cloud.githubusercontent.com/assets/5700795/20360200/12c1a6ae-ac33-11e6-8660-d770d5ef2cc0.jpg)

![fg-1](https://cloud.githubusercontent.com/assets/5700795/20360201/12c675d0-ac33-11e6-8b3b-13f933b42d08.jpg)

- the rudder shape is a tiny bit wrong, it is missing a half-circle hole, see:

![rudder](https://cloud.githubusercontent.com/assets/5700795/20360322/9259e5a2-ac33-11e6-86f9-0e9f0a2be341.jpg)

some other references:

![](https://upload.wikimedia.org/wikipedia/commons/e/ee/Cessna_172S_Skyhawk_SP_N5204A_tail_1.JPG)

![](http://truepcgaming.com/wp-content/uploads/2014/07/A2A-Accusim-Cessna-172-Review-1.jpg)

**Comment by gilbertohasnofb** [comment]
The post above has been edited. 

@wlbragg would you maybe be interested in taking a look at this issue? These should be quite minor fixes I suppose.

**Comment by wlbragg** [comment]
Yep, I'll look at it when I do the control wheel lock.

**Comment by gilbertohasnofb** [comment]
👍 Thanks! Let me know if I can help somehow

**Comment by gilbertohasnofb** [comment]
I am not sure if this has been reported before, but there are some issues with the bottom part of the fuselage:

![fgfs-screen-001](https://user-images.githubusercontent.com/5700795/36034101-e0dedc30-0daa-11e8-88a2-b7d90be131d7.png)

Is that a 3D model, UV mapping or effect problem? Perhaps it could be added to this issue or maybe we should create a new issue for it -- opinions?

**Comment by wlbragg** [comment]
Wow, I am looking at the Blender model VS the c172p.xml and we do have an issue. I actually don't understand how the UV mapping of the baggage door is even working. There was an addition of
baggagedoorhandle
baggagedoorinterior
baggagedoorexterior
and the removal of 
baggagedoor

yet the XML only has 
baggagedoor

this shouldn't even be working.

Anyone else want to verify they show the same thing in the current master on GIT?

**Comment by wlbragg** [comment]
I don't know or remember who did the baggage door, but it was wrong. I am fixing it but would feel a lot better if I knew if it was my error early on or someone else has been in the Blend. If it is others in the Blend they need to be aware of everything that has to happen to add, remove or edit objects. There is effect definitions and livery definitions that have to be modified.
I'm just now noticing other objects that don't look right. I am still investigating the radiator intake.

**Comment by wlbragg** [comment]
That was the same issue for the object-name radi_box. It was never defined in the effects or livery.

**Comment by wlbragg** [comment]
Who added the radi_box? If it was me it was before I knew how some of this worked. We have z-fighting issues with it.
Please, if anyone else is responsible for this stuff they need to be aware of some of the issues so it doesn't happen anymore. I may be guilty of some of it in the past, but I do know what I am doing now and we have some issues here.

**Comment by wlbragg** [comment]
OK, I pushed a branch Issue680 that corrects a bunch of really bad mesh problems at the tail of the aircraft and the radiator area. The mesh issues in the tail (the seams you could see near the tie-downs) were done a long time ago and required some major mesh repair.
Please review closely.

**Comment by gilbertohasnofb** [comment]
@wlbragg many thanks for taking a look at this! I am afraid I am useless to check the 3D stuff in Blender, but I will gladly check the branch `Issue680` in the sim soon.

**Comment by wlbragg** [comment]
FYI: the tail of the fuselage had major vertex issues. There were vertexes that were merged that shouldn't be. Ones that were completely out of place. It was a mess. But it is all cleaned up now so a visual inspection of the model in the sim would be fine. I think I can also model the semicircle at the base of the rudder before we merge.
