### ISSUE TITLE
setting throttle via properties gets immediately reset.

### ISSUE THREAD

**Issue by tigert** [c172p-team/c172p-detailed#864]
So I was playing with an Arduino the other day, and wired a potentiometer to adjust the throttle via the example here:

  http://wiki.flightgear.org/Howto:Use_Arduino_with_FlightGear

However, it did not work with the C172p, and I think some of the Nasal logic we do the more complex stuff with seems to interfere and resets the value. 

You can view the issue without an arduino by going to the browser-based gui and seeing the properties of
   
   /controls/engines/engine/throttle

You can click the little picture icon next to the field to see a graph representation of the value. IF you manually type in a value of, say, 0.42 it gets quickly reset to 0 (or whatever you set the throttle via keyboard command to)

With other aircraft this works correctly though.

**Comment by tigert** [comment]
I guess we should either document a correct property to adjust. or avoid resetting the controls properties from code?

**Comment by onox** [comment]
Aren't we using engine number 2? So that would be
/controls/engines/engine[2]/throttle?

On Wed, Nov 16, 2016 at 10:23 AM, Tuomas Kuosmanen <notifications@github.com

**Comment by onox** [comment]
Oh, we're actually using some other property:
/controls/engines/current-engine/throttle

**Comment by onox** [comment]
@tigert I answered your question in my previous comment. Hopefully that fixes the issue for you. Going to close this issue, but you can always reopen it if you want (or comment if you need permissions for reopening).
