### ISSUE TITLE
More realistic bush wheels and tires

### ISSUE THREAD

**Issue by wlbragg** [c172p-team/c172p-detailed#875]
The bush tire and rim are not realistic. The tire should be a slick and the rim should be closer to the size of the default tire and could stand a better texture appropriate to a bush tire.

@gilbertohasnofb if you want to research the look of a bush tire and rim and make the texture, I'll apply it and fix the rim size. Or I can also research it and provide a picture for reference.

**Comment by gilbertohasnofb** [comment]
> research the look of a bush tire and rim and make the texture, I'll apply it and fix the rim size. Or I can also research it and provide a picture for reference.

:+1: This weekend I will be quite busy though, but I can work on it very soon. As for the picture, do you mean something more like this?

![](http://memberfiles.freewebs.com/38/32/79753238/photos/undefined/DSC_0033%20(2).JPG)

**Comment by wlbragg** [comment]
Yep!

**Comment by gilbertohasnofb** [comment]
@wlbragg I had a look at this issue, an I am not sure this is only a matter of texturing. It seems to me that the rim is too large and the "inner circle" of the tire is too small. Also, I came across some images of 172s in bush configuration, and the rim does look quite similar to ours:

![](http://www.bushair.co.za/Bush%20pilots%20flyin%202008/3D-101taxi.jpg)

![](http://www.john2031.com/alaska_bush_planes/aircraft_photos_5/nikiski/22_n8587b.JPG)

![](http://www.john2031.com/cessna/175/pictures/55130.JPG)

So isn't this a case of improving the 3D model a bit, resizing the rim and playing with UV-map?

**Comment by wlbragg** [comment]
Yes, I planned on resizing the rim.

**Comment by gilbertohasnofb** [comment]
@wlbragg :+1: If modelling alone doesn't cut it, then just let me know about what you'd need to be done with the textures, ok?

**Comment by wlbragg** [comment]
I'm looking at this now. I wonder if we shouldn't eliminate one of the bush wheel sizes? If agreed I would like to get a consensus of what size the only bush wheel should be?

**Comment by wlbragg** [comment]
I suppose for ease of modification it would be to keep the 36", the ones we use with skis.
It's not a requirement to eliminate a size, actually in the long run it would be more work removing the code than to resize another set of wheel. It's something I have been thinking about for awhile. Maybe users like having the choice of two sizes?

**Comment by wlbragg** [comment]
36" wheels finished, comments?
![wheels](https://cloud.githubusercontent.com/assets/11069680/21653257/d50c5958-d275-11e6-84f4-c878976b7d7a.jpg)

**Comment by gilbertohasnofb** [comment]
> I suppose for ease of modification it would be to keep the 36", the ones we use with skis.
It's not a requirement to eliminate a size, actually in the long run it would be more work removing the code than to resize another set of wheel. It's something I have been thinking about for awhile. Maybe users like having the choice of two sizes?

I would actually vote for the smaller bush tires, but I would rather keep them both if that would be possible. Are these modifications too much work?

> 36" wheels finished, comments?

Looks good to me, but I would perhaps make the corners a bit rounder. While regular wheels look very much like cylinders, I have the impression from photographs that the bush tires look different with no edge, see:

![](http://3ukr694671p02fhcme3a1bsaiek.wpengine.netdna-cdn.com/wp-content/uploads/2016/03/Ultralight-Bushwheel-Flight-Test-2.jpg)

![](http://www.legend.aero/images/airstreak.jpg)

**Comment by wlbragg** [comment]
OK, not like the tires immediately above, more like the tires in the first image on this page. Although with a different texture it might look closer to the one above.
This is about as good as I can get it. Still need to do 26" and then the damage model wheels for both 26" and 36".
I'm good with keeping both 26" and 36", a little more work, but not really when you take into consideration where all in the code you'd have to remove stuff to limit it to one size.
![bush1](https://cloud.githubusercontent.com/assets/11069680/21668930/7ba91a8e-d2cc-11e6-9463-e6b90e8ad5c0.jpg)
![bush2](https://cloud.githubusercontent.com/assets/11069680/21668931/7d77d4ea-d2cc-11e6-8f69-b11342fa2dc9.jpg)

**Comment by gilbertohasnofb** [comment]
@wlbragg I think it looks good :+1:

> I'm good with keeping both 26" and 36", a little more work, but not really when you take into consideration where all in the code you'd have to remove stuff to limit it to one size.

Ok then! :smile:

**Comment by wlbragg** [comment]
Cool, I actually just noticed something about the images we're using to model these tires. The two Piper pictures immediately above show more of a slick balloon tire where the first image of a "like" aircraft use a meatier, flatter profile, treaded tire, more like what I finally managed to model. So I think we are good to go.
I'll try to get the rest done next week, I'm fighting a time squeeze with real life stuff. :disappointed:

**Comment by wlbragg** [comment]
26" are finished. Please check them out and if they are OK I can move onto the damaged models for both 26 and 36 wheels.
![bush26a](https://cloud.githubusercontent.com/assets/11069680/21693270/e62eb674-d345-11e6-8a7e-2898fee24bfc.jpg)
![bush26b](https://cloud.githubusercontent.com/assets/11069680/21693271/e6341420-d345-11e6-8cd1-4a6bdeafb0f9.jpg)

**Comment by gilbertohasnofb** [comment]
@wlbragg Looking really good!

**Comment by onox** [comment]
Looks better 👍 Could the color made a bit darker perhaps? The tires have always been a bit too grey. If I use the color picker in gimp I get something like 33, 46, 43 (RGB) instead of 20, 20, 20 for the photo's in https://github.com/c172p-team/c172p-detailed/issues/875#issuecomment-263592576

**Comment by gilbertohasnofb** [comment]
> Could the color be made a bit darker perhaps?

Sure, I can correct that in the same branch (@wlbragg did you push your working branch yet?). But that will also affect all other tires, of course.

**Comment by onox** [comment]
@wlbragg Not sure if there's a need for it, but do you think it would be nice to add bump mapping to the tires like the p51d does it?

**Comment by onox** [comment]
You'll get something like this:

Enabled:
![fgfs-screen-019](https://cloud.githubusercontent.com/assets/3361585/21698362/e7f7cddc-d396-11e6-80e4-f8957464884b.png)
Disabled:
![fgfs-screen-020](https://cloud.githubusercontent.com/assets/3361585/21698363/e7fab146-d396-11e6-8fed-dd15d7de2d9e.png)

**Comment by wlbragg** [comment]
>Sure, I can correct that in the same branch (@wlbragg did you push your working branch yet?). But that will also affect all other tires, of course.

Yes, I pushes the damage blend. It uses the same texture as the main blend fuselage.png I think it is.

>@wlbragg Not sure if there's a need for it, but do you think it would be nice to add bump mapping to the tires like the p51d does it?

Yes, we already do, or did, but it will need to be checked (I forgot about it).
![fuselage-normal](https://cloud.githubusercontent.com/assets/11069680/21699791/f26f74e2-d362-11e6-8618-e373c58fd2c5.png)

**Comment by wlbragg** [comment]
If we darken them maybe we could also add some lighting and reflection.

**Comment by wlbragg** [comment]
Branch https://github.com/c172p-team/c172p-detailed/tree/bug-875

**Comment by gilbertohasnofb** [comment]
@wlbragg Ok, so I will try to darken the texture a bit. I am travelling now but once I am back home on Sunday I will take a look at it.

**Comment by gilbertohasnofb** [comment]
> we could also add some lighting and reflection.

do you mean on hardcoded on the textures or as some sort of effect? If the former, then I can do that as well

**Comment by wlbragg** [comment]
No, I meant effects, not the texture itself.

**Comment by wlbragg** [comment]
>No, I meant effects, not the texture itself.

It's already applies through bumpspec.eff. Maybe I need to look at the lighting settings in blender after you darken the texture.

**Comment by gilbertohasnofb** [comment]
Ok all, so I modified the textures of the tires to make them look darker and I pushed it to branch `bug-875`, so @wlbragg please do a `git pull` before continuing. here is how it's looking now:

![fg-3](https://cloud.githubusercontent.com/assets/5700795/21802178/f3d27896-d724-11e6-990c-087a8b504e0f.jpg)

I think this is much better.

And by the way, @wlbragg, I noticed that the UV map of the bush tires have a tiny problem, hardly perceptible but which we could fix on this PR. First, I wanted to make sure which textures were mapped in to the tires, so I made a test alteration to the `Models/fuselage.png` file:

![fuselage](https://cloud.githubusercontent.com/assets/5700795/21802302/7727893e-d725-11e6-9fa1-6a70f36eb6cd.jpg)

So in the sim I could confirm that that single texture affects tires of all liveries and all variants. The problem is with the chrome ring in the tire. I used a yellow colour to mark it, but I did leave enough chrome around to see what happened. And here are the results:

![fg-0](https://cloud.githubusercontent.com/assets/5700795/21802339/a60942b0-d725-11e6-9c81-f0dad31a015f.jpg)

![fg-1](https://cloud.githubusercontent.com/assets/5700795/21802341/a60b36f6-d725-11e6-8a56-61205caed25c.jpg)

![fg-2](https://cloud.githubusercontent.com/assets/5700795/21802340/a60a399a-d725-11e6-9956-3d0fd5df4997.jpg)

So notice that the default tires map the yellow circle into a perfect circle in the sim, while the other variants map it in a distorted way. Do you think you could take a look at that?

**Comment by wlbragg** [comment]
@gilbertohasnofb you are showing the old bush tires, not the new ones? So does that apply after changing to the new bush tires?
I'm not sure I am following the issue.
I see that the yellow is no longer uniform around the entire rim, is that what your looking at?
But it is with rims and tires that are no longer being used, so does it still do that with the new bush tires?

**Comment by gilbertohasnofb** [comment]
> you are showing the old bush tires, not the new ones? So does that apply after changing to the new bush tires?

Oh, I am so sorry for the confusion! It seems my first tests were done in the master branch, and only later I went to `bug-875`. Please ignore it as everything I wrote about it above, as it is looking perfect now:

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/21811591/8626d8b0-d750-11e6-877e-9ddf270f9f65.png)

So if you think the tire colour (not the pink, but the black one :wink: ) is fine now, then I guess that was all I needed to do here, correct?

**Comment by wlbragg** [comment]
Yes, I think we're good. Now I need to do the damage models. 

@onox, you think I should go ahead and bring the damage gear models over to the main blend/.ac. I question doing this as my testing clearly shows and was somewhat verified that the act of switching views, interior to exterior, or forward view to side view (down the wing), or undamaged to damaged, is what is causing the delay. Supposedly it causes a texture change even though the texture is the same one currently being used? I still don't fully understand what is going on here.

**Comment by onox** [comment]
What causes the delay when you damage your gear? Is it the loading of the .ac file (`Models/Effects/damage/c172p-damage.ac`)? Or the textures? The .ac file uses the same .png files as the main `c172p.ac` file: `fuselage.png`, `lights.png`, and `wing.png`. So texture change should not be it?

**Comment by onox** [comment]
@wlbragg `c172p-damage.ac` also contains the many damaged/broken wings. Maybe we should start with #592 by forgetting about the damaged/broken wings, splitting up the regular wing into 3 parts, and then make damaged variants of the outer parts?

**Comment by onox** [comment]
@gilbertohasnofb I noticed btw that ground equipment cannot be hidden after you have enabled them. Can you reproduce it?

**Comment by gilbertohasnofb** [comment]
> I noticed btw that ground equipment cannot be hidden after you have enabled them. Can you reproduce it?

No I can't, I can toggle them on and off, no problems. Are there any more steps to reproduce this?

**Comment by onox** [comment]
No

**Comment by onox** [comment]
I just open ground equipment and enable something. When I try to disable it, the object remains visible.

**Comment by gilbertohasnofb** [comment]
Hmm, I see no problems here using the ground equipment dialog to enable/disable them. Can anyone else try to reproduce this? @wlbragg ?

**Comment by wlbragg** [comment]
I get the same thing as @onox, once I enable something in ground equipment I can't disable it. I am in bug-875

**Comment by wlbragg** [comment]
>What causes the delay when you damage your gear? Is it the loading of the .ac file (Models/Effects/damage/c172p-damage.ac)? Or the textures? 

According to everything I have seen, heard and tested it is the loading of the texture. Emilian suggested it is the texture that unloads and loads on demand and is causing all the delay. The .ac mesh is loaded using the model/path statement regardless of a conditional call. I think I can verify that in the Shuttle, J3Cub and the c172p. It is the texture. But, even that isn't straight forward. In the J3Cub, the interior and exterior are on the same texture sheet, minus a few smaller textures. Emilian pointed out J3Cub is using a 4096 sheet VS the 2048 of the c172p, thus the extra loading time. What I don't understand is in the J3 if I change view from forward to side, down a wing, I get a huge delay while it loads? Also another when switching to an exterior view. Another when equipment changeover and yet another with damage model, all using the same texture sheet. So it isn't obvious as to what internally is going on in the code.
The only thing I know is I mitigated it all by using a pre-load of every view and model object. Emilian suggested even that won't hold over time as the texture load/unload on demand takes place. Although I haven't seen that yet.

**Comment by wlbragg** [comment]
From my testing with the pre-loading, putting the .ac's together doesn't change anything, unless possibly the texture sheet loading would be handled differently in that case. Or unless I had other variables I didn't account for or take into consideration. I guess we need to test that with a few controlled tests.
