### ISSUE TITLE
Update reflection shader

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#876]
change reflection shader to the one with real fresnel effect

See: https://github.com/HHS81/c182s/issues/152

**Comment by wlbragg** [comment]
Our original reflect settings
![fgfs-screen-004](https://cloud.githubusercontent.com/assets/11069680/20460726/f451a9d0-aeb2-11e6-9001-c75bd40f79c2.png)
Same new reflect settings and effect as c182s 
![fgfs-screen-002](https://cloud.githubusercontent.com/assets/11069680/20460727/fa680634-aeb2-11e6-81fc-bed30fa83550.png)

**Comment by gilbertohasnofb** [comment]
It looks fine but I am not too sure if that was an improvement or not. The whole livery looks much brighter while the horizontal surfaces are not reflecting more light. See for instance these two images by Heiko (please open them side by side and switch between them to see the differences):

![](https://cloud.githubusercontent.com/assets/12649375/19746924/ed5c61c0-9bd8-11e6-870f-f62144969922.jpg)

![](https://cloud.githubusercontent.com/assets/12649375/19746931/f6980b4a-9bd8-11e6-934d-8830b168d1fe.jpg)

Do you see that the only difference between them is that the wings and elevator reflects more light from the sky? For me that's the really wow effect of this. But that's just my 2 cents, I still didn't have the chance to test this in the sim so I have no idea how it looks in real time, ok?

**Comment by HHS81** [comment]
@wlbragg  the trick is to set `<fresnel-factor>1.0</fresnel-factor>`to a higher value than 0. I set the value to 1.0 in the example above.

**Comment by wlbragg** [comment]
@HHS81 in what branch and file name are you using the new reflection settings?

**Comment by wlbragg** [comment]
OK I figured it out, is this better :laughing: 
![fgfs-screen-006](https://cloud.githubusercontent.com/assets/11069680/20525214/07d7d808-b084-11e6-9f24-f9ca4d5403da.jpg)

**Comment by gilbertohasnofb** [comment]
@wlbragg It's difficult to say with this picture above given the green uniform colour, but is this effect applied similarly to the c182? I notice there how the wings and horizontal stabilizers are reflecting the blue from the sky while the rest of the fuselage is not, and in the picture above seems quite uniform. But I guess I need to wait and see it applied to a livery.

**Comment by wlbragg** [comment]
@gilbertohasnofb the above image was actually an accident, but it did show a major increase in reflectivity.

Below is as far as I have gotten with the effect. I think I need to wait for the wiki to be updated or more instruction from @HHS81 

![fgfs-screen-007](https://cloud.githubusercontent.com/assets/11069680/20526589/4ecd8d10-b08a-11e6-9183-b13d3be21296.png)
![fgfs-screen-010](https://cloud.githubusercontent.com/assets/11069680/20526592/50f02a26-b08a-11e6-8f07-fe04fe9a9185.png)

**Comment by HHS81** [comment]
@wlbragg I  need to look into your .eff-file to see what's wrong

**Comment by wlbragg** [comment]
After fiddling with the reflection values for an hour or so I managed to get something a little more plausible. However as of right now the fresnel-factor doesn't seem to be doing anything.

![fgfs-screen-003](https://cloud.githubusercontent.com/assets/11069680/20548123/5b9ccfb8-b0e6-11e6-862e-c96417bf4b41.png)

**Comment by wlbragg** [comment]
@HHS81 please see bug-876 branch.

**Comment by HHS81** [comment]
@wlbragg 
![c172prefltype1](https://cloud.githubusercontent.com/assets/12649375/20573326/89da62d6-b1af-11e6-8665-7c47b8db7e40.jpg)
![c172prefltype1 2](https://cloud.githubusercontent.com/assets/12649375/20573339/94368034-b1af-11e6-8460-8801ee721e67.jpg)
![c172prefltype2](https://cloud.githubusercontent.com/assets/12649375/20573356/9f831718-b1af-11e6-8157-97526033be65.jpg)
![c172prefltype2 2](https://cloud.githubusercontent.com/assets/12649375/20573367/aa4e4406-b1af-11e6-8797-548b803bf6bb.jpg)

**Comment by HHS81** [comment]
@wlbragg 
There are two new tags inside the eff-files:
	`<reflection-fresnel-factor type="float">1</reflection-fresnel-factor>`
and
	`<reflection-type type="int">2</reflection-type>`

The first controls the fresnel-effect. The higher the value, the stronger the effect.
The second controls the type of how the reflection color is applied. 

By adding `<use>/sim/rendering/fresnel-factor</use>` and `<use>/sim/rendering/refl-type</use>`insted of a number value you can adjust the values per livery.

**Comment by HHS81** [comment]
@wlbragg 

> Instead, what are you using the greymap.png for? Is that in place of white.png?

It is a map of greyvalues set to transparency. So you can control the reflection per pixel (unfortunately not per livery)

**Comment by gilbertohasnofb** [comment]
That looks really cool! But we have to be careful adjusting the intensity of the effect, as we don't want our poor Cessna looking like this:

![](https://img.planespotters.net/photo/421000/original/n881aa-american-airlines-boeing-727-223a_PlanespottersNet_421801.jpg)

**Comment by wlbragg** [comment]
@gilbertohasnofb did you look closely at the last image I posted? I actually like it better than the 4 with the new effect applied. A couple of the new effect ones have way to much green reflection on the top of the wing.
Take a close up look at the last image I posted. I think it should also still work with the livery as I don't think it is using any of the new effect.

**Comment by HHS81** [comment]
@ wlbragg you adjust the strength of the reflections and the strength of the fresnel effect. Especially the fresnel effect had been added to allow more realistic reflections. That does not mean you can not overdo any of this.

**Comment by gilbertohasnofb** [comment]
@wlbragg Yes, I have seen that one as well. I have the feeling that all these images (the four by Heiko and the one you posted before) show too much reflections. This is what a 172 looks like under RL light:

![](http://www.m0a.com/wordpress/wp-content/uploads/2009/01/cessna-172-flying-m0a.jpg)

Notice that the fuselage has little to none reflection, the only parts that reflect something are the ones at a shallow angle with the observer (in the case above, the bottom of the wings)

I know everyone in the forum/list hates me when I make comments about X-Plane, but do take a look in the video below about X-Plane 11 and how they are treating aircraft light reflection. Topic starts at 48:15, the visual example at around 49:30:

https://www.youtube.com/watch?v=8VUS7mYriNk

Or take a look at this screenshots below, notice how the door has no reflectivity (since the angle is quasi perpendicular) while the fuselage in front of the door does reflect a considerable amount of light at this shallow angle:

![](http://10images.cgames.de/images/idgwpgsgp/bdb/2774828/600x338.jpg)

I understand that the illumination code in FG might not be able to do the same, but in that case I would rather err by having too little reflectivity than by having too much.

**Comment by HHS81** [comment]
As I said: the new Code makes it better. It allows that the shallow angles have this reflections more than other. This is what is called Fresnel Effect. But you have to adjust the strength of the effect and the overall reflections by yourself. I have overdone it to showcase

**Comment by wlbragg** [comment]
>But you have to adjust the strength of the effect and the overall reflections by yourself. I have overdone it to showcase

Thanks @HHS81  I'll work on it, haven't had the time yet. I understood this issue to be too little reflection when it appears it is simply not the wanted reflection. So I think I have it in my head now what is needed and how to do it, thanks to your support and @gilbertohasnofb 's explanations.

**Comment by HHS81** [comment]
@gilbertohasnofb and @wlbragg 
I found a bit more time today.
X-Plane 11 uses now [PBR.](https://www.marmoset.co/posts/basic-theory-of-physically-based-rendering/)
We don't have this yet, it is much different to Rembrand or ALS.

But the shader update by Throsten and me allows now one important part: fresnel. 
I had overdone the effects here as an example to show that it is working. 

More realistic values could be:
`	<reflection-correction type="float">-0.8</reflection-correction>`
`	<reflection-fresnel-factor type="float">0.5</reflection-fresnel-factor>`
`	<reflection-type type="int">1</reflection-type>`

or

`	<reflection-correction type="float">-0.95</reflection-correction>`
`	<reflection-fresnel-factor type="float">0.75</reflection-fresnel-factor>`
`	<reflection-type type="int">2</reflection-type>`

(Both tested)

**Comment by onox** [comment]
Is there a PR or branch that has this code?

**Comment by HHS81** [comment]
And this: 
```
<PropertyList>
  <name>Aircraft/c172p/Models/Effects/exterior/bumpspec</name>
  <inherits-from>Effects/model-combined-deferred</inherits-from>
  <parameters>
    <rain-enabled type="int">2</rain-enabled>
    <normalmap-enabled type="int"> 1 </normalmap-enabled>
    <normalmap-dds type="int"> 0 </normalmap-dds>
    <normalmap-tiling type="float"> 1.0 </normalmap-tiling>
    <lightmap-enabled type="int"> 0 </lightmap-enabled>
    <reflection-enabled type="int"> 1 </reflection-enabled>
   <reflection-correction type="float">-0.75</reflection-correction>
   <reflection-fresnel-factor type="float">0.6</reflection-fresnel-factor>
   <reflection-type type="int">1</reflection-type>
    <reflection-dynamic type="int"> 1 </reflection-dynamic>
    <reflection-fresnel type="float"> 0.0 </reflection-fresnel>
    <reflection-rainbow type="float"> 0.0 </reflection-rainbow>
    <reflection-noise type="float"> 0.0 </reflection-noise>
    <texture n= "5" >
        <type>cubemap</type>
	<images>
			<positive-x>Aircraft/Generic/Effects/CubeMaps/buildings/N.png</positive-x>
			<negative-x>Aircraft/Generic/Effects/CubeMaps/buildings/S.png</negative-x>
			<positive-y>Aircraft/Generic/Effects/CubeMaps/buildings/W.png</positive-y>
			<negative-y>Aircraft/Generic/Effects/CubeMaps/buildings/E.png</negative-y>
			<positive-z>Aircraft/Generic/Effects/CubeMaps/buildings/U.png</positive-z>
			<negative-z>Aircraft/Generic/Effects/CubeMaps/buildings/D.png</negative-z>
            </images>
    </texture>
    <ambient-correction type="float"> 0.1 </ambient-correction>
  </parameters>
...
```

Will lead to this:
![shader](https://cloud.githubusercontent.com/assets/12649375/20862836/55aac67c-b9b6-11e6-960d-12e1be1b209f.jpg)
You can see the subtile reflections on the side of the engine cowling, but not on the door

**Comment by gilbertohasnofb** [comment]
@HHS81 That is absolutely fantastic, Heiko! :open_mouth: This behaviour of the reflections looks incredibly realistic!

@onox 

> Is there a PR or branch that has this code?

I don't think so

**Comment by onox** [comment]
I have created PR #889 which applies @HHS81's fresnel settings from above. @wlbragg I have removed your commit if you don't mind. From the comments in this thread I got the impression that it didn't correctly use the new fresnel effect.
