### ISSUE TITLE
Create new thumbnails

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#878]
Create three thumbnails with filenams `thumbnail-exterior.jpg`, `thumbnail-ground.jpg` and `thumbnail-panel.jpg` using the recommendations by @zakalawe 

>  If you would prefer to make them yourselves, I need the following:
> 
> * an exterior shot for each variant
> * a decent panel shot
> * a few 'feature' shots as you desire (showing what features of the 3D model you guys are most proud of)
>
>These should be 16:9 or 4:3 aspect and probably 800x600 or 1024x768 (or equivalent sizes for 16:9 aspect).
>
>The important thing: there must be /no/ text or borders on the image, because the new splash screen will overlay that info (i.e aircraft name, description, maybe authors) from the -set.xml automatically and dynamically.
>
>The launcher will also make these images visible when browsing aircraft to be installed. It will help me considerable if the C172 is a good example of what is possible!
>
>Oh and JPEG format is probably better for file size, to avoid the package getting huge.

**Comment by zakalawe** [comment]
Thank you for looking at this, I can promise you will do a better job than me :)

**Comment by gilbertohasnofb** [comment]
@zakalawe My pleasure, James. And sorry if I sounded harsh, I was not aware those were just for testing purposes 😄

**Comment by dg-505** [comment]
Two suggestions: :wink: 
![thumbnail-panel](https://cloud.githubusercontent.com/assets/12293276/20642571/7aba6638-b412-11e6-82a1-06de8cdbc0b5.jpg)
![thumbnail-ground](https://cloud.githubusercontent.com/assets/12293276/20642572/7abaafbc-b412-11e6-8c33-a6ddfdf3f52c.jpg)

**Comment by gilbertohasnofb** [comment]
@dg-505 I like the first picture a lot, those planes in the ground are really cool, but there are some things about it I don't like (which are not your fault!): the hands of the model do not fit the yoke, the GPS is untexturized, the walker model is quite bad in my opinion. I will give this issue a go and then we see, is that fine? If you or other people in the project want to come up with pictures, we can just show them here and let everyone here decide, I am totally fine with that.

**Comment by gilbertohasnofb** [comment]
@zakalawe @onox @wlbragg @Juanvvc @dany93 @dg-505 @everyone else, what about these ones?

cockpit:
![172-cockpit](https://cloud.githubusercontent.com/assets/5700795/20651666/9babe22c-b4e9-11e6-8607-e4039f2d06e4.jpg)

external view:
![172-external](https://cloud.githubusercontent.com/assets/5700795/20651667/9bac683c-b4e9-11e6-8dcd-d17de2659f56.jpg)

external view2:
![172-external2](https://cloud.githubusercontent.com/assets/5700795/20651668/9bad3780-b4e9-11e6-99e5-1a5b27746070.jpg)

parked with open doors:
![172-open-door](https://cloud.githubusercontent.com/assets/5700795/20651671/9bb0dca0-b4e9-11e6-8cc4-2be7d7fbbe7f.jpg)

secured:
![172-secured](https://cloud.githubusercontent.com/assets/5700795/20651669/9badc7ae-b4e9-11e6-94c3-528332ec7ea0.jpg)

variant amphibian:
![variant-amphibian](https://cloud.githubusercontent.com/assets/5700795/20651670/9bae2488-b4e9-11e6-9288-47546a9d34a2.jpg)

variant bush:
![variant-bush](https://cloud.githubusercontent.com/assets/5700795/20651672/9bc008ec-b4e9-11e6-8865-becf58e60e0d.jpg)

variant default gear:
![variant-default](https://cloud.githubusercontent.com/assets/5700795/20651673/9bc0be40-b4e9-11e6-8ed5-004b39a6bfb1.jpg)

variant ski:
![variant-ski](https://cloud.githubusercontent.com/assets/5700795/20651674/9bc21a6a-b4e9-11e6-957f-1a342f1272ff.jpg)

And I think the second shot by @dg-505 above is very nicely showing the ground equipment, so we can include it as well. I have resized it to 1024x576 (i.e. 16:9 ratio):

![172-ground-equipment](https://cloud.githubusercontent.com/assets/5700795/20651691/fbad188a-b4e9-11e6-85ef-96437335e18a.jpg)

**Comment by dany93** [comment]
Fine

**Comment by wkitty42** [comment]
that always struck me weird, too... then i figured out it was a wide FOV shot taken from "close" in...

**Comment by wlbragg** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
@dany93 @wkitty42 really? That's my favourite shot ever of our plane! :broken_heart:

**Comment by gilbertohasnofb** [comment]
But I am fine changing it if you guys want, just please suggest something else then (a screenshot from the wiki, forum or taken by yourselves). Just please use some high quality visual settings: use ALS, use advanced weather, no fps counter in the corner, no menu bar on top, etc.

**Comment by wkitty42** [comment]
@gilbertohasnofb nonononono... i'm not saying to remove it... it is just the perspective... especially on a standard aspect screen... on a wide screen, i imagine it looks different/better? i dunno but i'm not against it at all... i only tossed out a comment... nothing more...

FWIW: i almost bought, on black friday, a set of 25inch flat screens to replace this Samsung SyncMaster 900p... it'll happen one day... the lower power usage alone will easily pay for them... 25w compared to 150w...

**Comment by onox** [comment]
@gilbertohasnofb Your screenshots look fine to me. The "variant default gear" looks like you just altered the left/right position of the camera.

**Comment by dany93** [comment]
Like @wkitty42. Not so important, particularly if you @gilbertohasnofb  like so much. :smile:

**Comment by gilbertohasnofb** [comment]
Ok, thanks guys :smile_cat: 

> The "variant default gear" looks like you just altered the left/right position of the camera.

That's correct. In a lot of screenshots I also play with the "focal length" by zooming in/out combined with coming closer/farther from the aircraft. That one is "distorted" because it's like an image with a wide angle lens, and I think that's what makes the composition interesting.

**Comment by gilbertohasnofb** [comment]
@zakalawe I just saw your [forum post](https://forum.flightgear.org/viewtopic.php?f=19&t=31730) about the new splash screens, so I would like to ask you a couple of things:

1) are you referring to the same as these thumbnails here or do you literally mean splash screens? And if you mean the latter, should we modify ours? (please see files `splash1.png` through `splash10.png` in the root of our `master`
2) if you meant thumbnails, then are the ones we selected here fine? If so I will make a PR to add them to the `master` branch
3) do these thumbnails need to have some specific file names?

**Comment by zakalawe** [comment]
It's the same system, I switch the name from 'thumbnails' to 'previews'. For an example of what to do, look a the Seneca in FGaddon. The data is added to the -set.xml, you can have different previews for each variant (skis, floats, etc) also.

And yes the images above look excellent! Only thing is tag them with appropriate type; we don't have a standard for this so please use:
'exterior', 'cockpit', 'interior', 'detail'
(in your ones above, I would use 'detail' for the one with the open door and the ground equipment). It's also up to you which ones you mark as suitable for use a the splash. (Probably not the cockpit and detail ones but your choice).

There is also provision to replace the aircraft name with a seperate logo image; the B1900 is an example of this in FGaddon. I would suggest leaving this feature for now, and adding it as a seperate piece.

**Comment by zakalawe** [comment]
(BTW once you have done this I will probably point people at the C172 as a reference aircraft for the system...)

**Comment by gilbertohasnofb** [comment]
> For an example of what to do, look a the Seneca in FGaddon. The data is added to the -set.xml, you can have different previews for each variant (skis, floats, etc) also.

Great, I took a look at it and I think I understand well how it works. I will name these previews above in a consistent way and add them as follows to the -set.xml file, inside the `<sim>` block:

```
    <previews>
        <preview>
            <type>exterior</type>
            <path>c172p-preview1.png</path>
            <splash type="bool">true</splash>
        </preview>
        <preview>
            <type>panel</type>
            <path>c172p-preview2.png</path>
            <splash type="bool">true</splash>
        </preview>
        [...]
    </previews>
```

> And yes the images above look excellent! Only thing is tag them with appropriate type; we don't have a standard for this so please use:
> 'exterior', 'cockpit', 'interior', 'detail'

Great to hear it! And the tags are all clear.

> It's also up to you which ones you mark as suitable for use a the splash. (Probably not the cockpit and detail ones but your choice).

Hmm, we are currently using 10 splash screens which are randomly selected to be displayed, do you mean that the new preview system will replace the current splash screen system? I was under the impression that these previews would be used only by the launcher, did I misunderstand something?

**Comment by zakalawe** [comment]
Yes this also replaces the current splash screens. I didn't want to bloat every aircraft zip by have two sets of very similar images, so I've adjusted the system so that one set of images can be used for both.

**Comment by gilbertohasnofb** [comment]
@zakalawe I have noticed that the splash screen for the B1900D (file `b1900dsplash.png`) has black stripes on the top and on the bottom just like our current 10 splash screens, so another possibility for us here would be to simply remove the text from our current 10 splashes, categorize them as you suggested and change the xml code in the set file, is that correct?

**Comment by gilbertohasnofb** [comment]
@zakalawe James, I am sorry to bother you but I am having some troubles implementing the preview system. I am using the code I posted above https://github.com/c172p-team/c172p-detailed/issues/878#issuecomment-282271549 but the splash screens used when I launch FG is one of the generic ones and not the aircraft specific ones I am defining. This happens with both the Qt5 and FGRun launchers. I am running FG 2017.1.2. Do you have some idea of what I might be doing wrongly?

@dg-505 would you like to re-create that second shot of yours from this post https://github.com/c172p-team/c172p-detailed/issues/878#issuecomment-263079769 now that @wlbragg has made a big improvement to the bush tires?

**Comment by zakalawe** [comment]
Hmm, can I see this code + the files in current repo here? What you have looks correct, it should work.

**Comment by gilbertohasnofb** [comment]
@zakalawe Sure, I have pushed my initial commit to the branch `bug-878`. The code for the preview is in the set file, line 294 on. I have pushed just two splash images so far as I am still testing it, so I just want to figure it out how to make it work here on my side before working on the images themselves. Thanks a lot for the help!

**Comment by wlbragg** [comment]
@gilbertohasnofb I added something similar to the following to each -set file in the J3Cub project and it appears to be working correctly.
~~~xml
<previews>
  <preview>
    <type>panel</type>
    <path>splash1.png</path>
    <splash type="bool">true</splash>
  </preview>
  <preview>
    <type>panel</type>
    <path>splash2.png</path>
    <splash type="bool">true</splash>
  </preview>
  <preview>
    <type>panel</type>
    <path>splash9.png</path>
    <splash type="bool">true</splash>
  </preview>
  <preview>
    <type>panel</type>
    <path>splash10.png</path>
    <splash type="bool">true</splash>
  </preview>
</previews>
<startup>
  <splash-texture>Aircraft/J3Cub/splash1.png</splash-texture>
  <splash-texture>Aircraft/J3Cub/splash8.png</splash-texture>
  <splash-texture>Aircraft/J3Cub/splash9.png</splash-texture>
  <splash-texture>Aircraft/J3Cub/splash10.png</splash-texture>
</startup>
~~~

Note: the "type" is the same in each of these, I forgot about that part. Actually, I don't really know what that is for? Would someone care to explain that to me?

**Comment by zakalawe** [comment]
Answered this on the ML, but 'splash-texture' is no longer needed (but can be kept for backwards compat) and the new system accepts images of any size. I am using 1024x768 but anything reasonable should work: 800x600 saves disk space / makes the download smaller but looks a little blurry when starting full-screen on my big monitors.

**Comment by gilbertohasnofb** [comment]
@wlbragg except for the <startup> block, which as James states is not necessary any longer, my code seems identical to yours.

**Comment by zakalawe** [comment]
Just testing the C172, the previews work for me, but please change them to exclude the Cessna logo, and do that (on the splash screen) via the splash-logo feature.

**Comment by gilbertohasnofb** [comment]
> the previews work for me

Hmm, so I have to figure out why it isn't working for me else it's difficult to work on these. With version 2017.1.2 it should work, correct?

>  but please change them to exclude the Cessna logo

Sure

**Comment by dg-505** [comment]
I'm not 100 percent sure, but I think it works only in next, i.e. in 2017.2.0

**Comment by zakalawe** [comment]
Yes, only on 'next' for now, while we work out the bugs :)

**Comment by onox** [comment]
@zakalawe I just recompiled FG to see how the new splash screen works. Looks better now. One comment though: could you replace "http://www.flightgear.org" with "flightgear.org" (or at least drop the http:// part)?

**Comment by gilbertohasnofb** [comment]
Ok, thanks all. I am unfortunately having issues with 2017.2.0 here on my side so I am sticking to 2017.1.2, so I must trust whomever reviews this that the result is looking fine. I have pushed a PR in which all text has been removed from our splash screens and I categorized them as James suggested. So please test it and make sure it is working and looking good before merging that PR, ok?

**Comment by wlbragg** [comment]
@zakalawe, rather than have you chase all over for this information and feedback, I'll post it here as it will apply to the c172p also.
What, if anything can be done about a lengthy authors description?
![splash](https://cloud.githubusercontent.com/assets/11069680/23722376/bb6a4c0a-040a-11e7-9993-5b59dda1722d.jpg)

**Comment by wlbragg** [comment]
Also,

>but please change them to exclude the Cessna logo, and do that (on the splash screen) via the splash-logo feature.

What is the "splash-logo feature" and how does that work?

**Comment by zakalawe** [comment]
Look at the B1900d for an example - you can have a separate (transparent, PNG) image on the splash screen which replaces the textual aircraft name.

Regarding the long authors string, I am still working on a solution.
