### ISSUE TITLE
Rendering bug with reflect-shader on ponton

### ISSUE THREAD

**Issue by HHS81** [c172p-team/c172p-detailed#891]
This is because the effect for the pontons inherits from the `bumpspec-fuselage.eff`. This has a normalmap enabled, which makes use of the normalmap `fuselage-normal.png` for the fuselage.

The ponton doesn't have an own normalmap  , nor it is mapped to the normalmap `fuselage-normal.png` of the fuselage.

So the .eff-file can't find it and as resultat we got a strange rendering:
[https://cloud.githubusercontent.com/assets/3361585/20885822/3f2289ec-baf3-11e6-949b-d6e1576430ce.png](url)

Please see also  #889  and #876 

Solution: create an own effect-file with own normalmap for the pontons.

**Comment by wlbragg** [comment]
Also see #507
