### ISSUE TITLE
Preload damaged model mesh and gear or equipment changes where slow to load.

### ISSUE THREAD

**Issue by wlbragg** [c172p-team/c172p-detailed#894]
We talked about adding damage model objects to the main model to speed up model rendering under a damage condition.While experimenting with the same thing in the J3Cub I discovered that this really doesn't help, the first time you see the damage event it still pauses. Also the pause when changing interior to exterior view and equipment changes can be sped up using a technique I discovered.
While it isn't elegant it worked wonder on the J3Cub which was really slow to update these three events, view change, equipment change and damage model loading upon a damage condition.

This would not eliminate the need to do #319 Improve the broken wing model, that still would be a good idea. However it does eliminate the need to combine all the different blends into the same ac.

 This technique is transparent to the user but it does take the delay time normally experienced during runtime changes to the mesh and adds it to the loading time.

Immediately after FDM_init
~~~xml
setprop("/sim/current-view/view-number", 1);
setprop("/sim/model/preload", 1); 
~~~
this should be instantiated in the -set file like this
~~~xml
<sim>
<model>
<preload type="int or bool">1 or true</preload>
</model>
</sim>
~~~
but I couldn't get it to load the value using the -set file so I also initialized it in nasal.

Then in all damage, equipment or any other model change condition where you use the "select animation", to pre-cache that object, add an ```<or>``` to validate the ```/sim/model/preload```
Example
~~~xml
<!--Right Amphibious Damaged -->
    <animation>
        <type>select</type>
        <object-name>R-FloatD</object-name>
        <object-name>RFrontWheelD</object-name>
        <object-name>RAxleD</object-name>
        <object-name>RdamperD</object-name>
        <object-name>Rstrut.001D</object-name>
        <object-name>Rstrut.002D</object-name>
        <condition>
            <or>
                <and>
                    <equals>
                        <property alias="/params/pontoon_right_damaged/property"/>
                        <value>2</value>
                    </equals>
                    <equals>
                        <property alias="/params/bushkit"/>
                        <value>3</value>
                    </equals>
                </and>
                <property>sim/model/preload</property>
            </or>
        </condition>
    </animation>
~~~
Then I used the first loop I run, that happens to be a global perpetual loop to check for actions not conducive to a listener, and changed the view back to interior and set the ```/sim/model/preload``` property back to 0.
~~~xml
If (getprop("/sim/current-view/view-number") == 1) {
    setprop("/sim/current-view/view-number", 0);
    setprop("/sim/model/preload", 0);
}
~~~
That's it, it actually works really well. The trade off is adding load time. 

What it is actually doing is immediately after FDM_init it switches the view to 1 (external), makes preload param true, this causes both the view to change to exterior and then all the objects to pre-load and pre-cache. Then it switches the view back to 0 (interior) and sets the preload flag to false so only the normal intended objects are now selected and visible. This is all done during the loading screen right after the "Loading Scenery" is finished but before the screen is updated.

For an example of how well it works see the fgaddon J3Cub. If you ever tried it prior to this change you'll notice the difference.

If there is a better way I am all ears. I asked on the dev mailing list if there is a way to pre-cache or where in the c++ code it is responsible for the delay in these events. I haven't heard anything back yet.

**Comment by onox** [comment]
@wlbragg See #895

**Comment by wlbragg** [comment]
We should probably close this and go with the optimization ideas, hopefully they will be enough to speed things up. This could remain a fall-back for damage models if they still lag upon loading.
FYI: in the J3Cub this did seem effective in speeding of everything, except livery change over. Maybe a more limited use could be tolerable.
