### ISSUE TITLE
3D model optimizations

### ISSUE THREAD

**Issue by onox** [c172p-team/c172p-detailed#895]
I've been reading the mailing list a bit, and it seems we should apply some optimizations.

1. We can start with #592. So you get something like this:
    
    ![fgfs-wings](https://cloud.githubusercontent.com/assets/3361585/21724858/3f94d63a-d436-11e6-823d-f6b3c4616245.png)
    
   All the objects can be in the same `c172p.blend` file and same textures can be used.
    
    I can do all the XML stuff in `Models/c172p.xml`.

2. We should use a as few textures as possible. We should also reuse UV coordinates if an object (and its texture) is symmetrical. For example, take a look at `fuselage.png`: apart from the baggage door, the right side of the fuselage is the same as the left side, so we can just use one side. Same for the propeller (just use one half) and that thing above the wheel. Same thing with `tail.png`, `wing.png`, and `floats.png`.
    
    `interior_windows.png`, `lights.png`, `panel_parts.png`, `prop.png` are very small textures, and should be added to to the other textures.
    
    Same thing with many instruments; they often use many small textures instead of just one big texture.

3. There are some unnecessary objects: https://github.com/c172p-team/c172p-detailed/blob/master/Models/c172p.xml#L3117-L3164 This can be one object called 'FuelSelector` with one rotate animation instead of four select animations.
    
    We can remove https://github.com/c172p-team/c172p-detailed/blob/master/Models/c172p.xml#L3505-L3551 if we decide to drop Rembrandt lighting.

**Comment by gilbertohasnofb** [comment]
About 2., I am all for it but I am just a bit afraid of doing this now and later having to rework these textures because of model changes. I would much rather wait for the main issues involving 3D model to be solved before attacking this, as there is potential of UV map changes. @wlbragg what do you think?

> if we decide to drop Rembrandt lighting.

Yeah, I think Rembrandt is a dead horse but it seems that a large group of people still use (and love) it. What would be the reason for dropping it? Would that also optimize our aircraft or minimize some work we need to do with some specific issue?

**Comment by onox** [comment]
>Yeah, I think Rembrandt is a dead horse but it seems that a large group of people still use (and love) it. What would be the reason for dropping it? Would that also optimize our aircraft or minimize some work we need to do with some specific issue?

For us it would not mean much; we can just drop a little bit of code. Currently we don't really support Rembrandt anyway. It's mostly the fact that having 3 render engines in FG and tons of effect files and shaders make it easy for aircraft developers to make mistakes (using a wrong effect for particular object for example). FG should really make a decision, clean things up, and focus on one engine. But I don't see that happening. Maybe declaring Basic and Rembrandt deprecated could set things moving.

**Comment by wlbragg** [comment]
>About 2., I am all for it but I am just a bit afraid of doing this now and later having to rework these textures because of model changes. I would much rather wait for the main issues involving 3D model to be solved before attacking this, as there is potential of UV map changes. @wlbragg what do you think?

Yeah, you make a good point. @gilbertohasnofb refresh my memory on the model issues we need to correct, maybe I can tackle all of this together at the same time.

**Comment by gilbertohasnofb** [comment]
@onox :+1: about Rembrandt

> How much do the fuselages of the c172p and c182 differ in real life?

Quite a lot, I believe. Not only in size, but also in shape. Deforming a 182 into a 172 wouldn't be a practical way of going through things I think.

@wlbragg 
> refresh my memory on the model issues we need to correct, maybe I can tackle all of this together at the same time.

It's mainly the nose of the aircraft and the wings. Basically we need thicker wings, reshape the nose a bit and raise the cockpit. These are perhaps all of them, and they of course vary in degree of relevance (and of quantity of work):

https://github.com/c172p-team/c172p-detailed/issues/118
https://github.com/c172p-team/c172p-detailed/issues/6
https://github.com/c172p-team/c172p-detailed/issues/860
https://github.com/c172p-team/c172p-detailed/issues/259
https://github.com/c172p-team/c172p-detailed/issues/446
https://github.com/c172p-team/c172p-detailed/issues/216
https://github.com/c172p-team/c172p-detailed/issues/621
https://github.com/c172p-team/c172p-detailed/issues/600
https://github.com/c172p-team/c172p-detailed/issues/430

**Comment by HHS81** [comment]
@onox 

> We should use a as few textures as possible. We should also reuse UV coordinates if an object is symmetrical. For example, take a look at fuselage.png: apart from the baggage door, the right side of the fuselage is the same as the left side, so we can just use one side.

That's no good idea, because one side will be the mirror of the other side. (mirroed texts, numbers, liveries etc....

> How much do the fuselages of the c172p and c182 differ in real life?

A very lot!

**Comment by onox** [comment]
> That's no good idea, because one side will be the mirror of the other side. (mirroed texts, numbers, liveries etc....

Obviously it only applies where you don't have numbers or asymmetrical liveries.

I'm just highlighting a possible technique to reduce the amount of space on a texture that is wasted.

**Comment by HHS81** [comment]
@onox  But that's what we have with the fuselage. And this technique doesn't apply to objects who needs different lightmaps.

**Comment by onox** [comment]
About point 3: we can drop `LandingLightCone`, `TaxiLightCone`, `navlight_left`, `navlight_right`, `ZHI_cent`, `landinglight` (replace it with ALS procedural light), `taxilight` (replace it with ALS procedural light).

`Exhaust` should be made single sided (uncheck Double Sided on the Data tab in Blender), add an inner layer (enable Backface Culling under Shading (press n key).

`PitotTube` should also be single sided.

All the glass should be single sided. Flip normals if a face is not visible.

... and we should find out if and how FG does face culling (with `glEnable(GL_CULL_FACE)`)

**Comment by wlbragg** [comment]
>All the glass should be single sided. Flip normals if a face is not visible.

This needs to be verified. I remember setting the glass up like it is because it was the only way we could get all the effects we have and also see exterior rain (falling rain). I don't remember all the nuance, but I do remember butting heads with it.

>>We should also reuse UV coordinates
>And this technique doesn't apply to objects which needs different lightmaps.

Yes, any surface that we may ever want to apply a lightmap to needs to be in its own uv space.
