### ISSUE TITLE
Add condition to "sound" logic to eliminate sound during loading.

### ISSUE THREAD

**Issue by wlbragg** [c172p-team/c172p-detailed#896]
I asked this question on the dev list and have a possible way to eliminate the really harsh sounds from firing during the loading screen.
I tried some of it on the J3Cub and it appears to work OK except I don't like what I had to do to the "in-transit" mode sounds (i.e. flaps) and the wind (non-conditional sound).

For the looped sounds with conditionals it was relatively easy
~~~xml
<crank>
            <name>crank</name>
            <mode>looped</mode>
            <path>Sounds/cranking.wav</path>
            <condition>
                <and>
                    <property>/engines/active-engine/cranking</property>
                    <not>
                        <property>/sim/startup/splash-alpha</property>
                    </not>
                    <not>
                        <property>/engines/active-engine/running</property>
                    </not>
                </and>
            </condition>
            <volume>
                <factor>0.7143</factor>
                <property>/sim/model/j3cub/sound/volume-boost-door</property>
            </volume>
            <volume>
                <offset>0.5</offset>
            </volume>
        </crank>
~~~

For flaps the only way I could get it to work was to eliminate "in-transit" mode and make it "looped". But then I had to add a bunch of additional conditions. Maybe one of you geniuses (@onox) can figure out a better way. It's possible you can still use the in-transit mode, maybe I simply messed up on the logic when I tried a few things.

~~~xml
        <flap>
            <name>flaps</name>
            <!--mode>in-transit</mode-->
			<mode>looped</mode>
            <path>Sounds/flaps.wav</path>
            <condition>
                <and>
                    <or>
                        <and>
                            <greater-than>
                                <property>/surface-positions/flap-pos-norm</property>
                                <value>0</value>
                            </greater-than>
                            <less-than>
                                <property>/surface-positions/flap-pos-norm</property>
                                <value>0.3333331</value>
                            </less-than>
                        </and>
                        <and>
                            <greater-than>
                                <property>/surface-positions/flap-pos-norm</property>
                                <value>0.3333335</value>
                            </greater-than>
                            <less-than>
                                <property>/surface-positions/flap-pos-norm</property>
                                <value>0.6666665</value>
                            </less-than>
                        </and>
                        <and>
                            <greater-than>
                                <property>/surface-positions/flap-pos-norm</property>
                                <value>0.6666668</value>
                            </greater-than>
                            <less-than>
                                <property>/surface-positions/flap-pos-norm</property>
                                <value>1</value>
                            </less-than>
                        </and>
                    </or>
                    <property>/sim/model/j3cub/pa-18</property>
                    <not>
                        <property>/sim/startup/splash-alpha</property>
                    </not>
                </and>
            </condition>
            <volume>
                <factor>0.8</factor>
            </volume>
            <reference-dist>10.0</reference-dist>
            <max-dist>20.0</max-dist>
        </flap>
~~~
I don't know what to do with the non-conditional wind either
~~~xml
 <condition>
                <!-- Silence "Neither a condition nor a property specified" warning -->
                <true/>
 </condition>
~~~

**Comment by wlbragg** [comment]
There is also a sound/enalble-disable property (I can't remember the exact property), but it appeared to not be active until after fdm_init and that was too late.

**Comment by gilbertohasnofb** [comment]
I don't like those sounds in the loading screen either, for instance the sound of the door banging or the flap sounds, but I think this is something that should be done by the devs directly in the FG code and not be up to aircraft developers to hack their way around the issues in the sim. Well, that's my 2 cents.

**Comment by wkitty42** [comment]
On 01/10/2017 05:16 AM, Gilberto Agostinho wrote:
> I don't like those sounds in the loading screen either, for instance the
> sound of the door banging or the flap sounds, but I think this is something
> that should be done by the devs directly in the FG code and not be up to
> aircraft developers to hack their way around the issues in the sim. Well,
> that's my 2 cents.

i agree completely... these sounds come during the sim and FDM start up 
sequence... likely when the craft is dropped onto the terrain surface from 
whatever height the sim starts it at... you should hear the 777 and/or 757 when 
they hit the terrain and their tires screech ;)

so anyway, yeah, i agree that the devs need to turn off the sounds and only 
enable them once the FDM is stable and the sim is ready for action... that would 
be roughly around the time the splash screen is removed...

my 2, too

**Comment by onox** [comment]
> but I think this is something that should be done by the devs directly in the FG code and not be up to aircraft developers to hack their way around the issues in the sim. Well, that's my 2 cents.

I agree it should be fixed in FG.

**Comment by zakalawe** [comment]
I think myself or Erik could look at fixing this in the main code, could you detail what the switching criteria might be? I.e what's the earliest time sounds should be played? During Nasal init maybe?

It would probably be useful to have a discussion on the developer list to check other aircraft developers agree.

**Comment by gilbertohasnofb** [comment]
@zakalawe What about ignoring any sound events that happen while the loading screen is still being shown?

**Comment by wlbragg** [comment]
I posted this on the dev list, hopefully it can be taken care of in the main code. Thanks James!

**Comment by wlbragg** [comment]
Taken care of in the source code, yeah. Thanks James!

**Comment by gilbertohasnofb** [comment]
Thank you all for bringing this up and fixing it :+1:
