### ISSUE TITLE
radios still receive asos when avionics are switched off

### ISSUE THREAD

**Issue by kentrosaur** [c172p-team/c172p-detailed#900]
1.) start c172p
2.) turn on master and avionics 
3.) tune com1 or com2 to local ASOS station and toggle com1/2 to headset or speaker
4.) listen to metar
5.) turn off avionics, metar continues to broadcast
6.) turn off master, continue to hear broadcast

Variation, test nav1/2:
1 + 2 above, 3.) set nav1 or 2 to a nearby beacon.  4) hear morse code  repeat 5 but note that the morse code is not on the speaker.

**Comment by gilbertohasnofb** [comment]
@kentrosaur is this a c172p specific issue or do you see it in other aircraft as well (i.e. a general FG bug)?

**Comment by gilbertohasnofb** [comment]
@kentrosaur reproduced. Actually, ignore the previous question, this is clearly an issue with the radio itself. Apparently those toggles are not checking if electricity is reaching the radio (if avionics are on, if master is on, if circuit breakers are in place, etc.). 

Actually, the radio has a lot of other issues. For instance, when you toggle COM1/2 to off from headset or speaker, you can see that the volume knob in the COM1/2 radio moves to 0%. Not only that, but normally setting the volume to 0 does make the displays go black, but this automatically moving of volume to 0 via the headset/speaker/off toggle does not do that. It's really a mess that needs to be addressed sooner or later...

**Comment by onox** [comment]
@kentrosaur Could you test branch `bug-900`? Comm 0/1, DME, and transponder should now be serviceable depending on electrical output.

**Comment by kentrosaur** [comment]
Just got a chance to check this and it works, thanks!

**Comment by onox** [comment]
Good to hear 👍
