### ISSUE TITLE
Shadow remains visible but unoriented upon water upside down

### ISSUE THREAD

**Issue by wlbragg** [c172p-team/c172p-detailed#913]
I'm looking for a good property, maybe an fdm/attitude, to use in the shadow condition code. What I want is one that will work for upside down. The contact points don't register WOW over water so we're getting a shadow after crashing upside down, which is a common attitude when trying to land upon water with gear down in the amphibious configuration.

**Comment by onox** [comment]
Isn't there some contact point on top of the wings?

**Comment by wlbragg** [comment]
They don't register WOW over water thus the use of something else is needed.

**Comment by onox** [comment]
Have you tried `/fdm/jsbsim/hydro/active-norm > 0.0`?

**Comment by onox** [comment]
And `/fdm/jsbsim/ground/solid`

**Comment by wlbragg** [comment]
No, those will shut off the shadow anytime we're over water. I'm looking for a property that indicates the aircraft is inverted or even <> than 90 deg, or <>  than -90 deg pitch or roll.
