### ISSUE TITLE
New HD splash screens aren't loaded in startup

### ISSUE THREAD

**Issue by condab** [c172p-team/c172p-detailed#915]
The enhanced splash screens which were recently added are not loaded in startup and there is a reason. Stated in [this](http://wiki.flightgear.org/Howto:Create_custom_splash_screens#Things_to_note "Splash Screens Wiki") article; "Image dimensions _must_ be **powers of two** (eg. 256x256 or 512x512 pixels)", which means that they will be square. The new splash screens for c172p are 16:9 widescreen, so they are disregarded in startup. 

I have also read that the filenames need to be referenced in an xml and are usually "splash.png", whereas the new c172p has **.jpeg** images named "c172p-preview0.jpg". This may not be a problem if they are referenced in the xml file, but it has always usually been "splash(number).png" which would make for better continuity across versions. 

**Simple fix:** Black bars on the top and bottom of the splash screens should be created with name tags like "FlightGear" and "Cessna 172p" to square up the image. Preferably, but not necessarily crucial; filenames for splash screens should be returned to "splash(number).png". The images (to my belief) are still allowed to be high quality, so they don't need to be reverted to the old splashes, just edited.

P.S. I've never submitted an issue here before, so this could be completely not my responsibility / wrong place / not my authority. If this post is wrong or the issue is not occurring for anyone else, please remove this post or comment that it is wrong and I will remove it asap. 

I sincerely apologize if I have made a mistake.

**Comment by onox** [comment]
The new splash screens are meant for Flightgear 2017.2. See https://github.com/c172p-team/c172p-detailed/pull/912#issuecomment-284750144

**Comment by onox** [comment]
You probably have 2017.1.x? That should explain it. The Github version of the c172p is officially meant to be used together with the git version of FG / FGDATA, but it usually works (mostly) for older versions as well.

If you spot more bugs, feel free to open an issue for them.

**Comment by condab** [comment]
Just as I finished downloading 2017.2, I realized this! I see how it is meant to be used, both in the aircraft list before startup & as the new splash screens. Sorry for my ignorance, and thanks for responding quickly. I'll be sure to double check next time!

**Comment by gilbertohasnofb** [comment]
@condab 

> I sincerely apologize if I have made a mistake.

No worries, we appreciate the bug reports and the troubleshooting. It's better to have someone open an issue like this (i.e. invalid due to different FG version) than someone keeping silent about a potential bug.
