### ISSUE TITLE
Attitude Indicator calibration fails after off nominal flight envelope

### ISSUE THREAD

**Issue by wlbragg** [c172p-team/c172p-detailed#923]
See https://forum.flightgear.org/viewtopic.php?f=25&t=32121

This is at least the second time I have seen this issue. I did some quick tests and searches through the property tree and it is unclear to me as to the cause and effect. It is "easily" reproducible.

**Comment by dany93** [comment]
I've responded, what IMHO should be an explanation.
https://forum.flightgear.org/viewtopic.php?f=25&t=32121&p=309724#p309724

**Comment by wlbragg** [comment]
I suppose I need to close this, but I really would like to understand why the FDM having the stall and spin behavior modeled causes the gyro to fail but not if it doesn't?

**Comment by dany93** [comment]
Because the spin departure in stall and spin is much more brutal than the control by the ailerons and rudder inside the flight envelope. The gyroscope of the attitude indicator cannot keep its absolute orientation.
At least, this is my interpretation.
I'd like that real pilots give their opinion, but this is not an exercise often practised with ordinary aicraft, and aerobatics pilots are rare.

**Comment by wlbragg** [comment]
~~~xml
Because the spin departure in stall and spin is much more brutal than the control by the ailerons and rudder inside the flight envelope.~~~
I get that except I can cause it with some steep banks and not just in a spin or stall situation, yet that can't be done in the j3. So it is something other than the act of a "more" aggressive maneuver. It is inherent to something else.

**Comment by dany93** [comment]
Yes, on very steep banks (almost vertical, close to or slightly more than 90 deg roll) I sometimes see the AI make an angular "jump" instead of increasing continuously.
I don't know....

**Comment by dany93** [comment]
I've found that, to get this "dysfunction" (probably realistic IMO), the` /instrument/attitude-indicator/config/tumble-flag = ` property must be `bool` and = `'true'`.
Can you check and try this in the J3Cub ?
Its default type and state depends on the aircraft.

**Comment by dany93** [comment]
Thank you @Juanvvc for these explanations and the attitude indicator code.

**Comment by wlbragg** [comment]
> If tumble-flag is set

Thanks for clarifying, I haven't looked at the Cub yet but I have no doubt this it the piece I was missing, thanks.

With this all said, this issue is a non-issue.
