### ISSUE TITLE
Questionable transponder behavior 

### ISSUE THREAD

**Issue by wlbragg** [c172p-team/c172p-detailed#926]
> by CaptB » Wed Jun 07, 2017 7:47 am
> I have tested with OpenRadar, where the modes seem to work better, but still not perfect. I tested the FGAddon C172 where Transponder mode position "ON" is no different from "ALT" it should instead not report altitude, just squawk number, so basically mode A when set to "ON" and mode C when set to "ALT"

See https://forum.flightgear.org/viewtopic.php?f=4&t=32320&start=15#p312001

I've never used the transponder and know next to nothing about its function, but it may be worth investigating to get it right.

**Comment by wlbragg** [comment]
> @wlbragg: this seems unrelated to the C172, same behaviour with UFO

Looks like this was a non-starter, sorry for the noise.
I'll keep and eye on it.

**Comment by wkitty42** [comment]
On 06/07/2017 01:10 PM, wlbragg wrote:
>     @wlbragg: this seems unrelated to the C172,
>     same behaviour with UFO
> 
> Looks like this was a non-starter, sorry for the noise.
> I'll keep and eye on it.


if the UFO does this, too, then perhaps it needs to be reported on the fgfs-dev 
mailing list so they can take a closer look at the code related to the 
transponder and its different modes ??

**Comment by gilbertohasnofb** [comment]
@wlbragg yes, it would be nice to bring it up to the mailing or to try fixing it ourselves. Is anyone familiar with how the transponder should work?

(by the way, sorry for the long silence, I have been away for more than a month but I am finally back home)

**Comment by wkitty42** [comment]
there's been a decent bit of discussion about it on the list or the forum... i read several posts about it earlier today (11 June) but don't recall where exactly... i think the forum because sanhozy's name keeps flashing in my memory viewport ;)
