### ISSUE TITLE
No more shadows on the dashboard with ALS

### ISSUE THREAD

**Issue by dany93** [c172p-team/c172p-detailed#927]
I can no longer get these nice shadows sweeping on the dashboard with ALS.
I don't know if I am missing a setting...
FG 2017.3.0 (was the same with 2017.2.0),
Linux Mint 18 (based on Ubuntu 16.04)
Graphics card NVIDIA GTX 650, Linux driver 375.66

**Comment by wlbragg** [comment]
Hum, I just checked and I still have them. Are you getting them on the door or floor?

**Comment by dany93** [comment]
You are right.
I can see them on the door and floor by enlarging the view (large angle zooming). Or / and / by a good orientation between the sun and the aircraft (obviously).

I believed they were easier to see before on the dashboard (?? by memory... may be wrong)

Anyway, they appear and move, sorry and thank you for the response.

**Comment by gilbertohasnofb** [comment]
> I believed they were easier to see before on the dashboard (?? by memory... may be wrong)

Do you have this impression only with our aircraft or with others as well? I have to say the shadows look fine for me on 2017.2

**Comment by dany93** [comment]
I haven't tested with other aircraft (which need this feature coded to get it).

Yes, the shadows look fine on the floor and door. Even better if I set the sun in the morning  (low angle).
For the dashboard, it can come from my memory... and depend on the livery.
Do not worry, thank you.
