### ISSUE TITLE
Generic tutorials

### ISSUE THREAD

**Issue by wlbragg** [c172p-team/c172p-detailed#928]
Tutorials should be of a more generic nature. For example see,
https://forum.flightgear.org/viewtopic.php?f=25&t=32636

If this were not geared for a specific airport then there would be no requirement to update them per version release.

**Comment by gilbertohasnofb** [comment]
@wlbragg if our request to have a fixed scenery tile available in all versions then this issue can be closed and we can open a new one for moving the tutorials once and for all for whatever airport will be decided.

**Comment by wkitty42** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
@wlbragg I am closing this since we will from now on have tutorials on a single airport, so there is no need to make them generic
