### ISSUE TITLE
Magneto switch is too long

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#930]
The magneto switch model is too long, this is how it looks now:

![](https://user-images.githubusercontent.com/13608602/29731670-80081514-89e5-11e7-93e1-dd1787364b80.png)

And this is how it should look:

![](https://camo.githubusercontent.com/e0caee3bad89c3178d6cdf94787a2f056012502c/68747470733a2f2f7777772e61746176696174696f6e2e756b2f77702d636f6e74656e742f75706c6f6164732f323031362f31302f494d475f313736312d373632783435362e6a7067)

![](http://pad1.whstatic.com/images/thumb/4/4d/DSC00114_959.JPG/670px-DSC00114_959.JPG)

As a quick and dirty fix, the model can be moved in the z-axis as to hide the unwanted length "inside" the panel.

**Comment by okroth** [comment]
The actual length of the nut is 0.5" = 12.7mm, the diameter s 1.068" = 27mm.
The diameter is given in a manual from Continental, the length I did measure from photos, using the diameter as reference.
![grafik](https://user-images.githubusercontent.com/10168496/30025563-5fe4b1b6-9179-11e7-9bfe-7560a5ea4ac2.png)

**Comment by gilbertohasnofb** [comment]
Hmm, this issue has been fixed but not closed, see:

![fg](https://user-images.githubusercontent.com/5700795/36554403-194e9974-17f7-11e8-958f-8c62a261d578.jpg)

**Comment by gilbertohasnofb** [comment]
I believe this was fixed by #151

**Comment by gilbertohasnofb** [comment]
Oh gosh, this issue was a mistake by me, apologies: the long magneto switch belonged to the c182s and not to this project! My report was in the wrong repository... anyway, both aircraft are fine now :smile:
