### ISSUE TITLE
C172P JSBSim model fcs/left-aileron-pos-rad

### ISSUE THREAD

**Issue by okroth** [c172p-team/c172p-detailed#931]
I went through the JSBSim parameters of the C172P model in FGFS to insert some force-feedback formulas (hinge moment * gear factor) and found a peculiarity:
The roll moment, side force, and yaw moment from aileron deflection use the left aileron deflection (in rad) only.
This will introduce an error, as the aileron is deflected downwards to -20 degrees, but only 15 degrees upwards. This is true in the real C172 the same way, to reduce adverse yaw.

Now, as only the left ailerons deflection is used in the formulas, turning the yoke clockwise (for a right turn) is 33% more effective then turning it counter-clockwise (for a left turn).
Possibly, one should not use the actual deflection of a single aileron, but the fcs/roll-trim-sum (computed as sum of fcs/aileron-cmd-norm and fcs/roll-trim-cmd-norm), of course with adjusted factors?

**Comment by dany93** [comment]
You are right. I think that it is a historical flaw from Aeromatic (initially assuming that aileron deflection are equal for up and down ).
I'm going to see what can be done. Rather than taking some  roll-trim-cmd-norm, I'd prefer attempting to implement an average angle value for right and left, in order to keep the linear aerodynamic coefficients consistency (conventionally per radian if I understand well). Possibly with the same factor.
Looking at it, I see that there are other mistakes or weird code in the aileron deflection limits.

The ailerons are rarely pushed at full deflection, which may explain why this is not sensed at piloting.

**Comment by okroth** [comment]
Hi,


Am 28.08.2017 um 10:39 schrieb dany93:
>
> You are right. I think that it is a historical flaw from Aeromatic 
> (initially assuming that aileron deflection are equal for up and down ).
> I'm going to see what can be done. Rather than taking some 
> roll-trim-cmd-norm, I'd prefer attempting to implement an average 
> angle value for right and left, in order to keep the linear 
> aerodynamic coefficients consistency (conventionally per radian if I 
> understand well). Possibly with the same factor.
> Looking at it, I see that there are other mistakes or weird code in 
> the aileron deflection limits.
>
> The ailerons are rarely pushed at full deflection, which may explain 
> why this is not sensed at piloting.
>



I found some more oddities with the rudder:
the side force from rudder (CYdr) is only 38.1% of the 'classic' 172P, but
the yaw moment from rudder (Cndr) is 162.8%, while
the roll moment from rudder (Cldr) is same on both.

IMHO, it is not likely that side force is decreased, while one moment it 
creates gets bigger and the other not.

-- 
Oliver Kroth

**Comment by okroth** [comment]
Hi dany93

Am 28.08.2017 um 10:39 schrieb dany93:
>
> You are right. I think that it is a historical flaw from Aeromatic 
> (initially assuming that aileron deflection are equal for up and down ).
> I'm going to see what can be done. Rather than taking some 
> roll-trim-cmd-norm, I'd prefer attempting to implement an average 
> angle value for right and left, in order to keep the linear 
> aerodynamic coefficients consistency (conventionally per radian if I 
> understand well). Possibly with the same factor.
> Looking at it, I see that there are other mistakes or weird code in 
> the aileron deflection limits.
>
> The ailerons are rarely pushed at full deflection, which may explain 
> why this is not sensed at piloting.
>
You don't need to push the aileron to the max; the upward deflected 
aileron is always 33% ahead:

One could average ailerons like this:

             <function name="aero/coefficient/CYda">
                 <description>Side force due to aileron</description>
                 <product>
                     <property>aero/qbar-psf</property>
                     <property>metrics/Sw-sqft</property>
                     <sum>
<property>fcs/left-aileron-pos-rad</property>
                         <property>- fcs/right-aileron-pos-rad</property>
                     </sum
                     <value>-0.0250</value>
                 </product>
             </function>

Oliver

**Comment by dany93** [comment]
Hi Oliver,

Thanks, I've already done it, I think that it works.
I will push it shortly.

Dany

**Comment by wlbragg** [comment]
Does this apply to all Aeromatic produced FDM's? I noticed the Cub is the same.

**Comment by okroth** [comment]
> Does this apply to all Aeromatic produced FDM's? I noticed the Cub is 
> the same
>
At least to those that have different maximum travel for aileron up and 
down

-- 
Oliver

**Comment by dany93** [comment]
Yes, Aeromatic (and, I think, AeromatiC++ from Erik Hofman too) have this flaw.
Aeromatic is the common origin.
If up and down aileron deflections are equal  (left = -right), no problem.
If the FDM is modified to make up and down different, the flaw is present.
Practically, the effect is very weak (nobody will notice for most aircraft unless extreme tests with careful observations) but the FDM is formally flawed.

**Comment by dany93** [comment]
@okroth wrote:
> You don't need to push the aileron to the max; the upward deflected 
> aileron is always 33% ahead

_(rather the downwards? if I understand well what you are meaning)_
Anyway, yes, but as long as full deflection is not needed, all that the pilot has to do is to adjust the stick position. Which he does automatically.

**Comment by onox** [comment]
Fixed by PR #935
