### ISSUE TITLE
[Suggestion] Do you have plan to re-work for C172R ?

### ISSUE THREAD

**Issue by tonghuix** [c172p-team/c172p-detailed#942]
I suddenly found the C172R still in FGAddon and it less developed. https://github.com/FGMEMBERS/c172r Does it reasonable that based on C172P to re-work for C172R?

Because of some flying schools are using C172R due to it is a later version (1996) and not like C182R with a complex propellers. ...And also it may easily integrate G1000...

**Comment by HHS81** [comment]
@tonghuix Wait, you say FGAddon, but you link to FGMembers.... :  🙄 

Anyway.
I'm not part of the C172P-team, but I can say the C172R differs alot from the C172P: different propulsion, different panel, different fuel system. Luckily beside the different engine systems, fuel system, electronics everythings else is equal or similar to the existing C182S in FlightGear.

But the C172R never had the G1000, that's the C172S which makes use of it. The C172R uses the same panel design like the C182S or early C182T.

**Comment by tonghuix** [comment]
Errr, I was lazy to paste link from SF, so I link it from FGMembers, https://sourceforge.net/p/flightgear/fgaddon/HEAD/tree/trunk/Aircraft/c172r/

Sorry that I am not very familiar with Cessna production line, It's only a suggestion, to provide a more modernized training aircraft to newcomers.

**Comment by HHS81** [comment]
@tonghuix 

> Errr, I was lazy to paste link from SF, so I link it from FGMembers
I see 😄 

> Sorry that I am not very familiar with Cessna production line, It's only a suggestion, to provide a more modernized training aircraft to newcomers.

The production line is quite complex, and their products changes from year to year. But yeah, a Cessna172 S/ R would be nice

**Comment by tonghuix** [comment]
I learned some of flying schools prefer old style 172 N / P, most of them are flying club or operated by airport of local collage. Some flying schools which provide airliner licence training prefer 172R/S or SP, and most of them integrate with G1000 training as well.

OT, I just found a video about C172 history: https://www.youtube.com/watch?v=By0-bSkzMs4

**Comment by onox** [comment]
> but I can say the C172R differs alot from the C172P

I guess this can be closed as wont-fix.
