### ISSUE TITLE
Add G1000

### ISSUE THREAD

**Issue by stuartbuchanan** [c172p-team/c172p-detailed#943]
Hi All,

As mentioned on the mailing list, I'm making good progress on the G1000 implementation.

I'd really like to have this supported on some variant of the flagship c172, as it would be a create showcase both of a modern glass-panel 172, as well as FlightGear's capabilities.  Plus it would probably be fairly easy to make similar changes to the 182 as well.

Is anyone interested in helping with this?

-Stuart

**Comment by tonghuix** [comment]
Good job!

Refering #942 , may rework C172R and add G1000 for that plane.

**Comment by wlbragg** [comment]
I'll volunteer to take a look at installing it as a variant if it is not too complicated. Complicated as in the variant aircraft isn't too dissimilar to what we already have. In other words I am not up to making an entire new model of the Cessna, at least no by myself.
I think the first step is to identify what model would be the best fit for it.

**Comment by tonghuix** [comment]
@wlbragg maybe you have to co-work with C182 team. cc @HHS81

**Comment by onox** [comment]
@stuartbuchanan I've seen your work on the G1000 on the forum and it looks very nice. Not sure what is needed to add this to the c172p. Might be as simple as conditionally enabling (with select animations) certain models, or it might involve work on the dashboard 3D model to make it look nice.

There's also the G5 (see #925) which seems to be very simple compared to the G1000.

**Comment by wlbragg** [comment]
My hesitation is not knowing what equipment this replaces? If we could agree on a layout for the dash and if that is the only change that is needed, I think I could handle the modeling requirements and hooking it up. I like the idea of simply using a select animation and adding this as an option in the c172p GUI.

**Comment by HHS81** [comment]
I thought the c172p was meant to be realistic. The c172p is a 1981s model. I have never seen that such an old model had been converted to use a Garmin G1000. 

Only the much newer C172SP models does use it,  but this a completely different c172 with its fuel-injected engine and other things.

**Comment by onox** [comment]
Since the c172p is a relatively simple aircraft suitable for new FG users, perhaps it's better to stick to the analog instruments and optionally a G5 instrument and keep the G1000 for other GA aircraft?

**Comment by onox** [comment]
@stuartbuchanan Just an idea: maybe the FG launcher could provide a feature where if the user has spend a certain amount of time in a particular aircraft (for example the c172p) it unlocks/suggests an aircraft that is a bit more advanced (one that has a G1000 instrument)?

**Comment by wkitty42** [comment]
On 01/26/2018 10:08 AM, wlbragg wrote:
> My hesitation is not knowing what equipment this replaces? If we could agree on 
> a layout for the dash and if that is the only change that is needed, I think I 
> could handle the modeling requirements and hooking it up. I like the idea of 
> simply using a select animation and adding this as an option in the c172p GUI.


my understanding is that (just about?) all of the instruments are replaced... 
put two of these G1000's in the dash and you have a full glass cockpit... not 
sure if the radios would have to move... more sensors, too... should be able to 
to have full AP capabilities with this device and not the restricted 
capabilities of the current AP device/system ;)  basically a modern c172p...

**Comment by wkitty42** [comment]
On 01/26/2018 10:17 AM, HHS81 wrote:
> I thought the c172p was meant to be realistic. The c172p is a 1981s model. I 
> have never seen that such an old model had been converted to use a Garmin G1000.
> 
> Only the much newer C172SP models does use it, but this a completely different 
> c172 with its fuel-injected engine and other things.

perhaps it is not too much to start with the existing c172p and redo parts of it 
to come out with a c172sp? we have two engines for the c172p... surely another 
one can be fitted? are there any/many body style changes between the two?

**Comment by HHS81** [comment]
> perhaps it is not too much to start

It is much.

The C172SP is completely different aircraft compared with C172P.
The SP has a completly different interior, and some changes to the exterior.
The SP has completly different panel design (not just a G100 added)
The SP has a fuel-injected engine - take a look at the C182S to see how complex the simulation of it is.

And the support of many different engines makes the whole thing more and more difficult to maintain.

Sorry, but the idea of a 1981s C172P with a G1000 is compeltely nuts.....

**Comment by wkitty42** [comment]
it might be but if i had one, i would also have the expendable funds and would gladly convert it to a glass cockpit... IRL it is only a matter of $$$... in a sim, it is only a matter of drive ;)

**Comment by stuartbuchanan** [comment]
Hi All,

I had thought that the 172SP wasn’t that different from the 172P and just modifying the panel would be sufficient.  

Sounds like I was wrong.  :(

That’s a shame, as I think there are lots of people training and flying 172SP with G1000 and I think it would be very good to have one available. 

-Stuart

**Comment by tonghuix** [comment]
... And I also suggest 172R ref #942 , but it seems from 172R to 172S/SP, it changes a lot! Fuel system using fuel pump instead of carburetor. 

So it is better co-working with c182 team create a new aircraft.

**Comment by stuartbuchanan** [comment]
Yes, sounds like the c182 might be a better choice.  I'll contact them.

-Stuart

**Comment by tonghuix** [comment]
@stuartbuchanan Could you please try add G1000 to DA42 aircraft, it now already has a G1000, but less functional, if you can add G1000 to DA42, it will make it more to perfect!
