### ISSUE TITLE
Switches in KMA 20 instrument move dials in radio instruments

### ISSUE THREAD

**Issue by wkitty42** [c172p-team/c172p-detailed#949]
this was originally reported on the forums here...
[https://forum.flightgear.org/viewtopic.php?f=14&t=33695](url)

i've reproduced it in both the current c172p in FGData as well as the current craft in master on this repo...

here's the steps i followed...

1. before loading, i went to my ~/.fgfs/aircraft-data and deleted my c172p.xml file so i would start clean...
2. i started at EGLL and used the autostart... make sure you set the parking brake!
3. hit F12 for the radio stack
4. looked up EGLL radio freqs
5. tune COM1 to 128.07 (Heathrow Information)...
6. i didn't hear anything
7. i used my mouse (left mouse button) and toggled the COM1 switch up (ON)...
8. i hear the ATIS information
9. i used my wheel button to click the switch back to the center position (OFF)...
10. i don't hear the ATIS information any more
11. zoom in close and toggle the COM1 switch
12. you can see the radio's volume switch jump from all the way down (actually 10%) to about 75%

there's more confusion in there between those two switches, too... this also happens when flipping the switch down to the headphone position and back up...

what should happen is that the COM1 switch should only affect the sound... it should be off, speaker or headphone and the radio's volume button should not move... it should stay at the same volume setting no matter which position the COM1 switch is in... yes, this means that you may flip the speaker on and be blasted by the radio at 100% volume... same with flipping the headphones on...

**Comment by onox** [comment]
The issue is that the COM1/COM2/NAV1/NAV2 rocker switches in the top KMA 20 instrument modify the dials in the two radio instruments below it.

**Comment by wkitty42** [comment]
On 01/30/2018 02:54 AM, onox wrote:
> The issue is that the COM1/COM2/NAV1/NAV2 rocker switches in the top KMA 20 
> instrument modify the dials in the two radio instruments below it.

yes, if COM1 does it, the others probably do, too... i didn't check the other 
3-position switches, though... only the COM1 interaction as reported in the forum...

**Comment by wkitty42** [comment]
there're more details in the forum... i'm going to point to this bug report and maybe they'll come over and post here where we can keep up with it better...

**Comment by mathieugouin** [comment]
Hello, I was the original reporter of the issue, however, I found it with the stock c172p from the FlightGear installation.  Do you recommend I re-test with the latest master from github?

I'm happy to help :)

**Comment by mathieugouin** [comment]
> yes, if COM1 does it, the others probably do, too... i didn't check the other 3-position switches, though... only the COM1 interaction as reported in the forum...

COM1 & COM2 both exhibits the same problem.

I confirm NAV1, NAV2 & ADF retain their respective volume setting.  However, for these switches, setting to SPEAKER position has the effect of pulling the knob to IDENT mode.  This seems strange, but I assume this was done because there is no way of actually pulling the knob to ident mode by other means.

Refer to this image: http://wiki.flightgear.org/images/5/5e/C172p-cockpit2.jpg

**Comment by wkitty42** [comment]
i don't know about the push and pull of a knob but some craft do have such for numerous of their switches... i would imagine that their methodology could be employed in the c172p unless this is something that comes with the device in question... now that i think about it, this may actually be a problem over there instead of in the c172p... especially if this is an existing ""generic"" device that any craft can use...

**Comment by onox** [comment]
>  Do you recommend I re-test with the latest master from github?

I have already reproduced the problem with master.

**Comment by mathieugouin** [comment]
`but some craft do have such for numerous of their switches`

I tried with various combination of click, shift+click, ctrl+click and I was not able to pull directly the volume knob.  

Do you know the key combination to do so?

**Comment by wkitty42** [comment]
i don't know if there is such a keystroke for this device... if there is not, it may be possible to update it so there is... a quick look seems to show that the KAP140 autopilot is the only generic model used from FGData... you're on the right track, though... i just don't know which craft to provide as an example... perhaps the IDG32X? they seem to have several functions on one knob whether it is pushed in, pulled out or in its default (middle?) position...

**Comment by onox** [comment]
> Do you know the key combination to do so?

Try the mouse scroll wheel.

**Comment by mathieugouin** [comment]
@onox Yes, the scroll wheel adjust the volume and when I scroll down to 0% it turns off the NAV/COM radio.

I was asking how to push/pull the knob to be in IDENT mode.

**Comment by onox** [comment]
I don't think those volume buttons can be pushed/pulled in the model.

**Comment by onox** [comment]
Actually you can push/pull them by moving the NAV1/NAV2 rocker switches 👎 

Would you like to try to fix this issue?

**Comment by mathieugouin** [comment]
> Would you like to try to fix this issue?

I can, but I will have a lot of questions... ;)  If you can bear with me.

Do you think this issue is possible to fix by only modifying xml & nasal code?  I'm asking because I'm not setup to recompile FG...

**Comment by onox** [comment]
> Do you think this issue is possible to fix by only modifying xml & nasal code?

Yes.

Feel free to ask any questions.

**Comment by wkitty42** [comment]
On 02/12/2018 02:31 PM, onox wrote:
> I don't think those volume buttons can be pushed/pulled in the model.


right but that's a problem... the one switch specifically says to pull for 
ident... my questions is is this something we need to fix in this craft or is 
this a generic model in FGData and the fix needs to be done over there so it is 
available for all craft using this device? in fact, that question applies to the 
problem of COM1 switch moving the volume control, too... do we fix it here or 
must it be fixed over there in FGData?

i know that some airbus craft (josh's IDG stuff) do push and pull on numerous of 
their knobs... i just don't know what keys or modifiers (shift, ctrl, alt) they 
are using to do it with...

**Comment by mathieugouin** [comment]
My initial attempt as a start was to try to make the KMA-20 switches only control the ident mode (equivalent of PULL), but do not affect the volume.

Ideally, to better mimic real-life, we should have both KMA switches & NAV/COM radio switches independent.  This would be possible if we find a proper key combination to do the PULL.

**Comment by mathieugouin** [comment]
A beginner question, how can I force the c172 aircraft to use my local git clone version instead of the installation default A/C.  I'm using the --aircraft-dir option but that does not seem to work.  

Thanks!

**Comment by dany93** [comment]
Hi @mathieugouin,

The --aircraft-dir option should work (if the path is written correctly).
Did you try by the Qt Launcher, by Addons > Additional aircraft locations ?

**Comment by mathieugouin** [comment]
Ok, found the issue with `--aircraft-dir`.

For the record, if it can help someone else.

I have my additional a/c in:
`/home/mgouin/Documents/FG/Aircrafts`
Inside I have
- `c172p`
- `c182s`
- ... and so on ...

I have set `--fg-aircraft=/home/mgouin/Documents/FG/Aircrafts`

Flight gear seem to find correctly c182s in the sub directory, but for some reason, it finds c172p in the default install dir instead of this path.

So I found that I can specify this option multiple time, so I have set it like this in my `.fgfsrc`

`--fg-aircraft=/home/mgouin/Documents/FG/Aircrafts/c172p`
`--fg-aircraft=/home/mgouin/Documents/FG/Aircrafts`

Now, I can start any of my downloaded A/C.

Thanks.

**Comment by wkitty42** [comment]
On 02/19/2018 12:08 AM, Mathieu Gouin wrote:
> So I found that I can specify this option multiple time, so I have set it like 
> this in my |.fgfsrc|
> 
> |--fg-aircraft=/home/mgouin/Documents/FG/Aircrafts/c172p|
> |--fg-aircraft=/home/mgouin/Documents/FG/Aircrafts|
> 
> Now, I can start any of my downloaded A/C.


you can also just stack them...

--fg-aircraft=/home/mgouin/Documents/FG/Aircrafts/c172p:/home/mgouin/Documents/FG/Aircrafts

note the colon (:) separating the two paths on linux... on winwhatever, it would 
be a semicolon (;)... i don't know what mac uses but i suspect the same as 
linux... --fg-scenery can be done this same way, too...

one key on the craft is getting the directories in the proper order... another 
key is that you point this directive to a base directory and not an individual 
craft's directory... --aircraft-dir is different in that you point it to the 
craft's directory... it doesn't work like --fg-aircraft... i think your problem 
shown above is that you were pointing directly to the c172p's directory instead 
of the base directory it resides in...

on my system my private hanger is in ~/myflightgear/Aircraft and there are 
several craft that reside in there... i also have a private hanger of FGAddon 
which is in ~/flightgear-dev/fgaddon-ng so i list my --fg-aircraft like this...

--fg-aircraft=/home/myuser/flightgear-dev/fgaddon-ng/Aircraft:/home/myuser/myflightgear/Aircraft

**Comment by mathieugouin** [comment]
Thanks, but I still cannot understand why FG would not find c172p inside my sub-directories?

with --fg-aircraft=~/Documents/FG/Aircrafts

This folder is the git clone of this repo:
~/Documents/FG/Aircrafts/c172p


It seems the search order is as follows:
1. Immediate folder option of --fg-aircraft (no recursion)
2. Default system installation folder
3. --fg-aircraft (with recursion)

**Comment by wkitty42** [comment]
On 02/19/2018 02:48 PM, Mathieu Gouin wrote:
> Thanks, but I still cannot understand why FG would not find c172p inside my 
> sub-directories?
> 
> with --fg-aircraft=~/Documents/FG/Aircrafts


FG doesn't know what ~ stands for in a path line... you have to specify it fully...

   --fg-aircraft=/home/youruser/Documents/FG/Aircrafts


i'm also assuming that your use of ~ and forward slashes "/" indicates you are 
on linux...

**Comment by mathieugouin** [comment]
Sorry for the confusion, I was actually full paths.

**Comment by mathieugouin** [comment]
Refer to pull request #990.
