### ISSUE TITLE
Use Shift+Q to reset view

### ISSUE THREAD

**Issue by onox** [c172p-team/c172p-detailed#952]
Shift + Q can be used to reset the camera to the default position/orientation. Several other aircraft have this like the P51D and the JA37. It's useful to quickly move the camera to point at the instruments when you were looking out of the window.

You can basically modify and use https://github.com/onox/p51d/commit/dd9d2e3b4d4a4fc37dcd084e8ac7a659865ad74d

**Comment by tonghuix** [comment]
Good suggestion! When I practice circling with a ground point, it's not easy for that. I have to focus more on instruments.

Another key is shift+NUM 8, it means view forward, but it's not default view.
