### ISSUE TITLE
Reduce reflections, particularly on the propeller

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#956]
I think the propeller is really too shiny now, as it seems to use the same coefficients as the fuselage. But it seems to me that in RL the propeller is quite matte:

![](http://www.parvinproperties.com/cessna/cessna-front-closeP5300108.jpg)

As a side note, perhaps our fuselage is also a bit too shiny? Even under sunlight a white 172 is also quite matte:

![](http://www.oy-reg.dk/billeder/l24313.jpg)

**Comment by gilbertohasnofb** [comment]
@wlbragg would you be interested in taking a look at this?

**Comment by HHS81** [comment]
@gilbertohasnofb 

> As a side note, perhaps our fuselage is also a bit too shiny? Even under sunlight a white 172 is also quite matte:

What you experience is the limit of FlightGears renderering system. The shinyness is o.k., but the renderer doesn't really take sunshine into account. For this we need real PBR (and not what will Mr. T. wants to sell us as PBR).
 I can show later some images from X-Plane showing how reflection reacts in sunlight there

**Comment by HHS81** [comment]
here are the images from X-Plane 11 Demo:
**With the sun:**
![cessna_172sp_12](https://user-images.githubusercontent.com/12649375/36051265-cc0e1ec6-0de9-11e8-9fb1-04651390c789.jpg)
**Against the sun:**
![cessna_172sp_13](https://user-images.githubusercontent.com/12649375/36051285-dc57750c-0de9-11e8-8c11-44b53ead3790.jpg)

**Looking really shiy (Due to fresnel effect and 90° against the sun)**
![cessna_172sp_15](https://user-images.githubusercontent.com/12649375/36051293-e02b1daa-0de9-11e8-9af2-c32b289aa38b.jpg)

**with the sun (low light)**
![cessna_172sp_18](https://user-images.githubusercontent.com/12649375/36051299-e78727ba-0de9-11e8-97f6-dd33431f8cb0.jpg)

**against the sun (low light):**
![cessna_172sp_17](https://user-images.githubusercontent.com/12649375/36051296-e468ff54-0de9-11e8-8fa3-475c88eba57b.jpg)

Our rendering system isn't able to deal with that, but real PBR would be able

**Comment by gilbertohasnofb** [comment]
> Our rendering system isn't able to deal with that, but real PBR would be able

Yes, I understand that, but we could tweak the parameters of the reflections according to what FG is capable right. IMO our reflections are too strong in most cases, so perhaps lowering them could give us a more compelling result.

**Comment by wlbragg** [comment]
> But it seems to me that in RL the propeller is quite matte:

I don't necessarily agree with this from looking at images on the Internet. Some are more reflective than others. Some are considerably more dirty than the aircraft. Seems to depend on environment and individual aircraft.

**Comment by gilbertohasnofb** [comment]
@wlbragg It seemed to me that the propeller is always substantially more matte than the fuselage in all photos I saw, but then again these things are difficult to discuss impartially. If you don't think that's the case then we can just close this issue as invalid.

**Comment by wlbragg** [comment]
Maybe some more input from others would help. I need to look closer at our model in the sim before I commit either way. I just noticed doing a Google search that there were some props that looked pretty reflective even high gloss yet others were matte and as I said a bunch were just plain dirty.

**Comment by wlbragg** [comment]
I remapped the propeller and changed the lighting and smoothness settings. I think that is the best I can do without a texture change.
![prop](https://user-images.githubusercontent.com/11069680/36609131-7caa48d4-1891-11e8-8936-e11709668652.jpg)

**Comment by gilbertohasnofb** [comment]
@wlbragg the photos I have are mainly glossy, I've seen just one or two that would be shiny:

![_dsc7938](https://user-images.githubusercontent.com/5700795/36609580-484f7ba2-18c5-11e8-8820-70b7c732eb96.jpg)

![charlotte_aerial_photography_-_cessna_172_ n73429 _ 3560076691](https://user-images.githubusercontent.com/5700795/36609590-4d8b7828-18c5-11e8-9fa2-916b5d23562b.jpg)

**Comment by wlbragg** [comment]
Then I think we need a texture change. Look at the new changes I pushed. Notice the lighter gray area, that actually looks like many of the propellers in the images you posted. Look at where on the texture that color is coming from, may give you some idea of the color you need for a new propeller texture. Also if you do a new propeller texture, we only need one, not both of them. We can use the existing second propeller texture area for something else.

**Comment by gilbertohasnofb** [comment]
@wlbragg working on it, I will push soon. But we actually need both sides because some propellers are not symmetrical due to decals (e.g. OH-CTL), and anyway we have space left in the `fuselage.png` so as of now space is not critical.

**Comment by wlbragg** [comment]
OK, then I'll map both sides.

**Comment by gilbertohasnofb** [comment]
Please don't change the mapping yet, I am just adjusting the old propeller textures. I don't think you will need to do anything else.

**Comment by wlbragg** [comment]
Except I already put both sides on one of the props.

**Comment by wlbragg** [comment]
Not only that but the way it was mapped the entire prop was mapped without taking into account the twist. That made the side of the twist that was not broad, not use the entire texture and we were getting half the prop without the entire texture on it.

**Comment by gilbertohasnofb** [comment]
Well, no problems, but I just pushed some new textures for the 5 HD liveries so do a git pull before continuing. Also, notice that the backside of the propeller is located on the right side of the texture file, though it seems this has never been mapped into the props:

![image](https://user-images.githubusercontent.com/5700795/36613263-d9babf10-18d0-11e8-9e9e-384dfe06deca.png)

The 4X-CHV has a black propeller on both sides, but other liveries such as OH-CTL will have a black backside and a more detailed front side.

**Comment by wlbragg** [comment]
>I just pushed some new textures for the 5 HD liveries

@gilbertohasnofb  I don't see your changes pushed anywhere.

**Comment by wlbragg** [comment]
@gilbertohasnofb 
This should be finished, please review before merging the PR.

**Comment by gilbertohasnofb** [comment]
@wlbragg I tested it and while the front of the propellers are looking much better, the back side looks a bit too reflective to me, it should be as matte as possible. I learned somewhere that the backside of propellers are always matte black because this way they minimize any sun reflexes towards the pilot's point of view. Would it be possible to take care of that?

**Comment by wlbragg** [comment]
I'm not sure what to do here. You changed the the front facing prop texture, but not the rear facing texture.
The rear facing texture is glossy looking so start with. I don't know if that is the issue or not.

My problem would be this is one object, I can't apply two different material settings on a single object. So the only thing I know to do is to make the rear facing texture less glossy looking and/or potentially changing the entire propeller mesh's material and smoothness settings, which I basically already did.

**Comment by gilbertohasnofb** [comment]
> The rear facing texture is glossy looking so start with. I don't know if that is the issue or not.

Yes, thanks for pointing that out, indeed I forgot to change that texture. But that won't change too much as the glossiness of the texture is not that apparent in the sim, but the reflection of the material is.

> My problem would be this is one object,

What about making the whole propeller completely matte then?

**Comment by gilbertohasnofb** [comment]
I will work on those textures as soon as the branch of that PR is cleaned.

**Comment by wlbragg** [comment]
>What about making the whole propeller completely matte then?

I more or less thought I did. Once you get the new texture in, I'll review the material and other settings of the propeller and see if I can do more.

>I will work on those textures as soon as the branch of that PR is cleaned.

:+1:

**Comment by gilbertohasnofb** [comment]
> The back side propeller texture still needs to be added to all liveries.

Forgot that this was a single object, I will do this to all liveries in the evening when I come back home.

**Comment by gilbertohasnofb** [comment]
Done. And you were right, after the texture modification the backside of the propeller looks like it should :tada:
