### ISSUE TITLE
Some internal objects needs smoothing

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#965]
Some internal objects needs smoothing:

![](https://user-images.githubusercontent.com/5700795/36178857-2f94d3b0-1112-11e8-998f-1900ca37955e.jpg)

![](https://user-images.githubusercontent.com/5700795/36178854-2eeebd90-1112-11e8-8375-06e3a20003e9.jpg)

![](https://user-images.githubusercontent.com/5700795/36178852-2ddd6da2-1112-11e8-8c46-19fba8cca4a9.jpg)

**Comment by wlbragg** [comment]
ET and extinguishers are now smoothed. The air vents are smoothed already, it's just the mesh is squared. The headphone is in fgdata and out of my realm.
I remapped the yoke, please review and comment.
The white unmapped mesh at the base of the doors is now mapped.
The trim wheel needs a texture as it is mapped to a solid black strip.
