### ISSUE TITLE
Add cables to rudder

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#969]
Add cables to rudder using these as reference:

![](https://camo.githubusercontent.com/7387f601a826201690ced63c67c9ef67803f455b/68747470733a2f2f6469736369706c65736f66666c696768742e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031362f30392f322d736b796861776b2d61756374696f6e2d656c657661746f722d736372617463682e6a7067)

![](https://camo.githubusercontent.com/c2f8858a7844f6ee24fed8d0db07b26e8bd5809f/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f484d4f41472e6a7067)

![](https://camo.githubusercontent.com/14b57a104610d5fbd3eedbbaa787d8afb79f5a9b/68747470733a2f2f7777772e782d706c61696e65642e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031372f30362f416972666f696c6c6162732d4331373253502d36332e6a706567)

**Comment by gilbertohasnofb** [comment]
One more reference photo:

![](http://www.weekendcfii.com/photos/c172preflt/C172_tail_tie.jpg)

**Comment by wlbragg** [comment]
I was trying to knock this one out and ran into a bit of a problem. After considerable time and effort I finished at a less than perfect animation of the system.
Problem:
If you look closely at the reference pictures, especially the close ups, and after trying to model a system with our model, you come to the conclusion that the bottom approx. 6-8 inches of the tail rudder and that part of the tails fuselage are both really close to horizontal, not diagonal like the rest of the rudder as you proceed from the bottom to the top, that may be what the cutout is for (semicircle). It may help for the transfer from horizontal to diagonal.

Compare the two images ,above and this one below
![n2937s_delaware_07](https://user-images.githubusercontent.com/11069680/36633117-517df9a2-1955-11e8-8d8d-1cffa0bda0b8.jpg)

Look at this second one (I think it is a Cessna 150G)
Notice the angle of the cable coming out of the fuselage,  even in the top image the angle of the mechanics is such that it look like it is converting the horizontal to a slight diagonal (probably to match the rudder hinge angle), yet the lines or line between the tail fuselage and the rudder look really close to horizontal.

I don't see how that mechanism works unless the cable is pushing and pulling at the same angle as the tail hinge. So the cable must terminate on the horizontal into a mechanics which at that point converts horizontal movement to a diagonal movement that is perpendicular to the rudder in order for the mechanics of the push pull to work correctly.

Anyway, here is what I have. I'm not thrilled with it but I really want to get on to the wing trim flaps!

https://youtu.be/zie9zaMR5dA

If this stands as is @gilbertohasnofb  we need to either add a dark shadow to the fuselage.png texture where the rudder cable port covers to give the appearance of it being cut out for the cable to go through. Or I should actually cut it out. Cutting it out may cause other issues such as portraying one sided mesh and the likes.

See my expert illustration of the subject below...
![ports](https://user-images.githubusercontent.com/11069680/36634703-156eb8d4-196e-11e8-83f0-77ceaf95a5f6.png)

**Comment by wlbragg** [comment]
@gilbertohasnofb I don't  want to push this to the #973 PR until I figured out what happened with your modifications to the liveries?

**Comment by gilbertohasnofb** [comment]
@wlbragg sorry, I had forgotten to push my textures, silly me. That's done now, please take a look if you can pull my commit.

**Comment by gilbertohasnofb** [comment]
> If this stands as is @gilbertohasnofb we need to either add a dark shadow to the fuselage.png texture where the rudder cable port covers to give the appearance of it being cut out for the cable to go through. Or I should actually cut it out. Cutting it out may cause other issues such as portraying one sided mesh and the likes.

I can try to fix that, but I am quite busy during this weekend. Could you wait for a couple of days?

**Comment by dany93** [comment]
@wlbragg wrote:
> I don't see how that mechanism works unless the cable is pushing and pulling at the same angle as the tail hinge. So the cable must terminate on the horizontal into a mechanics which at that point converts horizontal movement to a diagonal movement that is perpendicular to the rudder in order for the mechanics of the push pull to work correctly.

After some difficulty, I think (hope) to understand.
Your problem is that the rudder hinge axis is not vertical but diagonal, not in accordance with the pulling cables that are horizontal.
I agree, for mechanical considerations the best would be that the cables come out and pull perpendicularly to the hinge axis. That is, descending cables from middle to rear of the fuselage. This could have been obtained by adding high enough pulleys inside the fuselage at some distance before the lever at the rudder. Differently, the designers have chosen this compromise of pulling by cables which are close to horizontal (this position has to slightly adapt with rudder deflection).
This is not perfect (it adds vertical constraints) but IMHO it should work as well. With parts (particularly the lever) which must be more solid. Obviously, this angle discrepancy must be not too high.

Looking at your animation, I don't see what is "not good". Seems OK.

**Comment by gilbertohasnofb** [comment]
@wlbragg I just took a quick look at the c172p and the new rudder cables look great. But is the lack of smoothing on the ball intentional?

![fg](https://user-images.githubusercontent.com/5700795/36640828-2ee75400-1a1e-11e8-9afd-691b0903d5b5.jpg)

**Comment by wlbragg** [comment]
Good, if you guys are OK with it so am I. It's the perfectionist coming out in me. I've spent enough time on it and am ready to move on.
@gilbertohasnofb I'll see if I can get. The ball to be smooth.

**Comment by gilbertohasnofb** [comment]
> Good, if you guys are OK with it so am I. It's the perfectionist coming out in me. I've spent enough time on it and am ready to move on.

It's looking really nice, @wlbragg! :smile: 

I will see if I manage to make some time today to add the shadows to the fuselage in those areas you asked me, so that we can move on with that PR

**Comment by gilbertohasnofb** [comment]
> If this stands as is @gilbertohasnofb we need to either add a dark shadow to the fuselage.png texture where the rudder cable port covers to give the appearance of it being cut out for the cable to go through. Or I should actually cut it out. Cutting it out may cause other issues such as portraying one sided mesh and the likes.

Ok, I tried taking a look at this but I ran into a small problem. The 'box' into which the rudder cable enters is mapped to the same bit of texture as the fuselage under it. See my pic below: 

![fg-1](https://user-images.githubusercontent.com/5700795/36643446-54a10414-1a43-11e8-83d1-5a44caca6546.jpg)


So both the purple polygon and the red area are mapped to the same. I wanted to make the red area to be dark so that the final result would look like this:

![](https://camo.githubusercontent.com/9bd7e037671eb74ae48b722618b20054510e07cf/687474703a2f2f7777772e7765656b656e64636669692e636f6d2f70686f746f732f63313732707265666c742f433137325f7461696c5f7469652e6a7067)

So what about this: what if I darken those areas of the fuselage but at the same time I would add a new texture to `fuselage.png` so that you can map it to the purple box? Does that make sense to you?

So let me know if this is what you had in mind and then I will get to work on it.

**Comment by wlbragg** [comment]
>So both the purple polygon and the red area are mapped to the same

Yeah, I wasn't considering that. Yes that makes sense it would be less work for you if I just map the "separated ports objects to a different location on the fuselage. Unless you think a custom texture for it would be better. 

Which ever way you want to go is fine with me.

Does this help your for placing the shadow...

![port](https://user-images.githubusercontent.com/11069680/36644616-62f74d00-1a22-11e8-9e6d-ed41af2ade17.png)

![star](https://user-images.githubusercontent.com/11069680/36644618-6603273a-1a22-11e8-8b61-875997ebad7b.png)

**Comment by gilbertohasnofb** [comment]
Yes, that helps a lot. I will work on this and let you know once it's done. I will add the shadow on those places and then add a new texture for the box itself somewhere else, ok? These should be livery dependent, of course.

**Comment by wlbragg** [comment]
Hold on, what I gave you just now isn't accurate. My mind's not working this morning.

**Comment by wlbragg** [comment]
That is just where I mapped the port and it is not proportioned or positioned exactly.
it is already a separate object from the fuselage. We need to figure out how to give you the exact location of the mesh object ,right?

**Comment by wlbragg** [comment]
![port](https://user-images.githubusercontent.com/11069680/36644846-aeb71ff6-1a25-11e8-844e-d81f8c3cce10.png)

**Comment by gilbertohasnofb** [comment]
Thanks, I will give these a shot.

**Comment by wlbragg** [comment]
Looking a bit forward with this. I am going to have to make the ports two sided and shade the inside also or it wont look right. I can use the location your shading to do this if you make the shadow large enough (or precise enough) that it extends into the flat outside edge of the ports.

**Comment by wlbragg** [comment]
![shade](https://user-images.githubusercontent.com/11069680/36644998-ff030540-1a27-11e8-8165-108f17c4a5c3.jpg)

**Comment by wlbragg** [comment]
>But is the lack of smoothing on the ball intentional?

I smoothed the entire fixture, simply forgot to during construction. I'll wait to push it until your done with the texture.

**Comment by gilbertohasnofb** [comment]
Great :+1:  Working on it now

**Comment by wlbragg** [comment]
@gilbertohasnofb 
Now that your deep into this, I just thought of another way to do this so you didn't have to do anything. I could have simply cut the fuselage in the shadow area without removing the mesh and mapped that part to a dark area on the fuselage.png texture.

Still can if your having to put to much effort into this?

**Comment by gilbertohasnofb** [comment]
@wlbragg actually that solution sounds good, I did not put too much effort on it yet (I had to handle something non-FG related in this meantime). So let's try this solution.

I just pushed a new black square to `fuselage.png`, see:

![image](https://user-images.githubusercontent.com/5700795/36645501-b68efcbc-1a61-11e8-8f80-175c3ebc44ed.png)

**Comment by gilbertohasnofb** [comment]
If it looks good with a full black shadow then this doesn't have to be livery dependant. On the other hand if the shadow should be a darker version of the fuselage colour (nearly black but not completely) then I would need to edit all liveries and we would need to make it livery-dependent. it's your choice.

**Comment by wlbragg** [comment]
OK give me a few to see what this looks like and then we can decide.

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by wlbragg** [comment]
OK, here it is. Turns out I didn't even have to touch the fuselage, when I made the knife cut on the fuselage it distorted the face so I opted out of that solution .Instead I made the rudder cable port a standalone 3 dimensional object with inside and outside faces. Thus I can map the inside face to a dark part texture and the outside faces to a light part of the texture.
I haven't pulled your new dark texture yet, I need to finish all my work so I can commit and do a pull for you work. So this dark area inside is currently mapped to a random dark part of fuselage.png (a part of the tire texture I think). Still gives us a good idea of what it is going to look like. Keep in mind the texture it is mapped to currently is not "jet black".
![fgfs-screen-001](https://user-images.githubusercontent.com/11069680/36646024-89ce4798-1a37-11e8-8b77-0cbb2fd7fbc0.png)

**Comment by gilbertohasnofb** [comment]
I think this looks really good!

**Comment by wlbragg** [comment]
Finished with everything except pulling your new texture and mapping the inside to it.

These shots will serve as a comparison of using a dark shadow (your new one) or something less than black (what it is mapped to now).

![fgfs-screen-004](https://user-images.githubusercontent.com/11069680/36646266-efad0e70-1a3a-11e8-84ae-ca60e027f538.png)

![fgfs-screen-005](https://user-images.githubusercontent.com/11069680/36646268-f30a07d0-1a3a-11e8-80e2-ec09d2b5785a.png)

![fgfs-screen-006](https://user-images.githubusercontent.com/11069680/36646270-f5653a2c-1a3a-11e8-81e2-7f3f06ef46e3.png)

**Comment by gilbertohasnofb** [comment]
@wlbragg to be honest, I think this is looking so good it doesn't need a new texture! Let the natural light take care of it, and this way it inherits the fuselage colour.

**Comment by gilbertohasnofb** [comment]
If you agree, then I will remove that commit of mine, and so in that case please wait a second before pushing.

**Comment by gilbertohasnofb** [comment]
@wlbragg ok, I took the decision to remove my last commit in which I added that black rectangle to the default livery. Your results above look better than what will be achieved with that. So just make sure your local branch is up to date before pushing.

**Comment by wlbragg** [comment]
Oops, to late.
Now what?
How should I revert?

**Comment by gilbertohasnofb** [comment]
I see that you reintroduced the modified texture. I can remove that commit of mine. But have you mapped the model to that texture? I think your screenshots above look really good so we could leave it that way. Makes sense?

**Comment by gilbertohasnofb** [comment]
Actually I see that I would need to remove your last two commits as well, can I do that? I am talking about removing the `Remap rudder cable ports to new black texture` and `Merge branch 'issue-737' of https://github.com/c172p-team/c172p-detai…`

**Comment by wlbragg** [comment]
I'm not sure it is going to matter either way because I either map it to the tire texture (my pictures) or your new texture.

The only real difference would be the tire texture part I map it to is not quite so black and has a bit of texture to it.

Right now the 737 branch looks like your new texture is gone. even with my last push.

**Comment by wlbragg** [comment]
So I think the easiest (not cleanest) way to do this is you commit and push the new texture. Or I remap what is now in git to the tire.

**Comment by gilbertohasnofb** [comment]
Wait a second, this is getting really messy.

So are you telling me that the following screenshot of yours has the interior part of the box of the cables mapped to the tires?! 

![image](https://user-images.githubusercontent.com/5700795/36646687-eedb7a62-1a72-11e8-9043-27e15d5c58ea.png)

**Comment by gilbertohasnofb** [comment]
Please let's just clarify everything before making any further commits.

**Comment by wlbragg** [comment]
No, I think because you removed your commit it is mapped to a white background now (where your new texture used to be.). All I have to do is map it back to the tire and were done.
Or you can push the new texture and were done.

**Comment by wlbragg** [comment]
VS having to reverse any commits or clean up our less than stellar commit history.

**Comment by gilbertohasnofb** [comment]
> No, I think because you removed your commit it is mapped to a white background now (where your new texture used to be.). All I have to do is map it back to the tire and were done.

What I am trying to say is that the screenshots above look really good, better than if the interior was fully black! Now that we have a natural shadow cast from the object itself into its interior, we don't need any trickery as mapping to the tire or to a black square. So my idea is to simply map it to the same fuselage bit as the exterior part (which is how you initially mapped it) and that would look best. 

But I also want to clean all this mess with commits. First, you did reintroduce my commit and the current fuselage texture on that branch has the black square, and I am not sure why you are not seeing it. Anyway, I am thinking about doing the following:

1. revert 3 of those last 4 commits leaving only `Make inside faces on rudder cable ports and remap for shadow`
2. we make sure your branch copy is identical to the remote
3. map the interior to the same place as the exterior of the box, i.e. in the back of the fuselage
4. we would be good to go 

What do you think?

**Comment by wlbragg** [comment]
>First, you did reintroduce my commit and the current fuselage texture on that branch has the black square,

Your right, I checked it also.

Yes, do it. 

What am I going to have to do to get the changes you make, just pull and merge tracking 737 to local 737?

**Comment by gilbertohasnofb** [comment]
> What am I going to have to do to get the changes you make, just pull and merge tracking 737 to local 737?

I believe just a `git pull`, but let me check that first

**Comment by wlbragg** [comment]
One thing I don't see in the history is your removing the new texture?

Did I overwrite that history so it never happened?

**Comment by wlbragg** [comment]
Sorry, for the headache of doing something when nothing was required. I really didn't think it was going to be dark enough naturally. It may be that once I made the rudder cable ports interior faces it changed the way the lighting works on it.

**Comment by gilbertohasnofb** [comment]
@wlbragg My apologies but I somehow messed up the rebasing, got some commits doubled and did not manage to remove those. The branch is truly messy now and I would suggest we both wait for super @onox to save the day. I am sorry if this freezes the work until the fix, I really thought I had gotten the hang of it...

**Comment by wlbragg** [comment]
OK, I'll duplicate my local repo so I can continue on other stuff if I want. I'll wait until our Saviour shows up.

**Comment by gilbertohasnofb** [comment]
Thanks, and apologies again.

**Comment by wlbragg** [comment]
No apologies necessary, I think I started it.

Well get it done, one way or another.

Thanks for all your time and efforts.

**Comment by wlbragg** [comment]
OK, I think we got our wires crossed and both moved to fast.
We need to map the inside of the rudder cable ports to a dark texture.

This is mapped to the fuselage
![fgfs-screen-001](https://user-images.githubusercontent.com/11069680/36648836-d8469648-1a5d-11e8-80d9-aa6a68ddd307.png)

This is mapped to the dark tire texture
![fgfs-screen-002](https://user-images.githubusercontent.com/11069680/36648842-e5ba4658-1a5d-11e8-8d9e-069a513865b5.png)

I think we had it right either with your new texture or the tire.

**Comment by gilbertohasnofb** [comment]
@wlbragg I understand now, I thought those were natural shadows from the model. Apologies for all the confusion... anyway, just pushed a dark texture for you, see:

![image](https://user-images.githubusercontent.com/5700795/36648961-4745ee76-1a91-11e8-9fc9-955a115e84b0.png)

Please do not make this livery dependent as I did not add it to all liveries, only the default one.

**Comment by gilbertohasnofb** [comment]
And I also pushed a matte version of the backside of the propeller for the default livery only. Please do not make it livery dependent as all backsides are matte black.

**Comment by wlbragg** [comment]
>Please do not make it livery dependent as all backsides are matte black.

We have no choice as the Propeller is one object. If the front side has to be livery dependent then so will the back be. I guess you need to but the back side matte prop on all the liveries?

**Comment by wlbragg** [comment]
This is done on my end.
If we want the rudder cable ports to match the fuselage then they have to have livery dependency.  Unfortunately the object is all one piece so it needs the new interior black shadow texture added to all liveries. As it is now only the default livery has the interior shadow.

**Comment by gilbertohasnofb** [comment]
> Unfortunately the object is all one piece so it needs the new interior black shadow texture added to all liveries.

No problems. I will add that interior object to all liveries, together with the backside of the propeller.
