### ISSUE TITLE
Improve flaps 3D model

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#970]
Perhaps we still have some room for improvements for the 3D model of the flaps. The top image is how they currently look like (in red, in a cross-section of the wing) and below is how they look in RL:

![flaps](https://user-images.githubusercontent.com/5700795/36380019-a9ad84b6-1578-11e8-86d3-2e3494143010.png)

Reference photos:

![](https://airfactsjournal.com/files/2015/07/Cessna-flaps-down.jpg)

![](http://www.weekendcfii.com/photos/c172preflt/C172_flap_track.jpg)

![](http://www.weekendcfii.com/photos/c172preflt/C172_flap_rod.jpg)

**Comment by wlbragg** [comment]
Here is a preview of our next cool upgrade.
https://youtu.be/ERLddEDqC54

**Comment by wlbragg** [comment]
Done!

**Comment by gilbertohasnofb** [comment]
Looks amazing!!

**Comment by dany93** [comment]
Very nice!

**Comment by gilbertohasnofb** [comment]
Fixed by #973
