### ISSUE TITLE
Better UV-map of normal map on tail

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#974]
The UV-map of the normal map on tail is not looking too good:

![fg-1](https://user-images.githubusercontent.com/5700795/36453023-7f956fec-168e-11e8-92be-ab4470c13773.jpg)

Is this perhaps a side effect of fixing #430? If so, do we need to change the textures themselves rather than the UV-map of the normal textures, @wlbragg ?

**Comment by wlbragg** [comment]
Interesting, I'll take a look. It may have been a side effect of #430

**Comment by gilbertohasnofb** [comment]
Compare those images to: 

![c172p-preview8](https://user-images.githubusercontent.com/5700795/36454316-46e508b0-1693-11e8-8ac3-aa3f68646465.jpg)

**Comment by gilbertohasnofb** [comment]
But if that's a side effect of #430 then I am afraid I will need to somehow correct those textures manually by slowly distorting them and testing in the sim, which is a bit annoying but should be doable. This is particularly annoying since FG does not reload textures in the sim even if the model is reloaded, so every tiny tweak needs a full restart of the sim... :sob:

**Comment by wlbragg** [comment]
I think we're good. I just needed to move the mapping a tad. It's pushed.

**Comment by wlbragg** [comment]
I just moved the area where the paint strips are a little more. I think it is as far as I can go though.
