### ISSUE TITLE
Improve VHF antenna models

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#975]
Improve VHF antenna models:

![fg-5](https://user-images.githubusercontent.com/5700795/36453060-a53904d4-168e-11e8-8574-dbe2baea0730.jpg)

**Comment by legoboyvdlp** [comment]
A very similar antenna if not the same one:
![image](https://user-images.githubusercontent.com/10434911/36490219-b2a0299a-171f-11e8-990f-89231b606aeb.png)

**Comment by gilbertohasnofb** [comment]
Thanks lego, that's a better reference photo
