### ISSUE TITLE
Extinguisher object missing in master branch

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p-detailed#976]
Could not find at least one of the following objects for animation: 'extinguisher2'

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp do you mean you can't find the files? The extiguinsher is defined at `Models/Interior/FE-ELT/fe2.xml`

**Comment by onox** [comment]
I think it's a message printed by FG. The object in `fe2.ac` is called `extinguisher`, but `fe2.xml` refers to `extinguisher2`.

**Comment by onox** [comment]
There's also an empty `<animation>` block in that file.

**Comment by legoboyvdlp** [comment]
Excdllent, thank you.
