### ISSUE TITLE
Investigate replacing current autopilot with ITAF:GA KAP140 module

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p-detailed#980]
it0uchpods asked me to investigate adding the ITAF:GA KAP140 module from his Warrior to the Cessna 172P. He says that it has far better logic controlling than the current KAP140, and is more stable. Also, he says he is willing to create a prototype and send it to you for your consideration.

The J3Cub currently uses the ITAF:GA, but not the KAP140 module.
The Warrior uses the KAP140 module for ITAF:GA

**Comment by onox** [comment]
Has he read https://github.com/c172p-team/c172p-detailed/issues/603#issuecomment-164127990 ?

**Comment by legoboyvdlp** [comment]
I'll let him know.

**Comment by it0uchpods** [comment]
I'm up to date.

J

**Comment by it0uchpods** [comment]
This can be closed.
