### ISSUE TITLE
Improve matching of fuselage texture

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#983]
The fuselage textures of all liveries are having some matching issues, some shades do not match when two parts are stitched together and some artifacts are also being shown.

![](https://user-images.githubusercontent.com/10434911/36479726-98cc2df2-1701-11e8-960e-3d5204f8e9d5.png)

![](https://user-images.githubusercontent.com/11069680/36512234-2222c9b2-172f-11e8-9da7-8b29e2bc72f2.jpg)

![](https://user-images.githubusercontent.com/11069680/36559099-8101f5c2-17d2-11e8-877a-f988644ac21d.jpg)

**Comment by gilbertohasnofb** [comment]
I am working on this right now and this is a tough one to fix. This is the best I could achieve:

![fg-0](https://user-images.githubusercontent.com/5700795/36691596-b5d43b62-1b2d-11e8-90ca-96ac68cf4e6c.jpg)
![fg-1](https://user-images.githubusercontent.com/5700795/36691597-b5fc17ae-1b2d-11e8-99c6-df9e9fefb76f.jpg)

Also, this will only affect the HD textures as the older ones are not layred in GIMP and therefore do not allow me to correct he overlay layer which gives t he shadowing to the liveries.

**Comment by legoboyvdlp** [comment]
Hey... it looks a lot better!
Thanks a lot :)

**Comment by wlbragg** [comment]
Much better, good job!
