### ISSUE TITLE
C172P, landing light in the wing or the nose?

### ISSUE THREAD

**Issue by legoboyvdlp** [c172p-team/c172p-detailed#985]
This is probably a stupid question, but I understood our 172P to be a 1981 model? Supposedly, "in 1982, the "P" saw the landing lights moved from the nose to the wing to increase bulb life", according to Wikipedia - could our landing light actually be that of the 1982, not the 1981? Or are we actually a 1982 172?

**Comment by tonghuix** [comment]
haha, I think it should be a 1982 C172P...

**Comment by wkitty42** [comment]
ummm... i thought our light was on the wing? that's where i remember it from back when we were getting 2016 stuff ready...

**Comment by legoboyvdlp** [comment]
It is on the wing. The 1982 model P moved the real life light to the wing, but I thought ours was a 1981 model, with the nose landing light.

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp where did you find this information? I think we should dig on this a bit further. Depending on the differences between a model P from 1981 and 1982, perhaps the easiest "fix" would be to change the year instead of the model, what do you think @wlbragg ?

**Comment by gilbertohasnofb** [comment]
> haha, I think it should be a 1982 C172P...
> i've always understood it to be an 82 model man_shrugging
> I thought ours was a 1981 model, with the nose landing light.

`c172p.xml` states 1982 but `c172p-set.xml` states 1981, and the latter is what is shown on FG Run. I will reopen this and fix this in a new PR.

**Comment by wlbragg** [comment]
I have no clue. But I would oppose any attempt to move that light, that wold be a real headache. I guess if it turns out we have to make a choice I would chose to make the aircraft the year that had the light in the wing. So long as the rest of the airframe is compatible.
