### ISSUE TITLE
Tips of new wings are not UV-mapped correctly

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#986]
Tips of new wings are not UV-mapped correctly.

Before the new wing, as the textures were intended:

![fg-5](https://user-images.githubusercontent.com/5700795/36573700-3a327488-183a-11e8-9654-75b83d90ede7.jpg)
![fg-6](https://user-images.githubusercontent.com/5700795/36573701-3a5685bc-183a-11e8-8afe-caa969095ffd.jpg)
![fg-7](https://user-images.githubusercontent.com/5700795/36573702-3a7466f4-183a-11e8-8cd6-1b4ff2488095.jpg)
![fg-8](https://user-images.githubusercontent.com/5700795/36573703-3a915912-183a-11e8-8690-3c11cf28f9ff.jpg)
![fg-9](https://user-images.githubusercontent.com/5700795/36573704-3ab3699e-183a-11e8-8fad-a2c6f5e64d13.jpg)

After the new wing:

![fg-0](https://user-images.githubusercontent.com/5700795/36573756-679d50be-183a-11e8-81d3-02d1acba34d8.jpg)
![fg-1](https://user-images.githubusercontent.com/5700795/36573757-67c01c20-183a-11e8-93bd-b39edd9f3b9e.jpg)
![fg-2](https://user-images.githubusercontent.com/5700795/36573758-67e291b0-183a-11e8-99b5-cd899504635f.jpg)
![fg-3](https://user-images.githubusercontent.com/5700795/36573759-67fdf180-183a-11e8-9521-2446142f4971.jpg)
![fg-4](https://user-images.githubusercontent.com/5700795/36573760-681aedda-183a-11e8-813e-5e0a47590da3.jpg)

**Comment by gilbertohasnofb** [comment]
@HHS81 would you be able to give us a hand or to point us in the right direction?

**Comment by gilbertohasnofb** [comment]
@wlbragg I spoke to Heiko and he is quite busy at the moment as well as having some issues with his computer, so I think we need to figure out on our own how to fix this. Unfortunately these tips are an essential part of the liveries and for me the rework of the outer model isn't completely finished while this is opened :cry: Do you know any other 3D modellers that we could ask for help?

**Comment by legoboyvdlp** [comment]
CaptB on the FlightGear forums is an excellent 3D modeller, and may be willing to help. He is currently occupied with the IDG-A32X, however.

**Comment by wlbragg** [comment]
Thank @legoboyvdlp I think this is not going to be needed.

@gilbertohasnofb I feel really stupid right now. I took another look at this and see the problem, totally missed it the first time around. I think I can fix this. All that is wrong is the tips are basically mirrored the wrong way?

**Comment by wlbragg** [comment]
Yeah I see what happened. We do have one issue though I am not sure how to rectify.

The default livery, I don't think the original picture was correct either. According to the texture and the way it is laid out, I don't see how you get that mapping. I think it was already broke. I think I can get close with the rest of the liveries but the default is not ever going to be able to map as it was before as far as I can tell.

**Comment by gilbertohasnofb** [comment]
@wlbragg the default livery was not broken, it was looking good in the first picture I posted here in this issue. But if something needs adjustment texture-wise, I will be happy to do that.

**Comment by wlbragg** [comment]
@gilbertohasnofb can you find me a picture of the original default livery, maybe even the real life aircraft? I need to see the top, bottom and end of the wing.

**Comment by wlbragg** [comment]
Look a little closer at the "good" image of the default livery. Look at the very forward end. According to this livery that tip was never supposed to look like that.
![wingtip](https://user-images.githubusercontent.com/11069680/36987225-787ff74a-2061-11e8-80e2-ac24c84766ae.png)

**Comment by gilbertohasnofb** [comment]
![4x-chv-1](https://user-images.githubusercontent.com/5700795/36987633-ba39b5da-2094-11e8-8c4c-23a7b5fbf36a.jpg)
![4x-chv-2](https://user-images.githubusercontent.com/5700795/36987634-ba661eae-2094-11e8-841f-96126ea4726a.jpg)

**Comment by gilbertohasnofb** [comment]
I know it doesn't show the angle you wanted but perhaps this might help.

**Comment by wlbragg** [comment]
I was right there is not supposed to be any blue at the front end of the wing tip. Also one of the pinstripes is supposed to be blue.

**Comment by wlbragg** [comment]
![tip1](https://user-images.githubusercontent.com/11069680/36988107-914a1024-2063-11e8-9834-c7cc0d39e586.png)
![tip2](https://user-images.githubusercontent.com/11069680/36988112-927dd8b8-2063-11e8-8455-48b475cfc456.png)

**Comment by gilbertohasnofb** [comment]
> I was right there is not supposed to be any blue at the front end of the wing tip.

:+1: 

> Also one of the pinstripes is supposed to be blue (the top pinstripe)

Nice catch! The first photograph doesn't show it well but the second makes it very obvious.

So let me know once the UV-map is fixed from your side and I will then work on the texture of the default livery. Just let me know once you have it pushed somewhere, ok? I might have time still tonight to work on this. 

Can't believe we are this close to be done with the external model! :smile:

**Comment by wlbragg** [comment]
It doesn't show where the dividing line is from blue on the top of the wing to white on the bottom, any suggestions?
 ![tip](https://user-images.githubusercontent.com/11069680/36988630-f1155c74-2064-11e8-89dc-4f46156b7070.png)

**Comment by gilbertohasnofb** [comment]
Something in between the middle and bottom ones, see:

![](https://cdn.jetphotos.com/full/6/47067_1459285778.jpg)

**Comment by wlbragg** [comment]
Just pushed the changes. I think the only thing you need to deal with is the default livery stripes and get rid of the blue block near the stripes.

**Comment by wlbragg** [comment]
Maybe this will help. As far as I know this is the only thing that needs changed.
![tipends](https://user-images.githubusercontent.com/11069680/36991698-1c760f2c-206e-11e8-9a31-08d45f341e73.png)

**Comment by wlbragg** [comment]
Oh, and OH-CTL texture may need the wing tip end adjusted if you want it rounded towards the leading edge. The wing mesh shape changed enough I couldn't do anything more for it.

**Comment by wlbragg** [comment]
There is one thing bugging me still. if I move the Nav lights down would you fix the offset in the code?
![screenshot_2018-03-05_12-17-34](https://user-images.githubusercontent.com/11069680/36992315-255c4064-2070-11e8-9c17-d29ee8dcb929.png)

**Comment by gilbertohasnofb** [comment]
@wlbragg no problems, I will work on the texture adjustments. Those should be fairly easy. 

> There is one thing bugging me still. if I move the Nav lights down would you fix the offset in the code?

What code, the procedural lights one? I can try taking a look at that but I have no idea how that works as I did not implement that myself.

**Comment by gilbertohasnofb** [comment]
But the lights do look much better in the last shot!

**Comment by wlbragg** [comment]
>What code, the procedural lights one? I can try taking a look at that but I have no idea how that works as I did not implement that myself.

If your OK with me moving the lights, I'll take care of the code. I think it looks better too. Only thing that might be an issue is some of the liveries have the nav light casing colored to match its position on the wing (see OH-CTL texture). That may have to change?

**Comment by gilbertohasnofb** [comment]
Please move the lights first and then I will take a look at the liveries, making sure the lights match the livery in colour.

**Comment by wlbragg** [comment]
Done!
