### ISSUE TITLE
AI wake code is outputting some warnings

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#993]
The following warnings have been introduced by the AI wake PR and are output to the log:

```
In file /home/gilberto/WorkingFG/c172p/c172p/c172p.xml: line 1903
No direction element specified in force object. Default is (0,0,0).

In file /home/gilberto/WorkingFG/c172p/c172p/c172p.xml: line 1911
No direction element specified in moment object. Default is (0,0,0).
```

**Comment by gilbertohasnofb** [comment]
@bcoconni I have opened a new issue for this so that we don't forget to fix it. Let me know if you want to submit a PR yourself.

**Comment by bcoconni** [comment]
@gilbertohasnofb 
As per your request, I submitted a new PR #994 to remove the warnings you mentioned above.

**Comment by gilbertohasnofb** [comment]
@bcoconni Thanks a lot, really appreciate it!
